/**
 * Field-position test generator.
 *
 * Reads each hand-written segment source under src/segments/<version>/, extracts
 * every setter, the `this.fields[N]` index it writes, and (for composite fields)
 * the component layout of the array it builds, then emits a PV1.test.ts-style
 * test asserting each value encodes into the correct field/component.
 *
 * Covers v2.3 (base classes) and v2.5.1 (subclasses that add their own setters).
 * Generated files carry an AUTO-GENERATED header: existing generated files are
 * overwritten, hand-written tests (no header) are never clobbered — the
 * generated test is written to <SEG>.positions.test.ts instead.
 *
 * Usage:
 *   npx tsx codegen/generate-field-position-tests.ts [--dry-run]
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  generateFieldPositionTest,
  type FieldPositionSetter,
} from "./generators/fieldPositionTest.ts";

const ROOT = join(fileURLToPath(import.meta.url), "../..");
const DRY_RUN = process.argv.includes("--dry-run");
const GENERATED_MARKER = "AUTO-GENERATED by codegen/generate-field-position-tests";
const VERSIONS = ["v2.3", "v2.5.1"];

const NON_SETTERS = new Set([
  "if", "for", "while", "switch", "catch", "function", "map", "forEach", "constructor",
]);
const ACRONYMS = new Set([
  "id", "ssn", "dea", "hic", "ub1", "ub2", "ub82", "ub92", "cx", "url", "dob", "dmv", "vip", "loa",
]);

function toFieldName(method: string): string {
  return method
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/\s+/)
    .map((w) => (ACRONYMS.has(w.toLowerCase()) ? w.toUpperCase() : w.charAt(0).toUpperCase() + w.slice(1)))
    .join(" ")
    .replace(/\bId\b/g, "ID");
}

/** Accumulate source from `startLine` until brackets/parens balance to zero. */
function statementFrom(lines: string[], startLine: number): string {
  let depth = 0;
  let started = false;
  const buf: string[] = [];
  for (let i = startLine; i < lines.length; i++) {
    buf.push(lines[i]);
    for (const ch of lines[i]) {
      if ("([{".includes(ch)) { depth++; started = true; }
      else if (")]}".includes(ch)) depth--;
    }
    if (started && depth <= 0) break;
  }
  return buf.join("\n");
}

/** Split a top-level comma list (ignoring commas nested in brackets/parens). */
function splitTopLevel(s: string): string[] {
  const out: string[] = [];
  let depth = 0;
  let cur = "";
  for (const ch of s) {
    if ("([{<".includes(ch)) depth++;
    else if (")]}>".includes(ch)) depth--;
    if (ch === "," && depth === 0) { out.push(cur); cur = ""; }
    else cur += ch;
  }
  if (cur.trim()) out.push(cur);
  return out;
}

/** Raw parameter strings of a setter signature (with `?`/type/default intact). */
function rawSignatureParams(lines: string[], sigLine: number): string[] {
  const text = statementFrom(lines, sigLine);
  const open = text.indexOf("(");
  if (open < 0) return [];
  let depth = 0;
  let end = -1;
  for (let i = open; i < text.length; i++) {
    if (text[i] === "(") depth++;
    else if (text[i] === ")") { depth--; if (depth === 0) { end = i; break; } }
  }
  if (end < 0) return [];
  const list = text.slice(open + 1, end).trim();
  return list ? splitTopLevel(list) : [];
}

/** Count leading required params (not optional `?`, defaulted `=`, or rest `...`). */
function requiredParamCount(lines: string[], sigLine: number): number {
  let n = 0;
  for (const p of rawSignatureParams(lines, sigLine)) {
    const name = p.split(":")[0].trim();
    if (name.endsWith("?") || p.includes("=") || name.startsWith("...")) break;
    n++;
  }
  return n;
}

/** Parse a setter's signature parameter names, in order. */
function signatureParams(lines: string[], sigLine: number): string[] {
  const text = statementFrom(lines, sigLine);
  const open = text.indexOf("(");
  if (open < 0) return [];
  // Extract the balanced (...) param list.
  let depth = 0;
  let end = -1;
  for (let i = open; i < text.length; i++) {
    if (text[i] === "(") depth++;
    else if (text[i] === ")") { depth--; if (depth === 0) { end = i; break; } }
  }
  if (end < 0) return [];
  const list = text.slice(open + 1, end).trim();
  if (!list) return [];
  return splitTopLevel(list)
    .map((p) => p.trim().replace(/^\.\.\./, "").split(/[?:=]/)[0].trim())
    .filter(Boolean);
}

/**
 * From the fields[N] assignment statement, derive the component layout if the
 * field is built from a `createField([...])` / `createComponentsField([...])`
 * array literal of simple param/gap elements. Returns null otherwise.
 */
function componentLayout(
  stmt: string,
  params: string[],
): { params: string[]; slots: (number | null)[] } | null {
  const m = stmt.match(/create(?:Components)?Field\(\s*\[([\s\S]*)\]\s*\)/);
  if (!m) return null;
  const elements = splitTopLevel(m[1]);
  if (elements.length < 2) return null;
  const slots: (number | null)[] = [];
  for (const raw of elements) {
    const el = raw.trim().replace(/\s*(\|\||\?\?)\s*""$/, "").trim();
    if (el === "" || el === '""' || el === "undefined") { slots.push(null); continue; }
    if (/^[a-zA-Z_$][\w$]*$/.test(el)) {
      const idx = params.indexOf(el);
      if (idx < 0) return null; // references a non-param local — bail out
      slots.push(idx);
      continue;
    }
    return null; // function call / complex expression — not a simple composite
  }
  return { params, slots };
}

function extractSetters(src: string, isMSH: boolean): FieldPositionSetter[] {
  const lines = src.split("\n");
  const seen = new Set<string>();
  const setters: FieldPositionSetter[] = [];
  for (let i = 0; i < lines.length; i++) {
    const fm = lines[i].match(/this\.fields\[(\d+)\]\s*=\s*this\.create(?:Components)?Field/);
    if (!fm) continue;
    const index = Number(fm[1]);
    let method = "";
    let sigLine = -1;
    for (let j = i; j >= Math.max(0, i - 14); j--) {
      const nm = lines[j].match(/^\s*([a-zA-Z][a-zA-Z0-9_]*)\s*\(/);
      if (nm && !NON_SETTERS.has(nm[1])) { method = nm[1]; sigLine = j; break; }
    }
    if (!method) continue;
    const key = `${method}|${index}`;
    if (seen.has(key)) continue;
    seen.add(key);
    const params = signatureParams(lines, sigLine);
    const stmt = statementFrom(lines, i);
    const components = componentLayout(stmt, params) ?? undefined;
    setters.push({
      method,
      index,
      hl7Field: isMSH ? index + 2 : index + 1,
      fieldName: toFieldName(method),
      argCount: Math.max(1, requiredParamCount(lines, sigLine)),
      components,
    });
  }
  return setters;
}

let written = 0;
let skipped = 0;
for (const version of VERSIONS) {
  const dir = join(ROOT, "src/segments", version);
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts") && f !== "index.ts")
    .sort();

  for (const file of files) {
    const segName = file.slice(0, -3);
    const src = readFileSync(join(dir, file), "utf8");
    const setters = extractSetters(src, segName === "MSH");
    if (setters.length === 0) continue; // e.g. v2.5.1 subclasses that only add parse()

    // Pick a target path that never clobbers a hand-written test.
    const defaultPath = join(dir, `${segName}.test.ts`);
    let target = defaultPath;
    if (existsSync(defaultPath) && !readFileSync(defaultPath, "utf8").includes(GENERATED_MARKER)) {
      target = join(dir, `${segName}.positions.test.ts`);
    }

    const content = generateFieldPositionTest({ segName, version, setters });
    const rel = target.replace(ROOT + "/", "");
    if (DRY_RUN) {
      console.log(`[dry-run] ${rel}  (${setters.length} setters)`);
      continue;
    }
    writeFileSync(target, content, "utf8");
    console.log(`wrote  ${rel}  (${setters.length} setters)`);
    written++;
  }
}

console.log(`\nDone. ${written} written, ${skipped} skipped.`);
