/**
 * Generates a field-position test for a segment, in the style of the
 * hand-written src/segments/v2.3/PV1.test.ts.
 *
 * Each generated test instantiates the segment, calls one setter with sentinel
 * value(s), encodes, and asserts the value lands at the exact expected field.
 * `encode()` emits `SEG|f0|f1|...`, so a value written to fields[N] always
 * appears at split("|") index N+1. For non-MSH segments that index equals the
 * HL7 field number; MSH prepends the field-separator and encoding-characters
 * fields, so its HL7 field number is the split index + 1.
 *
 * The assertion checks the first component of the target field (setters that
 * take multiple values encode them as `a^b^...`, so the sentinel is component
 * one) and that the sentinel appears in exactly one field — which is what
 * catches off-by-one / wrong-field placement bugs.
 *
 * The setter list is extracted from the segment source (see
 * codegen/generate-field-position-tests.ts), so this stays a pure string
 * generator like the other generators/*.ts.
 */

/** One setter to assert. */
export interface FieldPositionSetter {
  /** Setter method name, e.g. "admitDateTime". */
  method: string;
  /** The `this.fields[N]` index the setter writes. */
  index: number;
  /** HL7 field number for the test label, e.g. 44 for PV1-44. */
  hl7Field: number;
  /** Human-readable field name for the test label, e.g. "Admit Date/Time". */
  fieldName: string;
  /** Number of sentinel args to pass so the call satisfies the signature. */
  argCount: number;
}

export interface FieldPositionTestConfig {
  /** Segment name / class name, e.g. "PV1". */
  segName: string;
  /** Directory version, e.g. "v2.3" (used only in the header comment). */
  version: string;
  /** Setters to assert, in field order. */
  setters: FieldPositionSetter[];
}

export function generateFieldPositionTest(config: FieldPositionTestConfig): string {
  const { segName, version, setters } = config;
  const isMSH = segName === "MSH";

  const cases = setters
    .map((s) => {
      const splitIndex = s.index + 1; // value written to fields[N] lands at split index N+1
      const args = Array.from({ length: s.argCount }, () => "SENTINEL").join(", ");
      return `  test(${JSON.stringify(`${segName}-${s.hl7Field} ${s.fieldName}`)}, () => {
    assertField(new ${segName}().${s.method}(${args}), ${splitIndex});
  });`;
    })
    .join("\n\n");

  const mshNote = isMSH
    ? `//
// NOTE: MSH-1 (field separator) and MSH-2 (encoding characters) occupy the
// start of the encoded segment, so an MSH-N value sits at split index N-1.
// The index passed to assertField() below is the split index, not the number.`
    : "";

  return `// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the ${segName} segment (HL7 ${version}). \`encode()\`
// emits \`${segName}|<field1>|<field2>|...\`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.${mshNote}
import { test, expect, describe } from "vitest";
import { ${segName} } from "./${segName}.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field \`splitIndex\` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: ${segName}, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe(${JSON.stringify(`${segName} field positions`)}, () => {
${cases}
});
`;
}
