/**
 * Generates a field-position test for a segment, in the style of the
 * hand-written src/segments/v2.3/PV1.test.ts.
 *
 * For each setter we assert where its value(s) encode:
 *  - simple setters: the value lands at the correct field (and nowhere else).
 *  - composite setters: each argument lands at the correct COMPONENT of that
 *    field, so interior gaps (e.g. a CX authority at .4) and component order
 *    are locked. `encode()` emits `SEG|f0|f1|...`, so a value written to
 *    fields[N] appears at split("|") index N+1 (true for MSH too, whose two
 *    special leading fields shift its HL7 field number by +2).
 *
 * The setter data is extracted from the segment source (see
 * codegen/generate-field-position-tests.ts), so this stays a pure string
 * generator like the other generators/*.ts.
 */

export interface FieldPositionSetter {
  /** Setter method name. */
  method: string;
  /** The `this.fields[N]` index the setter writes. */
  index: number;
  /** HL7 field number for the test label. */
  hl7Field: number;
  /** Human-readable field name for the test label. */
  fieldName: string;
  /** Number of sentinel args to pass for the simple field-position assertion. */
  argCount: number;
  /**
   * Present for composite setters whose field is built from an array literal.
   * `params` are the signature param names (in order); `slots[i]` is the index
   * into `params` for component i+1, or null for an interior gap.
   */
  components?: { params: string[]; slots: (number | null)[] };
}

export interface FieldPositionTestConfig {
  segName: string;
  version: string;
  setters: FieldPositionSetter[];
}

export function generateFieldPositionTest(config: FieldPositionTestConfig): string {
  const { segName, version, setters } = config;
  const isMSH = segName === "MSH";

  const cases = setters.map((s) => caseFor(segName, s)).join("\n\n");

  const mshNote = isMSH
    ? `//
// NOTE: MSH-1 (field separator) and MSH-2 (encoding characters) occupy the
// start of the encoded segment, so an MSH-N value sits at split index N-1.
// The index used below is the split index, not the HL7 field number.`
    : "";

  return `// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the ${segName} segment (HL7 ${version}). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.${mshNote}
import { test, expect, describe } from "vitest";
import { ${segName} } from "./${segName}.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field \`splitIndex\` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: ${segName}, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe(${JSON.stringify(`${segName} field positions`)}, () => {
${cases}
});
`;
}

function caseFor(segName: string, s: FieldPositionSetter): string {
  const splitIndex = s.index + 1; // value written to fields[N] lands at split index N+1
  const label = `${segName}-${s.hl7Field} ${s.fieldName}`;

  if (s.components && s.components.slots.length >= 2) {
    // Component-position test: distinct sentinel per param, assert exact layout.
    const { params, slots } = s.components;
    const sentinels = params.map((_, i) => `C${i + 1}`);
    const args = sentinels.map((c) => JSON.stringify(c)).join(", ");
    const expected = trimTrailing(
      slots.map((slot) => (slot === null ? "" : sentinels[slot])),
    ).join("^");
    return `  test(${JSON.stringify(label)}, () => {
    const parts = new ${segName}().${s.method}(${args}).encode().split("|");
    expect(parts[${splitIndex}]).toBe(${JSON.stringify(expected)});
  });`;
  }

  const simpleArgs = Array.from({ length: s.argCount }, () => "SENTINEL").join(", ");
  return `  test(${JSON.stringify(label)}, () => {
    assertField(new ${segName}().${s.method}(${simpleArgs}), ${splitIndex});
  });`;
}

function trimTrailing(values: string[]): string[] {
  const out = [...values];
  while (out.length > 0 && out[out.length - 1] === "") out.pop();
  return out;
}
