// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the ACC segment (HL7 v2.3). `encode()`
// emits `ACC|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { ACC } from "./ACC.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: ACC, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ACC field positions", () => {
  test("ACC-1 Accident Date Time", () => {
    assertField(new ACC().accidentDateTime(SENTINEL), 1);
  });

  test("ACC-2 Accident Code", () => {
    assertField(new ACC().accidentCode(SENTINEL), 2);
  });

  test("ACC-3 Accident Location", () => {
    assertField(new ACC().accidentLocation(SENTINEL), 3);
  });

  test("ACC-4 Auto Accident State", () => {
    assertField(new ACC().autoAccidentState(SENTINEL), 4);
  });

  test("ACC-5 Accident Job Related", () => {
    assertField(new ACC().accidentJobRelated(SENTINEL), 5);
  });

  test("ACC-6 Accident Death", () => {
    assertField(new ACC().accidentDeath(SENTINEL), 6);
  });

  test("ACC-7 Entered By", () => {
    assertField(new ACC().enteredBy(SENTINEL), 7);
  });

  test("ACC-8 Accident Description", () => {
    assertField(new ACC().accidentDescription(SENTINEL), 8);
  });

  test("ACC-9 Brought In By", () => {
    assertField(new ACC().broughtInBy(SENTINEL), 9);
  });

  test("ACC-10 Police Notified", () => {
    assertField(new ACC().policeNotified(SENTINEL), 10);
  });

  test("ACC-11 Accident Address", () => {
    assertField(new ACC().accidentAddress(SENTINEL), 11);
  });
});
