// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the ACC segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { ACC } from "./ACC.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: ACC, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ACC field positions", () => {
  test("ACC-1 Accident Date Time", () => {
    assertField(new ACC().accidentDateTime(SENTINEL), 1);
  });

  test("ACC-2 Accident Code", () => {
    const parts = new ACC().accidentCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3");
  });

  test("ACC-3 Accident Location", () => {
    assertField(new ACC().accidentLocation(SENTINEL), 3);
  });

  test("ACC-4 Auto Accident State", () => {
    const parts = new ACC().autoAccidentState({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[4]).toBe("C1^C2");
  });

  test("ACC-5 Accident Job Related", () => {
    assertField(new ACC().accidentJobRelated(SENTINEL), 5);
  });

  test("ACC-6 Accident Death", () => {
    assertField(new ACC().accidentDeath(SENTINEL), 6);
  });

  test("ACC-7 Entered By", () => {
    const parts = new ACC().enteredBy({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[7]).toBe("C1^C2^C3");
  });

  test("ACC-8 Accident Description", () => {
    assertField(new ACC().accidentDescription(SENTINEL), 8);
  });

  test("ACC-9 Brought In By", () => {
    assertField(new ACC().broughtInBy(SENTINEL), 9);
  });

  test("ACC-10 Police Notified", () => {
    assertField(new ACC().policeNotified(SENTINEL), 10);
  });

  test("ACC-11 Accident Address", () => {
    const parts = new ACC().accidentAddress({ street: "C1", city: "C2", state: "C3", zip: "C4" }).encode().split("|");
    expect(parts[11]).toBe("C1^^C2^C3^C4");
  });
});
