// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the AIG segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { AIG } from "./AIG.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: AIG, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIG field positions", () => {
  test("AIG-1 Set ID", () => {
    assertField(new AIG().setId(SENTINEL), 1);
  });

  test("AIG-2 Segment Action Code", () => {
    assertField(new AIG().segmentActionCode(SENTINEL), 2);
  });

  test("AIG-3 Resource ID", () => {
    const parts = new AIG().resourceId("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("AIG-4 Resource Type", () => {
    const parts = new AIG().resourceType("C1", "C2", "C3").encode().split("|");
    expect(parts[4]).toBe("C1^C2^C3");
  });

  test("AIG-5 Resource Group", () => {
    const parts = new AIG().resourceGroup("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("AIG-6 Resource Quantity", () => {
    assertField(new AIG().resourceQuantity(SENTINEL), 6);
  });

  test("AIG-7 Resource Quantity Units", () => {
    const parts = new AIG().resourceQuantityUnits("C1", "C2").encode().split("|");
    expect(parts[7]).toBe("C1^C2");
  });

  test("AIG-8 Start Date Time", () => {
    assertField(new AIG().startDateTime(SENTINEL), 8);
  });

  test("AIG-9 Start Date Time Offset", () => {
    assertField(new AIG().startDateTimeOffset(SENTINEL), 9);
  });

  test("AIG-10 Start Date Time Offset Units", () => {
    const parts = new AIG().startDateTimeOffsetUnits("C1", "C2").encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("AIG-11 Duration", () => {
    assertField(new AIG().duration(SENTINEL), 11);
  });

  test("AIG-12 Duration Units", () => {
    const parts = new AIG().durationUnits("C1", "C2").encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });

  test("AIG-13 Allow Substitution Code", () => {
    assertField(new AIG().allowSubstitutionCode(SENTINEL), 13);
  });

  test("AIG-14 Filler Status Code", () => {
    const parts = new AIG().fillerStatusCode("C1", "C2").encode().split("|");
    expect(parts[14]).toBe("C1^C2");
  });
});
