// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the AIG segment (HL7 v2.3). `encode()`
// emits `AIG|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { AIG } from "./AIG.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: AIG, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIG field positions", () => {
  test("AIG-1 Set ID", () => {
    assertField(new AIG().setId(SENTINEL), 1);
  });

  test("AIG-2 Segment Action Code", () => {
    assertField(new AIG().segmentActionCode(SENTINEL), 2);
  });

  test("AIG-3 Resource ID", () => {
    assertField(new AIG().resourceId(SENTINEL), 3);
  });

  test("AIG-4 Resource Type", () => {
    assertField(new AIG().resourceType(SENTINEL), 4);
  });

  test("AIG-5 Resource Group", () => {
    assertField(new AIG().resourceGroup(SENTINEL), 5);
  });

  test("AIG-6 Resource Quantity", () => {
    assertField(new AIG().resourceQuantity(SENTINEL), 6);
  });

  test("AIG-7 Resource Quantity Units", () => {
    assertField(new AIG().resourceQuantityUnits(SENTINEL), 7);
  });

  test("AIG-8 Start Date Time", () => {
    assertField(new AIG().startDateTime(SENTINEL), 8);
  });

  test("AIG-9 Start Date Time Offset", () => {
    assertField(new AIG().startDateTimeOffset(SENTINEL), 9);
  });

  test("AIG-10 Start Date Time Offset Units", () => {
    assertField(new AIG().startDateTimeOffsetUnits(SENTINEL), 10);
  });

  test("AIG-11 Duration", () => {
    assertField(new AIG().duration(SENTINEL), 11);
  });

  test("AIG-12 Duration Units", () => {
    assertField(new AIG().durationUnits(SENTINEL), 12);
  });

  test("AIG-13 Allow Substitution Code", () => {
    assertField(new AIG().allowSubstitutionCode(SENTINEL), 13);
  });

  test("AIG-14 Filler Status Code", () => {
    assertField(new AIG().fillerStatusCode(SENTINEL), 14);
  });
});
