// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the AIL segment (HL7 v2.3). `encode()`
// emits `AIL|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { AIL } from "./AIL.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: AIL, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIL field positions", () => {
  test("AIL-1 Set ID", () => {
    assertField(new AIL().setId(SENTINEL), 1);
  });

  test("AIL-2 Segment Action Code", () => {
    assertField(new AIL().segmentActionCode(SENTINEL), 2);
  });

  test("AIL-3 Location Resource ID", () => {
    assertField(new AIL().locationResourceId(SENTINEL), 3);
  });

  test("AIL-4 Location Type", () => {
    assertField(new AIL().locationType(SENTINEL), 4);
  });

  test("AIL-5 Location Group", () => {
    assertField(new AIL().locationGroup(SENTINEL), 5);
  });

  test("AIL-6 Start Date Time", () => {
    assertField(new AIL().startDateTime(SENTINEL), 6);
  });

  test("AIL-7 Start Date Time Offset", () => {
    assertField(new AIL().startDateTimeOffset(SENTINEL), 7);
  });

  test("AIL-8 Start Date Time Offset Units", () => {
    assertField(new AIL().startDateTimeOffsetUnits(SENTINEL), 8);
  });

  test("AIL-9 Duration", () => {
    assertField(new AIL().duration(SENTINEL), 9);
  });

  test("AIL-10 Duration Units", () => {
    assertField(new AIL().durationUnits(SENTINEL), 10);
  });

  test("AIL-11 Allow Substitution Code", () => {
    assertField(new AIL().allowSubstitutionCode(SENTINEL), 11);
  });

  test("AIL-12 Filler Status Code", () => {
    assertField(new AIL().fillerStatusCode(SENTINEL), 12);
  });
});
