// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the AIL segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { AIL } from "./AIL.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: AIL, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIL field positions", () => {
  test("AIL-1 Set ID", () => {
    assertField(new AIL().setId(SENTINEL), 1);
  });

  test("AIL-2 Segment Action Code", () => {
    assertField(new AIL().segmentActionCode(SENTINEL), 2);
  });

  test("AIL-3 Location Resource ID", () => {
    const parts = new AIL().locationResourceId({ pointOfCare: "C1", room: "C2", bed: "C3", facility: "C4" }).encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3^C4");
  });

  test("AIL-4 Location Type", () => {
    const parts = new AIL().locationType({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[4]).toBe("C1^C2");
  });

  test("AIL-5 Location Group", () => {
    const parts = new AIL().locationGroup({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("AIL-6 Start Date Time", () => {
    assertField(new AIL().startDateTime(SENTINEL), 6);
  });

  test("AIL-7 Start Date Time Offset", () => {
    assertField(new AIL().startDateTimeOffset(SENTINEL), 7);
  });

  test("AIL-8 Start Date Time Offset Units", () => {
    const parts = new AIL().startDateTimeOffsetUnits({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[8]).toBe("C1^C2");
  });

  test("AIL-9 Duration", () => {
    assertField(new AIL().duration(SENTINEL), 9);
  });

  test("AIL-10 Duration Units", () => {
    const parts = new AIL().durationUnits({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("AIL-11 Allow Substitution Code", () => {
    assertField(new AIL().allowSubstitutionCode(SENTINEL), 11);
  });

  test("AIL-12 Filler Status Code", () => {
    const parts = new AIL().fillerStatusCode({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });
});
