// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the AIP segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { AIP } from "./AIP.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: AIP, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIP field positions", () => {
  test("AIP-1 Set ID", () => {
    assertField(new AIP().setId(SENTINEL), 1);
  });

  test("AIP-2 Segment Action Code", () => {
    assertField(new AIP().segmentActionCode(SENTINEL), 2);
  });

  test("AIP-3 Personnel Resource ID", () => {
    const parts = new AIP().personnelResourceId({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("AIP-4 Resource Type", () => {
    const parts = new AIP().resourceType({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[4]).toBe("C1^C2^C3");
  });

  test("AIP-5 Resource Group", () => {
    const parts = new AIP().resourceGroup({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("AIP-6 Start Date Time", () => {
    assertField(new AIP().startDateTime(SENTINEL), 6);
  });

  test("AIP-7 Start Date Time Offset", () => {
    assertField(new AIP().startDateTimeOffset(SENTINEL), 7);
  });

  test("AIP-8 Start Date Time Offset Units", () => {
    const parts = new AIP().startDateTimeOffsetUnits({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[8]).toBe("C1^C2");
  });

  test("AIP-9 Duration", () => {
    assertField(new AIP().duration(SENTINEL), 9);
  });

  test("AIP-10 Duration Units", () => {
    const parts = new AIP().durationUnits({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("AIP-11 Allow Substitution Code", () => {
    assertField(new AIP().allowSubstitutionCode(SENTINEL), 11);
  });

  test("AIP-12 Filler Status Code", () => {
    const parts = new AIP().fillerStatusCode({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });
});
