// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the AIP segment (HL7 v2.3). `encode()`
// emits `AIP|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { AIP } from "./AIP.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: AIP, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIP field positions", () => {
  test("AIP-1 Set ID", () => {
    assertField(new AIP().setId(SENTINEL), 1);
  });

  test("AIP-2 Segment Action Code", () => {
    assertField(new AIP().segmentActionCode(SENTINEL), 2);
  });

  test("AIP-3 Personnel Resource ID", () => {
    assertField(new AIP().personnelResourceId(SENTINEL), 3);
  });

  test("AIP-4 Resource Type", () => {
    assertField(new AIP().resourceType(SENTINEL), 4);
  });

  test("AIP-5 Resource Group", () => {
    assertField(new AIP().resourceGroup(SENTINEL), 5);
  });

  test("AIP-6 Start Date Time", () => {
    assertField(new AIP().startDateTime(SENTINEL), 6);
  });

  test("AIP-7 Start Date Time Offset", () => {
    assertField(new AIP().startDateTimeOffset(SENTINEL), 7);
  });

  test("AIP-8 Start Date Time Offset Units", () => {
    assertField(new AIP().startDateTimeOffsetUnits(SENTINEL), 8);
  });

  test("AIP-9 Duration", () => {
    assertField(new AIP().duration(SENTINEL), 9);
  });

  test("AIP-10 Duration Units", () => {
    assertField(new AIP().durationUnits(SENTINEL), 10);
  });

  test("AIP-11 Allow Substitution Code", () => {
    assertField(new AIP().allowSubstitutionCode(SENTINEL), 11);
  });

  test("AIP-12 Filler Status Code", () => {
    assertField(new AIP().fillerStatusCode(SENTINEL), 12);
  });
});
