// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the AIS segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { AIS } from "./AIS.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: AIS, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIS field positions", () => {
  test("AIS-1 Set ID", () => {
    assertField(new AIS().setId(SENTINEL), 1);
  });

  test("AIS-2 Segment Action Code", () => {
    assertField(new AIS().segmentActionCode(SENTINEL), 2);
  });

  test("AIS-3 Universal Service ID", () => {
    const parts = new AIS().universalServiceId("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("AIS-4 Start Date Time", () => {
    assertField(new AIS().startDateTime(SENTINEL), 4);
  });

  test("AIS-5 Start Date Time Offset", () => {
    assertField(new AIS().startDateTimeOffset(SENTINEL), 5);
  });

  test("AIS-6 Start Date Time Offset Units", () => {
    const parts = new AIS().startDateTimeOffsetUnits("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });

  test("AIS-7 Duration", () => {
    assertField(new AIS().duration(SENTINEL), 7);
  });

  test("AIS-8 Duration Units", () => {
    const parts = new AIS().durationUnits("C1", "C2").encode().split("|");
    expect(parts[8]).toBe("C1^C2");
  });

  test("AIS-9 Allow Substitution Code", () => {
    assertField(new AIS().allowSubstitutionCode(SENTINEL), 9);
  });

  test("AIS-10 Filler Status Code", () => {
    const parts = new AIS().fillerStatusCode("C1", "C2").encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("AIS-11 Placer Supplemental Info", () => {
    const parts = new AIS().placerSupplementalInfo("C1", "C2").encode().split("|");
    expect(parts[11]).toBe("C1^C2");
  });

  test("AIS-12 Filler Supplemental Info", () => {
    const parts = new AIS().fillerSupplementalInfo("C1", "C2").encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });
});
