// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the AIS segment (HL7 v2.3). `encode()`
// emits `AIS|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { AIS } from "./AIS.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: AIS, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AIS field positions", () => {
  test("AIS-1 Set ID", () => {
    assertField(new AIS().setId(SENTINEL), 1);
  });

  test("AIS-2 Segment Action Code", () => {
    assertField(new AIS().segmentActionCode(SENTINEL), 2);
  });

  test("AIS-3 Universal Service ID", () => {
    assertField(new AIS().universalServiceId(SENTINEL), 3);
  });

  test("AIS-4 Start Date Time", () => {
    assertField(new AIS().startDateTime(SENTINEL), 4);
  });

  test("AIS-5 Start Date Time Offset", () => {
    assertField(new AIS().startDateTimeOffset(SENTINEL), 5);
  });

  test("AIS-6 Start Date Time Offset Units", () => {
    assertField(new AIS().startDateTimeOffsetUnits(SENTINEL), 6);
  });

  test("AIS-7 Duration", () => {
    assertField(new AIS().duration(SENTINEL), 7);
  });

  test("AIS-8 Duration Units", () => {
    assertField(new AIS().durationUnits(SENTINEL), 8);
  });

  test("AIS-9 Allow Substitution Code", () => {
    assertField(new AIS().allowSubstitutionCode(SENTINEL), 9);
  });

  test("AIS-10 Filler Status Code", () => {
    assertField(new AIS().fillerStatusCode(SENTINEL), 10);
  });

  test("AIS-11 Placer Supplemental Info", () => {
    assertField(new AIS().placerSupplementalInfo(SENTINEL), 11);
  });

  test("AIS-12 Filler Supplemental Info", () => {
    assertField(new AIS().fillerSupplementalInfo(SENTINEL), 12);
  });
});
