// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the AL1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { AL1 } from "./AL1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: AL1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("AL1 field positions", () => {
  test("AL1-1 Set ID", () => {
    assertField(new AL1().setId(SENTINEL), 1);
  });

  test("AL1-2 Allergen Type Code", () => {
    assertField(new AL1().allergenTypeCode(SENTINEL), 2);
  });

  test("AL1-3 Allergen", () => {
    assertField(new AL1().allergen({ code: SENTINEL, text: "", codingSystem: "" }), 3);
  });

  test("AL1-4 Allergy Severity Code", () => {
    assertField(new AL1().allergySeverityCode(SENTINEL), 4);
  });

  test("AL1-5 Allergy Reaction", () => {
    assertField(new AL1().allergyReaction(SENTINEL), 5);
  });

  test("AL1-6 Identification Date", () => {
    assertField(new AL1().identificationDate(SENTINEL), 6);
  });
});
