// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the CTI segment (HL7 v2.3). `encode()`
// emits `CTI|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { CTI } from "./CTI.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: CTI, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("CTI field positions", () => {
  test("CTI-1 Sponsor Study ID", () => {
    assertField(new CTI().sponsorStudyId(SENTINEL), 1);
  });

  test("CTI-2 Study Phase Identifier", () => {
    assertField(new CTI().studyPhaseIdentifier(SENTINEL), 2);
  });

  test("CTI-3 Study Scheduled Time Point", () => {
    assertField(new CTI().studyScheduledTimePoint(SENTINEL), 3);
  });
});
