// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the CTI segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { CTI } from "./CTI.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: CTI, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("CTI field positions", () => {
  test("CTI-1 Sponsor Study ID", () => {
    const parts = new CTI().sponsorStudyId({ entityIdentifier: "C1", namespaceId: "C2", universalId: "C3", universalIdType: "C4" }).encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3^C4");
  });

  test("CTI-2 Study Phase Identifier", () => {
    const parts = new CTI().studyPhaseIdentifier({ identifier: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3");
  });

  test("CTI-3 Study Scheduled Time Point", () => {
    const parts = new CTI().studyScheduledTimePoint({ identifier: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });
});
