// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the DB1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { DB1 } from "./DB1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: DB1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("DB1 field positions", () => {
  test("DB1-1 Set ID", () => {
    assertField(new DB1().setId(SENTINEL), 1);
  });

  test("DB1-2 Disabled Person Code", () => {
    assertField(new DB1().disabledPersonCode(SENTINEL), 2);
  });

  test("DB1-3 Disabled Person Identifier", () => {
    assertField(new DB1().disabledPersonIdentifier(SENTINEL), 3);
  });

  test("DB1-4 Disability Indicator", () => {
    assertField(new DB1().disabilityIndicator(SENTINEL), 4);
  });

  test("DB1-5 Disability Start Date", () => {
    assertField(new DB1().disabilityStartDate(SENTINEL), 5);
  });

  test("DB1-6 Disability End Date", () => {
    assertField(new DB1().disabilityEndDate(SENTINEL), 6);
  });

  test("DB1-7 Disability Return To Work Date", () => {
    assertField(new DB1().disabilityReturnToWorkDate(SENTINEL), 7);
  });

  test("DB1-8 Disability Unable To Work Date", () => {
    assertField(new DB1().disabilityUnableToWorkDate(SENTINEL), 8);
  });
});
