// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the DG1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { DG1 } from "./DG1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: DG1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("DG1 field positions", () => {
  test("DG1-1 Set ID", () => {
    assertField(new DG1().setId(SENTINEL), 1);
  });

  test("DG1-2 Diagnosis Coding Method", () => {
    assertField(new DG1().diagnosisCodingMethod(SENTINEL), 2);
  });

  test("DG1-3 Diagnosis Code", () => {
    assertField(new DG1().diagnosisCode({ code: SENTINEL, text: "", codingSystem: "" }), 3);
  });

  test("DG1-4 Diagnosis Description", () => {
    assertField(new DG1().diagnosisDescription(SENTINEL), 4);
  });

  test("DG1-5 Diagnosis Date Time", () => {
    assertField(new DG1().diagnosisDateTime(SENTINEL), 5);
  });

  test("DG1-6 Diagnosis Type", () => {
    assertField(new DG1().diagnosisType(SENTINEL), 6);
  });

  test("DG1-7 Major Diagnostic Category", () => {
    assertField(new DG1().majorDiagnosticCategory(SENTINEL), 7);
  });

  test("DG1-8 Diagnostic Related Group", () => {
    assertField(new DG1().diagnosticRelatedGroup(SENTINEL), 8);
  });

  test("DG1-9 Drg Approval Indicator", () => {
    assertField(new DG1().drgApprovalIndicator(SENTINEL), 9);
  });

  test("DG1-10 Drg Grouper Review Code", () => {
    assertField(new DG1().drgGrouperReviewCode(SENTINEL), 10);
  });

  test("DG1-11 Outlier Type", () => {
    assertField(new DG1().outlierType(SENTINEL), 11);
  });

  test("DG1-12 Outlier Days", () => {
    assertField(new DG1().outlierDays(SENTINEL), 12);
  });

  test("DG1-13 Outlier Cost", () => {
    assertField(new DG1().outlierCost(SENTINEL), 13);
  });

  test("DG1-14 Grouper Version And Type", () => {
    assertField(new DG1().grouperVersionAndType(SENTINEL), 14);
  });

  test("DG1-15 Diagnosis Priority", () => {
    assertField(new DG1().diagnosisPriority(SENTINEL), 15);
  });

  test("DG1-16 Diagnosing Clinician", () => {
    assertField(new DG1().diagnosingClinician({ id: SENTINEL, familyName: "", givenName: "" }), 16);
  });

  test("DG1-17 Diagnosis Classification", () => {
    assertField(new DG1().diagnosisClassification(SENTINEL), 17);
  });

  test("DG1-18 Confidential Indicator", () => {
    assertField(new DG1().confidentialIndicator(SENTINEL), 18);
  });

  test("DG1-19 Attestation Date Time", () => {
    assertField(new DG1().attestationDateTime(SENTINEL), 19);
  });
});
