// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the DRG segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { DRG } from "./DRG.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: DRG, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("DRG field positions", () => {
  test("DRG-1 Diagnostic Related Group", () => {
    const parts = new DRG().diagnosticRelatedGroup("C1", "C2", "C3").encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3");
  });

  test("DRG-2 Drg Assigned Date Time", () => {
    assertField(new DRG().drgAssignedDateTime(SENTINEL), 2);
  });

  test("DRG-3 Drg Approval Indicator", () => {
    assertField(new DRG().drgApprovalIndicator(SENTINEL), 3);
  });

  test("DRG-4 Drg Grouper Review Code", () => {
    assertField(new DRG().drgGrouperReviewCode(SENTINEL), 4);
  });

  test("DRG-5 Outlier Type", () => {
    const parts = new DRG().outlierType("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("DRG-6 Outlier Days", () => {
    assertField(new DRG().outlierDays(SENTINEL), 6);
  });

  test("DRG-7 Outlier Cost", () => {
    assertField(new DRG().outlierCost(SENTINEL), 7);
  });

  test("DRG-8 Drg Payor", () => {
    assertField(new DRG().drgPayor(SENTINEL), 8);
  });

  test("DRG-9 Outlier Reimbursement", () => {
    assertField(new DRG().outlierReimbursement(SENTINEL), 9);
  });

  test("DRG-10 Confidential Indicator", () => {
    assertField(new DRG().confidentialIndicator(SENTINEL), 10);
  });

  test("DRG-11 Drg Transfer Type", () => {
    assertField(new DRG().drgTransferType(SENTINEL), 11);
  });
});
