// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the ERR segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { ERR } from "./ERR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: ERR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ERR field positions", () => {
  test("ERR-1 Error Code And Location", () => {
    assertField(new ERR().errorCodeAndLocation(SENTINEL), 1);
  });

  test("ERR-2 Error Location", () => {
    const parts = new ERR().errorLocation("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3^C4^C5");
  });

  test("ERR-3 Hl7 Error Code", () => {
    const parts = new ERR().hl7ErrorCode("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("ERR-4 Severity", () => {
    assertField(new ERR().severity(SENTINEL), 4);
  });

  test("ERR-5 Application Error Code", () => {
    const parts = new ERR().applicationErrorCode("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("ERR-6 Application Error Parameter", () => {
    assertField(new ERR().applicationErrorParameter(SENTINEL), 6);
  });

  test("ERR-7 Diagnostic Info", () => {
    assertField(new ERR().diagnosticInfo(SENTINEL), 7);
  });

  test("ERR-8 User Message", () => {
    assertField(new ERR().userMessage(SENTINEL), 8);
  });

  test("ERR-9 Inform Person Indicator", () => {
    assertField(new ERR().informPersonIndicator(SENTINEL), 9);
  });
});
