// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the ERR segment (HL7 v2.3). `encode()`
// emits `ERR|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { ERR } from "./ERR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: ERR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ERR field positions", () => {
  test("ERR-1 Error Code And Location", () => {
    assertField(new ERR().errorCodeAndLocation(SENTINEL), 1);
  });

  test("ERR-2 Error Location", () => {
    assertField(new ERR().errorLocation(SENTINEL), 2);
  });

  test("ERR-3 Hl7 Error Code", () => {
    assertField(new ERR().hl7ErrorCode(SENTINEL), 3);
  });

  test("ERR-4 Severity", () => {
    assertField(new ERR().severity(SENTINEL), 4);
  });

  test("ERR-5 Application Error Code", () => {
    assertField(new ERR().applicationErrorCode(SENTINEL), 5);
  });

  test("ERR-6 Application Error Parameter", () => {
    assertField(new ERR().applicationErrorParameter(SENTINEL), 6);
  });

  test("ERR-7 Diagnostic Info", () => {
    assertField(new ERR().diagnosticInfo(SENTINEL), 7);
  });

  test("ERR-8 User Message", () => {
    assertField(new ERR().userMessage(SENTINEL), 8);
  });

  test("ERR-9 Inform Person Indicator", () => {
    assertField(new ERR().informPersonIndicator(SENTINEL), 9);
  });
});
