// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the EVN segment (HL7 v2.3). `encode()`
// emits `EVN|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { EVN } from "./EVN.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: EVN, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("EVN field positions", () => {
  test("EVN-1 Event Type Code", () => {
    assertField(new EVN().eventTypeCode(SENTINEL), 1);
  });

  test("EVN-2 Recorded Date Time", () => {
    assertField(new EVN().recordedDateTime(SENTINEL), 2);
  });

  test("EVN-3 Date Time Planned Event", () => {
    assertField(new EVN().dateTimePlannedEvent(SENTINEL), 3);
  });

  test("EVN-4 Event Reason Code", () => {
    assertField(new EVN().eventReasonCode(SENTINEL), 4);
  });

  test("EVN-5 Operator ID", () => {
    assertField(new EVN().operatorId(SENTINEL), 5);
  });

  test("EVN-6 Event Occurred", () => {
    assertField(new EVN().eventOccurred(SENTINEL), 6);
  });

  test("EVN-7 Event Facility", () => {
    assertField(new EVN().eventFacility(SENTINEL), 7);
  });
});
