// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the GT1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { GT1 } from "./GT1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: GT1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("GT1 field positions", () => {
  test("GT1-1 Set ID", () => {
    assertField(new GT1().setId(SENTINEL), 1);
  });

  test("GT1-2 Guarantor Number", () => {
    const parts = new GT1().guarantorNumber("C1", "C2").encode().split("|");
    expect(parts[2]).toBe("C1^^^C2");
  });

  test("GT1-3 Guarantor Name", () => {
    const parts = new GT1().guarantorName("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("GT1-4 Guarantor Spouse Name", () => {
    const parts = new GT1().guarantorSpouseName("C1", "C2").encode().split("|");
    expect(parts[4]).toBe("C1^C2");
  });

  test("GT1-5 Guarantor Address", () => {
    const parts = new GT1().guarantorAddress("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[5]).toBe("C1^^C2^C3^C4^C5");
  });

  test("GT1-6 Guarantor Phone Home", () => {
    assertField(new GT1().guarantorPhoneHome(SENTINEL), 6);
  });

  test("GT1-7 Guarantor Phone Business", () => {
    assertField(new GT1().guarantorPhoneBusiness(SENTINEL), 7);
  });

  test("GT1-8 Guarantor Date Of Birth", () => {
    assertField(new GT1().guarantorDateOfBirth(SENTINEL), 8);
  });

  test("GT1-9 Guarantor Sex", () => {
    assertField(new GT1().guarantorSex(SENTINEL), 9);
  });

  test("GT1-10 Guarantor Type", () => {
    assertField(new GT1().guarantorType(SENTINEL), 10);
  });

  test("GT1-11 Guarantor Relationship", () => {
    const parts = new GT1().guarantorRelationship("C1", "C2").encode().split("|");
    expect(parts[11]).toBe("C1^C2");
  });

  test("GT1-12 Guarantor SSN", () => {
    assertField(new GT1().guarantorSsn(SENTINEL), 12);
  });

  test("GT1-13 Guarantor Date Begin", () => {
    assertField(new GT1().guarantorDateBegin(SENTINEL), 13);
  });

  test("GT1-14 Guarantor Date End", () => {
    assertField(new GT1().guarantorDateEnd(SENTINEL), 14);
  });

  test("GT1-15 Guarantor Priority", () => {
    assertField(new GT1().guarantorPriority(SENTINEL), 15);
  });

  test("GT1-16 Guarantor Employer Name", () => {
    assertField(new GT1().guarantorEmployerName(SENTINEL), 16);
  });

  test("GT1-17 Guarantor Employer Address", () => {
    const parts = new GT1().guarantorEmployerAddress("C1", "C2", "C3", "C4").encode().split("|");
    expect(parts[17]).toBe("C1^^C2^C3^C4");
  });

  test("GT1-18 Guarantor Employer Phone", () => {
    assertField(new GT1().guarantorEmployerPhone(SENTINEL), 18);
  });

  test("GT1-19 Guarantor Employee ID", () => {
    assertField(new GT1().guarantorEmployeeId(SENTINEL), 19);
  });

  test("GT1-20 Guarantor Employment Status", () => {
    assertField(new GT1().guarantorEmploymentStatus(SENTINEL), 20);
  });

  test("GT1-21 Guarantor Organization Name", () => {
    const parts = new GT1().guarantorOrganizationName("C1", "C2", "C3").encode().split("|");
    expect(parts[21]).toBe("C1^C2^C3");
  });

  test("GT1-22 Guarantor Billing Hold Flag", () => {
    assertField(new GT1().guarantorBillingHoldFlag(SENTINEL), 22);
  });

  test("GT1-23 Guarantor Credit Rating Code", () => {
    const parts = new GT1().guarantorCreditRatingCode("C1", "C2", "C3").encode().split("|");
    expect(parts[23]).toBe("C1^C2^C3");
  });

  test("GT1-24 Guarantor Death Date Time", () => {
    assertField(new GT1().guarantorDeathDateTime(SENTINEL), 24);
  });

  test("GT1-25 Guarantor Death Flag", () => {
    assertField(new GT1().guarantorDeathFlag(SENTINEL), 25);
  });

  test("GT1-26 Guarantor Charge Adjustment Code", () => {
    const parts = new GT1().guarantorChargeAdjustmentCode("C1", "C2", "C3").encode().split("|");
    expect(parts[26]).toBe("C1^C2^C3");
  });

  test("GT1-27 Guarantor Household Annual Income", () => {
    const parts = new GT1().guarantorHouseholdAnnualIncome("C1", "C2").encode().split("|");
    expect(parts[27]).toBe("C1^C2");
  });

  test("GT1-28 Guarantor Household Size", () => {
    assertField(new GT1().guarantorHouseholdSize(SENTINEL), 28);
  });

  test("GT1-29 Guarantor Employer ID", () => {
    const parts = new GT1().guarantorEmployerId("C1", "C2", "C3").encode().split("|");
    expect(parts[29]).toBe("C1^^^C2^C3");
  });

  test("GT1-30 Guarantor Marital Status Code", () => {
    const parts = new GT1().guarantorMaritalStatusCode("C1", "C2", "C3").encode().split("|");
    expect(parts[30]).toBe("C1^C2^C3");
  });

  test("GT1-31 Guarantor Hire Effective Date", () => {
    assertField(new GT1().guarantorHireEffectiveDate(SENTINEL), 31);
  });

  test("GT1-32 Employment Stop Date", () => {
    assertField(new GT1().employmentStopDate(SENTINEL), 32);
  });

  test("GT1-33 Living Dependency", () => {
    assertField(new GT1().livingDependency(SENTINEL), 33);
  });

  test("GT1-34 Ambulatory Status", () => {
    assertField(new GT1().ambulatoryStatus(SENTINEL), 34);
  });

  test("GT1-35 Citizenship", () => {
    const parts = new GT1().citizenship("C1", "C2", "C3").encode().split("|");
    expect(parts[35]).toBe("C1^C2^C3");
  });

  test("GT1-36 Primary Language", () => {
    const parts = new GT1().primaryLanguage("C1", "C2", "C3").encode().split("|");
    expect(parts[36]).toBe("C1^C2^C3");
  });

  test("GT1-37 Living Arrangement", () => {
    assertField(new GT1().livingArrangement(SENTINEL), 37);
  });

  test("GT1-38 Publicity Code", () => {
    const parts = new GT1().publicityCode("C1", "C2", "C3").encode().split("|");
    expect(parts[38]).toBe("C1^C2^C3");
  });

  test("GT1-39 Protection Indicator", () => {
    assertField(new GT1().protectionIndicator(SENTINEL), 39);
  });

  test("GT1-40 Student Indicator", () => {
    assertField(new GT1().studentIndicator(SENTINEL), 40);
  });

  test("GT1-41 Religion", () => {
    const parts = new GT1().religion("C1", "C2", "C3").encode().split("|");
    expect(parts[41]).toBe("C1^C2^C3");
  });

  test("GT1-42 Mothers Maiden Name", () => {
    const parts = new GT1().mothersMaidenName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[42]).toBe("C1^C2^C3^C4^C5");
  });

  test("GT1-43 Nationality", () => {
    const parts = new GT1().nationality("C1", "C2", "C3").encode().split("|");
    expect(parts[43]).toBe("C1^C2^C3");
  });

  test("GT1-44 Ethnic Group", () => {
    const parts = new GT1().ethnicGroup("C1", "C2", "C3").encode().split("|");
    expect(parts[44]).toBe("C1^C2^C3");
  });

  test("GT1-45 Contact Person Name", () => {
    const parts = new GT1().contactPersonName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[45]).toBe("C1^C2^C3^C4^C5");
  });

  test("GT1-46 Contact Person Telephone", () => {
    assertField(new GT1().contactPersonTelephone(SENTINEL), 46);
  });

  test("GT1-47 Contact Reason", () => {
    const parts = new GT1().contactReason("C1", "C2", "C3").encode().split("|");
    expect(parts[47]).toBe("C1^C2^C3");
  });

  test("GT1-48 Contact Relationship", () => {
    assertField(new GT1().contactRelationship(SENTINEL), 48);
  });

  test("GT1-49 Job Title", () => {
    assertField(new GT1().jobTitle(SENTINEL), 49);
  });

  test("GT1-50 Job Code Class", () => {
    const parts = new GT1().jobCodeClass("C1", "C2").encode().split("|");
    expect(parts[50]).toBe("C1^C2");
  });

  test("GT1-51 Guarantor Employer Organization Name", () => {
    const parts = new GT1().guarantorEmployerOrganizationName("C1", "C2", "C3").encode().split("|");
    expect(parts[51]).toBe("C1^C2^C3");
  });

  test("GT1-52 Handicap", () => {
    assertField(new GT1().handicap(SENTINEL), 52);
  });

  test("GT1-53 Job Status", () => {
    assertField(new GT1().jobStatus(SENTINEL), 53);
  });

  test("GT1-54 Guarantor Financial Class", () => {
    const parts = new GT1().guarantorFinancialClass("C1", "C2").encode().split("|");
    expect(parts[54]).toBe("C1^C2");
  });

  test("GT1-55 Guarantor Race", () => {
    const parts = new GT1().guarantorRace("C1", "C2", "C3").encode().split("|");
    expect(parts[55]).toBe("C1^C2^C3");
  });
});
