// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the GT1 segment (HL7 v2.3). `encode()`
// emits `GT1|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { GT1 } from "./GT1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: GT1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("GT1 field positions", () => {
  test("GT1-1 Set ID", () => {
    assertField(new GT1().setId(SENTINEL), 1);
  });

  test("GT1-2 Guarantor Number", () => {
    assertField(new GT1().guarantorNumber(SENTINEL), 2);
  });

  test("GT1-3 Guarantor Name", () => {
    assertField(new GT1().guarantorName(SENTINEL), 3);
  });

  test("GT1-4 Guarantor Spouse Name", () => {
    assertField(new GT1().guarantorSpouseName(SENTINEL), 4);
  });

  test("GT1-5 Guarantor Address", () => {
    assertField(new GT1().guarantorAddress(SENTINEL), 5);
  });

  test("GT1-6 Guarantor Phone Home", () => {
    assertField(new GT1().guarantorPhoneHome(SENTINEL), 6);
  });

  test("GT1-7 Guarantor Phone Business", () => {
    assertField(new GT1().guarantorPhoneBusiness(SENTINEL), 7);
  });

  test("GT1-8 Guarantor Date Of Birth", () => {
    assertField(new GT1().guarantorDateOfBirth(SENTINEL), 8);
  });

  test("GT1-9 Guarantor Sex", () => {
    assertField(new GT1().guarantorSex(SENTINEL), 9);
  });

  test("GT1-10 Guarantor Type", () => {
    assertField(new GT1().guarantorType(SENTINEL), 10);
  });

  test("GT1-11 Guarantor Relationship", () => {
    assertField(new GT1().guarantorRelationship(SENTINEL), 11);
  });

  test("GT1-12 Guarantor SSN", () => {
    assertField(new GT1().guarantorSsn(SENTINEL), 12);
  });

  test("GT1-13 Guarantor Date Begin", () => {
    assertField(new GT1().guarantorDateBegin(SENTINEL), 13);
  });

  test("GT1-14 Guarantor Date End", () => {
    assertField(new GT1().guarantorDateEnd(SENTINEL), 14);
  });

  test("GT1-15 Guarantor Priority", () => {
    assertField(new GT1().guarantorPriority(SENTINEL), 15);
  });

  test("GT1-16 Guarantor Employer Name", () => {
    assertField(new GT1().guarantorEmployerName(SENTINEL), 16);
  });

  test("GT1-17 Guarantor Employer Address", () => {
    assertField(new GT1().guarantorEmployerAddress(SENTINEL), 17);
  });

  test("GT1-19 Guarantor Employee ID", () => {
    assertField(new GT1().guarantorEmployeeId(SENTINEL), 19);
  });

  test("GT1-20 Guarantor Employment Status", () => {
    assertField(new GT1().guarantorEmploymentStatus(SENTINEL), 20);
  });

  test("GT1-21 Guarantor Organization Name", () => {
    assertField(new GT1().guarantorOrganizationName(SENTINEL), 21);
  });
});
