// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the IN1 segment (HL7 v2.3). `encode()`
// emits `IN1|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { IN1 } from "./IN1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: IN1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("IN1 field positions", () => {
  test("IN1-1 Set ID", () => {
    assertField(new IN1().setId(SENTINEL), 1);
  });

  test("IN1-2 Insurance Plan ID", () => {
    assertField(new IN1().insurancePlanId(SENTINEL), 2);
  });

  test("IN1-3 Insurance Company ID", () => {
    assertField(new IN1().insuranceCompanyId(SENTINEL), 3);
  });

  test("IN1-4 Insurance Company Name", () => {
    assertField(new IN1().insuranceCompanyName(SENTINEL), 4);
  });

  test("IN1-5 Insurance Company Address", () => {
    assertField(new IN1().insuranceCompanyAddress(SENTINEL), 5);
  });

  test("IN1-6 Insurance Contact Person", () => {
    assertField(new IN1().insuranceContactPerson(SENTINEL), 6);
  });

  test("IN1-7 Insurance Phone Number", () => {
    assertField(new IN1().insurancePhoneNumber(SENTINEL), 7);
  });

  test("IN1-8 Group Number", () => {
    assertField(new IN1().groupNumber(SENTINEL), 8);
  });

  test("IN1-9 Group Name", () => {
    assertField(new IN1().groupName(SENTINEL), 9);
  });

  test("IN1-10 Insured Group Emp ID", () => {
    assertField(new IN1().insuredGroupEmpId(SENTINEL), 10);
  });

  test("IN1-11 Insured Group Emp Name", () => {
    assertField(new IN1().insuredGroupEmpName(SENTINEL), 11);
  });

  test("IN1-12 Plan Effective Date", () => {
    assertField(new IN1().planEffectiveDate(SENTINEL), 12);
  });

  test("IN1-13 Plan Expiration Date", () => {
    assertField(new IN1().planExpirationDate(SENTINEL), 13);
  });

  test("IN1-14 Authorization Info", () => {
    assertField(new IN1().authorizationInfo(SENTINEL), 14);
  });

  test("IN1-15 Plan Type", () => {
    assertField(new IN1().planType(SENTINEL), 15);
  });

  test("IN1-16 Name Of Insured", () => {
    assertField(new IN1().nameOfInsured(SENTINEL), 16);
  });

  test("IN1-17 Insured Relationship", () => {
    assertField(new IN1().insuredRelationship(SENTINEL), 17);
  });

  test("IN1-18 Insured Date Of Birth", () => {
    assertField(new IN1().insuredDateOfBirth(SENTINEL), 18);
  });

  test("IN1-19 Insured Address", () => {
    assertField(new IN1().insuredAddress(SENTINEL), 19);
  });

  test("IN1-20 Assignment Of Benefits", () => {
    assertField(new IN1().assignmentOfBenefits(SENTINEL), 20);
  });

  test("IN1-21 Coordination Of Benefits", () => {
    assertField(new IN1().coordinationOfBenefits(SENTINEL), 21);
  });

  test("IN1-22 Coord Of Ben Priority", () => {
    assertField(new IN1().coordOfBenPriority(SENTINEL), 22);
  });

  test("IN1-23 Notice Of Admission Flag", () => {
    assertField(new IN1().noticeOfAdmissionFlag(SENTINEL), 23);
  });

  test("IN1-47 Coverage Type", () => {
    assertField(new IN1().coverageType(SENTINEL), 47);
  });

  test("IN1-48 Handicap", () => {
    assertField(new IN1().handicap(SENTINEL), 48);
  });

  test("IN1-36 Policy Number", () => {
    assertField(new IN1().policyNumber(SENTINEL), 36);
  });

  test("IN1-37 Policy Deductible", () => {
    assertField(new IN1().policyDeductible(SENTINEL), 37);
  });
});
