// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the IN1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { IN1 } from "./IN1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: IN1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("IN1 field positions", () => {
  test("IN1-1 Set ID", () => {
    assertField(new IN1().setId(SENTINEL), 1);
  });

  test("IN1-2 Insurance Plan ID", () => {
    const parts = new IN1().insurancePlanId({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3");
  });

  test("IN1-3 Insurance Company ID", () => {
    const parts = new IN1().insuranceCompanyId({ id: "C1", assigningAuthority: "C2" }).encode().split("|");
    expect(parts[3]).toBe("C1^^^C2");
  });

  test("IN1-4 Insurance Company Name", () => {
    assertField(new IN1().insuranceCompanyName(SENTINEL), 4);
  });

  test("IN1-5 Insurance Company Address", () => {
    const parts = new IN1().insuranceCompanyAddress({ street: "C1", city: "C2", state: "C3", zip: "C4" }).encode().split("|");
    expect(parts[5]).toBe("C1^^C2^C3^C4");
  });

  test("IN1-6 Insurance Contact Person", () => {
    const parts = new IN1().insuranceContactPerson({ familyName: "C1", givenName: "C2" }).encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });

  test("IN1-7 Insurance Phone Number", () => {
    assertField(new IN1().insurancePhoneNumber(SENTINEL), 7);
  });

  test("IN1-8 Group Number", () => {
    assertField(new IN1().groupNumber(SENTINEL), 8);
  });

  test("IN1-9 Group Name", () => {
    assertField(new IN1().groupName(SENTINEL), 9);
  });

  test("IN1-10 Insured Group Emp ID", () => {
    assertField(new IN1().insuredGroupEmpId(SENTINEL), 10);
  });

  test("IN1-11 Insured Group Emp Name", () => {
    assertField(new IN1().insuredGroupEmpName(SENTINEL), 11);
  });

  test("IN1-12 Plan Effective Date", () => {
    assertField(new IN1().planEffectiveDate(SENTINEL), 12);
  });

  test("IN1-13 Plan Expiration Date", () => {
    assertField(new IN1().planExpirationDate(SENTINEL), 13);
  });

  test("IN1-14 Authorization Info", () => {
    const parts = new IN1().authorizationInfo({ authorizationNumber: "C1", date: "C2", source: "C3" }).encode().split("|");
    expect(parts[14]).toBe("C1^C2^C3");
  });

  test("IN1-15 Plan Type", () => {
    assertField(new IN1().planType(SENTINEL), 15);
  });

  test("IN1-16 Name Of Insured", () => {
    const parts = new IN1().nameOfInsured({ familyName: "C1", givenName: "C2", middleName: "C3" }).encode().split("|");
    expect(parts[16]).toBe("C1^C2^C3");
  });

  test("IN1-17 Insured Relationship", () => {
    const parts = new IN1().insuredRelationship({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[17]).toBe("C1^C2");
  });

  test("IN1-18 Insured Date Of Birth", () => {
    assertField(new IN1().insuredDateOfBirth(SENTINEL), 18);
  });

  test("IN1-19 Insured Address", () => {
    const parts = new IN1().insuredAddress({ street: "C1", city: "C2", state: "C3", zip: "C4" }).encode().split("|");
    expect(parts[19]).toBe("C1^^C2^C3^C4");
  });

  test("IN1-20 Assignment Of Benefits", () => {
    assertField(new IN1().assignmentOfBenefits(SENTINEL), 20);
  });

  test("IN1-21 Coordination Of Benefits", () => {
    assertField(new IN1().coordinationOfBenefits(SENTINEL), 21);
  });

  test("IN1-22 Coord Of Ben Priority", () => {
    assertField(new IN1().coordOfBenPriority(SENTINEL), 22);
  });

  test("IN1-23 Notice Of Admission Flag", () => {
    assertField(new IN1().noticeOfAdmissionFlag(SENTINEL), 23);
  });

  test("IN1-47 Coverage Type", () => {
    assertField(new IN1().coverageType(SENTINEL), 47);
  });

  test("IN1-48 Handicap", () => {
    assertField(new IN1().handicap(SENTINEL), 48);
  });

  test("IN1-36 Policy Number", () => {
    assertField(new IN1().policyNumber(SENTINEL), 36);
  });

  test("IN1-37 Policy Deductible", () => {
    assertField(new IN1().policyDeductible(SENTINEL), 37);
  });

  test("IN1-24 Notice Of Admission Date", () => {
    assertField(new IN1().noticeOfAdmissionDate(SENTINEL), 24);
  });

  test("IN1-25 Report Of Eligibility Flag", () => {
    assertField(new IN1().reportOfEligibilityFlag(SENTINEL), 25);
  });

  test("IN1-26 Report Of Eligibility Date", () => {
    assertField(new IN1().reportOfEligibilityDate(SENTINEL), 26);
  });

  test("IN1-27 Release Information Code", () => {
    assertField(new IN1().releaseInformationCode(SENTINEL), 27);
  });

  test("IN1-28 Pre Admit Cert", () => {
    assertField(new IN1().preAdmitCert(SENTINEL), 28);
  });

  test("IN1-29 Verification Date Time", () => {
    assertField(new IN1().verificationDateTime(SENTINEL), 29);
  });

  test("IN1-30 Verification By", () => {
    const parts = new IN1().verificationBy({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[30]).toBe("C1^C2^C3");
  });

  test("IN1-31 Type Of Agreement Code", () => {
    assertField(new IN1().typeOfAgreementCode(SENTINEL), 31);
  });

  test("IN1-32 Billing Status", () => {
    assertField(new IN1().billingStatus(SENTINEL), 32);
  });

  test("IN1-33 Lifetime Reserve Days", () => {
    assertField(new IN1().lifetimeReserveDays(SENTINEL), 33);
  });

  test("IN1-34 Delay Before LRDay", () => {
    assertField(new IN1().delayBeforeLRDay(SENTINEL), 34);
  });

  test("IN1-35 Company Plan Code", () => {
    assertField(new IN1().companyPlanCode(SENTINEL), 35);
  });

  test("IN1-38 Policy Limit Amount", () => {
    const parts = new IN1().policyLimitAmount({ price: "C1", priceType: "C2" }).encode().split("|");
    expect(parts[38]).toBe("C1^C2");
  });

  test("IN1-39 Policy Limit Days", () => {
    assertField(new IN1().policyLimitDays(SENTINEL), 39);
  });

  test("IN1-40 Room Rate Semi Private", () => {
    const parts = new IN1().roomRateSemiPrivate({ price: "C1", priceType: "C2" }).encode().split("|");
    expect(parts[40]).toBe("C1^C2");
  });

  test("IN1-41 Room Rate Private", () => {
    const parts = new IN1().roomRatePrivate({ price: "C1", priceType: "C2" }).encode().split("|");
    expect(parts[41]).toBe("C1^C2");
  });

  test("IN1-42 Insured Employment Status", () => {
    const parts = new IN1().insuredEmploymentStatus({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[42]).toBe("C1^C2^C3");
  });

  test("IN1-43 Insured Administrative Sex", () => {
    assertField(new IN1().insuredAdministrativeSex(SENTINEL), 43);
  });

  test("IN1-44 Insured Employer Address", () => {
    const parts = new IN1().insuredEmployerAddress({ street: "C1", otherDesignation: "C2", city: "C3", state: "C4", zip: "C5", country: "C6" }).encode().split("|");
    expect(parts[44]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("IN1-45 Verification Status", () => {
    assertField(new IN1().verificationStatus(SENTINEL), 45);
  });

  test("IN1-46 Prior Insurance Plan ID", () => {
    assertField(new IN1().priorInsurancePlanId(SENTINEL), 46);
  });

  test("IN1-49 Insured ID Number", () => {
    const parts = new IN1().insuredIdNumber({ id: "C1", assigningAuthority: "C2", identifierTypeCode: "C3" }).encode().split("|");
    expect(parts[49]).toBe("C1^^^C2^C3");
  });
});
