// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the IN2 segment (HL7 v2.3). `encode()`
// emits `IN2|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { IN2 } from "./IN2.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: IN2, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("IN2 field positions", () => {
  test("IN2-1 Insured Employee ID", () => {
    assertField(new IN2().insuredEmployeeId(SENTINEL), 1);
  });

  test("IN2-2 Insured SSN", () => {
    assertField(new IN2().insuredSsn(SENTINEL), 2);
  });

  test("IN2-3 Insured Employer Name", () => {
    assertField(new IN2().insuredEmployerName(SENTINEL), 3);
  });

  test("IN2-4 Employer Info Data", () => {
    assertField(new IN2().employerInfoData(SENTINEL), 4);
  });

  test("IN2-6 Medicare HIC Number", () => {
    assertField(new IN2().medicareHicNumber(SENTINEL), 6);
  });

  test("IN2-7 Medicaid Case Name", () => {
    assertField(new IN2().medicaidCaseName(SENTINEL), 7);
  });

  test("IN2-8 Medicaid Case Number", () => {
    assertField(new IN2().medicaidCaseNumber(SENTINEL), 8);
  });

  test("IN2-55 Relationship Start Date", () => {
    assertField(new IN2().relationshipStartDate(SENTINEL), 55);
  });

  test("IN2-56 Relationship Stop Date", () => {
    assertField(new IN2().relationshipStopDate(SENTINEL), 56);
  });

  test("IN2-72 Relationship To Patient", () => {
    assertField(new IN2().relationshipToPatient(SENTINEL), 72);
  });
});
