// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the IN2 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { IN2 } from "./IN2.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: IN2, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("IN2 field positions", () => {
  test("IN2-1 Insured Employee ID", () => {
    assertField(new IN2().insuredEmployeeId(SENTINEL), 1);
  });

  test("IN2-2 Insured SSN", () => {
    assertField(new IN2().insuredSsn(SENTINEL), 2);
  });

  test("IN2-3 Insured Employer Name", () => {
    const parts = new IN2().insuredEmployerName("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("IN2-4 Employer Info Data", () => {
    assertField(new IN2().employerInfoData(SENTINEL), 4);
  });

  test("IN2-5 Mail Claim Party", () => {
    assertField(new IN2().mailClaimParty(SENTINEL), 5);
  });

  test("IN2-6 Medicare HIC Number", () => {
    assertField(new IN2().medicareHicNumber(SENTINEL), 6);
  });

  test("IN2-7 Medicaid Case Name", () => {
    const parts = new IN2().medicaidCaseName("C1", "C2").encode().split("|");
    expect(parts[7]).toBe("C1^C2");
  });

  test("IN2-8 Medicaid Case Number", () => {
    assertField(new IN2().medicaidCaseNumber(SENTINEL), 8);
  });

  test("IN2-9 Military Sponsor Name", () => {
    const parts = new IN2().militarySponsorName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[9]).toBe("C1^C2^C3^C4^C5");
  });

  test("IN2-10 Military ID Number", () => {
    assertField(new IN2().militaryIdNumber(SENTINEL), 10);
  });

  test("IN2-11 Dependent Of Military Recipient", () => {
    const parts = new IN2().dependentOfMilitaryRecipient("C1", "C2", "C3").encode().split("|");
    expect(parts[11]).toBe("C1^C2^C3");
  });

  test("IN2-12 Military Organization", () => {
    assertField(new IN2().militaryOrganization(SENTINEL), 12);
  });

  test("IN2-13 Military Station", () => {
    assertField(new IN2().militaryStation(SENTINEL), 13);
  });

  test("IN2-14 Military Service", () => {
    assertField(new IN2().militaryService(SENTINEL), 14);
  });

  test("IN2-15 Military Rank Grade", () => {
    assertField(new IN2().militaryRankGrade(SENTINEL), 15);
  });

  test("IN2-16 Military Status", () => {
    assertField(new IN2().militaryStatus(SENTINEL), 16);
  });

  test("IN2-17 Military Retire Date", () => {
    assertField(new IN2().militaryRetireDate(SENTINEL), 17);
  });

  test("IN2-18 Military Non Avail Cert On File", () => {
    assertField(new IN2().militaryNonAvailCertOnFile(SENTINEL), 18);
  });

  test("IN2-19 Baby Coverage", () => {
    assertField(new IN2().babyCoverage(SENTINEL), 19);
  });

  test("IN2-20 Combine Baby Bill", () => {
    assertField(new IN2().combineBabyBill(SENTINEL), 20);
  });

  test("IN2-21 Blood Deductible", () => {
    assertField(new IN2().bloodDeductible(SENTINEL), 21);
  });

  test("IN2-22 Special Coverage Approval Name", () => {
    const parts = new IN2().specialCoverageApprovalName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[22]).toBe("C1^C2^C3^C4^C5");
  });

  test("IN2-23 Special Coverage Approval Title", () => {
    assertField(new IN2().specialCoverageApprovalTitle(SENTINEL), 23);
  });

  test("IN2-24 Non Covered Insurance Code", () => {
    assertField(new IN2().nonCoveredInsuranceCode(SENTINEL), 24);
  });

  test("IN2-25 Payor ID", () => {
    const parts = new IN2().payorId("C1", "C2", "C3").encode().split("|");
    expect(parts[25]).toBe("C1^^^C2^C3");
  });

  test("IN2-26 Payor Subscriber ID", () => {
    const parts = new IN2().payorSubscriberId("C1", "C2", "C3").encode().split("|");
    expect(parts[26]).toBe("C1^^^C2^C3");
  });

  test("IN2-27 Eligibility Source", () => {
    assertField(new IN2().eligibilitySource(SENTINEL), 27);
  });

  test("IN2-28 Room Coverage Type Amount", () => {
    const parts = new IN2().roomCoverageTypeAmount("C1", "C2", "C3").encode().split("|");
    expect(parts[28]).toBe("C1^C2^C3");
  });

  test("IN2-29 Policy Type Amount", () => {
    const parts = new IN2().policyTypeAmount("C1", "C2", "C3").encode().split("|");
    expect(parts[29]).toBe("C1^C2^C3");
  });

  test("IN2-30 Daily Deductible", () => {
    const parts = new IN2().dailyDeductible("C1", "C2", "C3").encode().split("|");
    expect(parts[30]).toBe("C1^C2^C3");
  });

  test("IN2-31 Living Dependency", () => {
    assertField(new IN2().livingDependency(SENTINEL), 31);
  });

  test("IN2-32 Ambulatory Status", () => {
    assertField(new IN2().ambulatoryStatus(SENTINEL), 32);
  });

  test("IN2-33 Citizenship", () => {
    const parts = new IN2().citizenship("C1", "C2", "C3").encode().split("|");
    expect(parts[33]).toBe("C1^C2^C3");
  });

  test("IN2-34 Primary Language", () => {
    const parts = new IN2().primaryLanguage("C1", "C2", "C3").encode().split("|");
    expect(parts[34]).toBe("C1^C2^C3");
  });

  test("IN2-35 Living Arrangement", () => {
    assertField(new IN2().livingArrangement(SENTINEL), 35);
  });

  test("IN2-36 Publicity Code", () => {
    const parts = new IN2().publicityCode("C1", "C2", "C3").encode().split("|");
    expect(parts[36]).toBe("C1^C2^C3");
  });

  test("IN2-37 Protection Indicator", () => {
    assertField(new IN2().protectionIndicator(SENTINEL), 37);
  });

  test("IN2-38 Student Indicator", () => {
    assertField(new IN2().studentIndicator(SENTINEL), 38);
  });

  test("IN2-39 Religion", () => {
    const parts = new IN2().religion("C1", "C2", "C3").encode().split("|");
    expect(parts[39]).toBe("C1^C2^C3");
  });

  test("IN2-40 Mothers Maiden Name", () => {
    const parts = new IN2().mothersMaidenName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[40]).toBe("C1^C2^C3^C4^C5");
  });

  test("IN2-41 Nationality", () => {
    const parts = new IN2().nationality("C1", "C2", "C3").encode().split("|");
    expect(parts[41]).toBe("C1^C2^C3");
  });

  test("IN2-42 Ethnic Group", () => {
    const parts = new IN2().ethnicGroup("C1", "C2", "C3").encode().split("|");
    expect(parts[42]).toBe("C1^C2^C3");
  });

  test("IN2-43 Marital Status", () => {
    const parts = new IN2().maritalStatus("C1", "C2", "C3").encode().split("|");
    expect(parts[43]).toBe("C1^C2^C3");
  });

  test("IN2-44 Insureds Employment Start Date", () => {
    assertField(new IN2().insuredsEmploymentStartDate(SENTINEL), 44);
  });

  test("IN2-45 Employment Stop Date", () => {
    assertField(new IN2().employmentStopDate(SENTINEL), 45);
  });

  test("IN2-46 Job Title", () => {
    assertField(new IN2().jobTitle(SENTINEL), 46);
  });

  test("IN2-47 Job Code Class", () => {
    const parts = new IN2().jobCodeClass("C1", "C2").encode().split("|");
    expect(parts[47]).toBe("C1^C2");
  });

  test("IN2-48 Job Status", () => {
    assertField(new IN2().jobStatus(SENTINEL), 48);
  });

  test("IN2-49 Employer Contact Person Name", () => {
    const parts = new IN2().employerContactPersonName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[49]).toBe("C1^C2^C3^C4^C5");
  });

  test("IN2-50 Employer Contact Person Phone Number", () => {
    assertField(new IN2().employerContactPersonPhoneNumber(SENTINEL), 50);
  });

  test("IN2-51 Employer Contact Reason", () => {
    assertField(new IN2().employerContactReason(SENTINEL), 51);
  });

  test("IN2-52 Insureds Contact Person Name", () => {
    const parts = new IN2().insuredsContactPersonName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[52]).toBe("C1^C2^C3^C4^C5");
  });

  test("IN2-53 Insureds Contact Person Phone Number", () => {
    assertField(new IN2().insuredsContactPersonPhoneNumber(SENTINEL), 53);
  });

  test("IN2-54 Insureds Contact Person Reason", () => {
    assertField(new IN2().insuredsContactPersonReason(SENTINEL), 54);
  });

  test("IN2-55 Relationship Start Date", () => {
    assertField(new IN2().relationshipStartDate(SENTINEL), 55);
  });

  test("IN2-56 Relationship Stop Date", () => {
    assertField(new IN2().relationshipStopDate(SENTINEL), 56);
  });

  test("IN2-57 Insurance Co Contact Reason", () => {
    assertField(new IN2().insuranceCoContactReason(SENTINEL), 57);
  });

  test("IN2-58 Insurance Co Contact Phone Number", () => {
    assertField(new IN2().insuranceCoContactPhoneNumber(SENTINEL), 58);
  });

  test("IN2-59 Policy Scope", () => {
    assertField(new IN2().policyScope(SENTINEL), 59);
  });

  test("IN2-60 Policy Source", () => {
    assertField(new IN2().policySource(SENTINEL), 60);
  });

  test("IN2-61 Patient Member Number", () => {
    const parts = new IN2().patientMemberNumber("C1", "C2", "C3").encode().split("|");
    expect(parts[61]).toBe("C1^^^C2^C3");
  });

  test("IN2-62 Guarantors Relationship To Insured", () => {
    const parts = new IN2().guarantorsRelationshipToInsured("C1", "C2", "C3").encode().split("|");
    expect(parts[62]).toBe("C1^C2^C3");
  });

  test("IN2-63 Insureds Phone Number Home", () => {
    assertField(new IN2().insuredsPhoneNumberHome(SENTINEL), 63);
  });

  test("IN2-64 Insureds Employer Phone Number", () => {
    assertField(new IN2().insuredsEmployerPhoneNumber(SENTINEL), 64);
  });

  test("IN2-65 Military Handicapped Program", () => {
    const parts = new IN2().militaryHandicappedProgram("C1", "C2", "C3").encode().split("|");
    expect(parts[65]).toBe("C1^C2^C3");
  });

  test("IN2-66 Suspend Flag", () => {
    assertField(new IN2().suspendFlag(SENTINEL), 66);
  });

  test("IN2-67 Copay Limit Flag", () => {
    assertField(new IN2().copayLimitFlag(SENTINEL), 67);
  });

  test("IN2-68 Stoploss Limit Flag", () => {
    assertField(new IN2().stoplossLimitFlag(SENTINEL), 68);
  });

  test("IN2-69 Insured Organization Name And ID", () => {
    const parts = new IN2().insuredOrganizationNameAndId("C1", "C2", "C3").encode().split("|");
    expect(parts[69]).toBe("C1^C2^C3");
  });

  test("IN2-70 Insured Employer Organization Name And ID", () => {
    const parts = new IN2().insuredEmployerOrganizationNameAndId("C1", "C2", "C3").encode().split("|");
    expect(parts[70]).toBe("C1^C2^C3");
  });

  test("IN2-71 Race", () => {
    const parts = new IN2().race("C1", "C2", "C3").encode().split("|");
    expect(parts[71]).toBe("C1^C2^C3");
  });

  test("IN2-72 Relationship To Patient", () => {
    const parts = new IN2().relationshipToPatient("C1", "C2").encode().split("|");
    expect(parts[72]).toBe("C1^C2");
  });
});
