// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the IN3 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { IN3 } from "./IN3.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: IN3, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("IN3 field positions", () => {
  test("IN3-1 Set ID", () => {
    assertField(new IN3().setId(SENTINEL), 1);
  });

  test("IN3-2 Certification Number", () => {
    assertField(new IN3().certificationNumber(SENTINEL), 2);
  });

  test("IN3-3 Certified By", () => {
    const parts = new IN3().certifiedBy("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("IN3-4 Certification Required", () => {
    assertField(new IN3().certificationRequired(SENTINEL), 4);
  });

  test("IN3-5 Penalty", () => {
    assertField(new IN3().penalty(SENTINEL), 5);
  });

  test("IN3-6 Certification Date Time", () => {
    assertField(new IN3().certificationDateTime(SENTINEL), 6);
  });

  test("IN3-7 Certification Modify Date Time", () => {
    assertField(new IN3().certificationModifyDateTime(SENTINEL), 7);
  });

  test("IN3-8 Operator", () => {
    const parts = new IN3().operator("C1", "C2", "C3").encode().split("|");
    expect(parts[8]).toBe("C1^C2^C3");
  });

  test("IN3-9 Certification Begin Date", () => {
    assertField(new IN3().certificationBeginDate(SENTINEL), 9);
  });

  test("IN3-10 Certification End Date", () => {
    assertField(new IN3().certificationEndDate(SENTINEL), 10);
  });

  test("IN3-11 Days", () => {
    assertField(new IN3().days(SENTINEL), 11);
  });

  test("IN3-12 Non Concur Code Description", () => {
    const parts = new IN3().nonConcurCodeDescription("C1", "C2").encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });

  test("IN3-13 Non Concur Effective Date Time", () => {
    assertField(new IN3().nonConcurEffectiveDateTime(SENTINEL), 13);
  });

  test("IN3-14 Physician Reviewer", () => {
    const parts = new IN3().physicianReviewer("C1", "C2", "C3").encode().split("|");
    expect(parts[14]).toBe("C1^C2^C3");
  });

  test("IN3-15 Certification Contact", () => {
    assertField(new IN3().certificationContact(SENTINEL), 15);
  });

  test("IN3-16 Certification Contact Phone", () => {
    assertField(new IN3().certificationContactPhone(SENTINEL), 16);
  });

  test("IN3-17 Appeal Reason", () => {
    const parts = new IN3().appealReason("C1", "C2").encode().split("|");
    expect(parts[17]).toBe("C1^C2");
  });

  test("IN3-18 Certification Agency", () => {
    const parts = new IN3().certificationAgency("C1", "C2").encode().split("|");
    expect(parts[18]).toBe("C1^C2");
  });

  test("IN3-19 Certification Agency Phone", () => {
    assertField(new IN3().certificationAgencyPhone(SENTINEL), 19);
  });

  test("IN3-20 Pre Certification Required", () => {
    assertField(new IN3().preCertificationRequired(SENTINEL), 20);
  });

  test("IN3-21 Case Manager", () => {
    assertField(new IN3().caseManager(SENTINEL), 21);
  });

  test("IN3-22 Second Opinion Date", () => {
    assertField(new IN3().secondOpinionDate(SENTINEL), 22);
  });

  test("IN3-23 Second Opinion Status", () => {
    assertField(new IN3().secondOpinionStatus(SENTINEL), 23);
  });

  test("IN3-24 Second Opinion Documentation Received", () => {
    assertField(new IN3().secondOpinionDocumentationReceived(SENTINEL), 24);
  });

  test("IN3-25 Second Opinion Physician", () => {
    const parts = new IN3().secondOpinionPhysician("C1", "C2", "C3").encode().split("|");
    expect(parts[25]).toBe("C1^C2^C3");
  });
});
