// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the MFI segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { MFI } from "./MFI.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: MFI, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("MFI field positions", () => {
  test("MFI-1 Master File Identifier", () => {
    const parts = new MFI().masterFileIdentifier({ identifier: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3");
  });

  test("MFI-2 Master File Application Identifier", () => {
    assertField(new MFI().masterFileApplicationIdentifier(SENTINEL), 2);
  });

  test("MFI-3 File Level Event Code", () => {
    assertField(new MFI().fileLevelEventCode(SENTINEL), 3);
  });

  test("MFI-4 Entered Date Time", () => {
    assertField(new MFI().enteredDateTime(SENTINEL), 4);
  });

  test("MFI-5 Effective Date Time", () => {
    assertField(new MFI().effectiveDateTime(SENTINEL), 5);
  });

  test("MFI-6 Response Level Code", () => {
    assertField(new MFI().responseLevelCode(SENTINEL), 6);
  });
});
