// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the MRG segment (HL7 v2.3). `encode()`
// emits `MRG|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { MRG } from "./MRG.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: MRG, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("MRG field positions", () => {
  test("MRG-1 Prior Patient ID", () => {
    assertField(new MRG().priorPatientId(SENTINEL), 1);
  });

  test("MRG-2 Prior Alternate Patient ID", () => {
    assertField(new MRG().priorAlternatePatientId(SENTINEL), 2);
  });

  test("MRG-3 Prior Patient Account Number", () => {
    assertField(new MRG().priorPatientAccountNumber(SENTINEL), 3);
  });

  test("MRG-4 Prior Patient ID Deprecated", () => {
    assertField(new MRG().priorPatientIdDeprecated(SENTINEL), 4);
  });

  test("MRG-5 Prior Visit Number", () => {
    assertField(new MRG().priorVisitNumber(SENTINEL), 5);
  });

  test("MRG-6 Prior Alternate Visit ID", () => {
    assertField(new MRG().priorAlternateVisitId(SENTINEL), 6);
  });

  test("MRG-7 Prior Patient Name", () => {
    assertField(new MRG().priorPatientName(SENTINEL), 7);
  });
});
