// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the MSA segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { MSA } from "./MSA.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: MSA, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("MSA field positions", () => {
  test("MSA-1 Acknowledgment Code", () => {
    assertField(new MSA().acknowledgmentCode(SENTINEL), 1);
  });

  test("MSA-2 Message Control ID", () => {
    assertField(new MSA().messageControlId(SENTINEL), 2);
  });

  test("MSA-3 Text Message", () => {
    assertField(new MSA().textMessage(SENTINEL), 3);
  });

  test("MSA-4 Expected Sequence Number", () => {
    assertField(new MSA().expectedSequenceNumber(SENTINEL), 4);
  });

  test("MSA-5 Delayed Acknowledgment Type", () => {
    assertField(new MSA().delayedAcknowledgmentType(SENTINEL), 5);
  });

  test("MSA-6 Error Condition", () => {
    const parts = new MSA().errorCondition("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });
});
