// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the MSA segment (HL7 v2.3). `encode()`
// emits `MSA|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { MSA } from "./MSA.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: MSA, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("MSA field positions", () => {
  test("MSA-1 Acknowledgment Code", () => {
    assertField(new MSA().acknowledgmentCode(SENTINEL), 1);
  });

  test("MSA-2 Message Control ID", () => {
    assertField(new MSA().messageControlId(SENTINEL), 2);
  });

  test("MSA-3 Text Message", () => {
    assertField(new MSA().textMessage(SENTINEL), 3);
  });

  test("MSA-4 Expected Sequence Number", () => {
    assertField(new MSA().expectedSequenceNumber(SENTINEL), 4);
  });

  test("MSA-5 Delayed Acknowledgment Type", () => {
    assertField(new MSA().delayedAcknowledgmentType(SENTINEL), 5);
  });

  test("MSA-6 Error Condition", () => {
    assertField(new MSA().errorCondition(SENTINEL), 6);
  });
});
