// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the MSH segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.//
// NOTE: MSH-1 (field separator) and MSH-2 (encoding characters) occupy the
// start of the encoded segment, so an MSH-N value sits at split index N-1.
// The index used below is the split index, not the HL7 field number.
import { test, expect, describe } from "vitest";
import { MSH } from "./MSH.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: MSH, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("MSH field positions", () => {
  test("MSH-3 Sending Application", () => {
    assertField(new MSH().sendingApplication(SENTINEL), 2);
  });

  test("MSH-4 Sending Facility", () => {
    assertField(new MSH().sendingFacility(SENTINEL), 3);
  });

  test("MSH-5 Receiving Application", () => {
    assertField(new MSH().receivingApplication(SENTINEL), 4);
  });

  test("MSH-6 Receiving Facility", () => {
    assertField(new MSH().receivingFacility(SENTINEL), 5);
  });

  test("MSH-7 Date Time Of Message", () => {
    assertField(new MSH().dateTimeOfMessage(SENTINEL), 6);
  });

  test("MSH-8 Security", () => {
    assertField(new MSH().security(SENTINEL), 7);
  });

  test("MSH-9 Message Type", () => {
    assertField(new MSH().messageType({ messageCode: SENTINEL, triggerEvent: "", messageStructure: "" }), 8);
  });

  test("MSH-10 Message Control ID", () => {
    assertField(new MSH().messageControlId(SENTINEL), 9);
  });

  test("MSH-11 Processing ID", () => {
    assertField(new MSH().processingId(SENTINEL), 10);
  });

  test("MSH-12 Version ID", () => {
    assertField(new MSH().versionId(SENTINEL), 11);
  });

  test("MSH-13 Sequence Number", () => {
    assertField(new MSH().sequenceNumber(SENTINEL), 12);
  });

  test("MSH-14 Continuation Pointer", () => {
    assertField(new MSH().continuationPointer(SENTINEL), 13);
  });

  test("MSH-15 Accept Acknowledgment Type", () => {
    assertField(new MSH().acceptAcknowledgmentType(SENTINEL), 14);
  });

  test("MSH-16 Application Acknowledgment Type", () => {
    assertField(new MSH().applicationAcknowledgmentType(SENTINEL), 15);
  });

  test("MSH-17 Country Code", () => {
    assertField(new MSH().countryCode(SENTINEL), 16);
  });

  test("MSH-18 Character Set", () => {
    assertField(new MSH().characterSet(SENTINEL), 17);
  });

  test("MSH-19 Principal Language Of Message", () => {
    const parts = new MSH().principalLanguageOfMessage({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[18]).toBe("C1^C2^C3");
  });
});
