// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the NK1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { NK1 } from "./NK1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: NK1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("NK1 field positions", () => {
  test("NK1-1 Set ID", () => {
    assertField(new NK1().setId(SENTINEL), 1);
  });

  test("NK1-2 Set Name", () => {
    const parts = new NK1().setName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3^C4^C5");
  });

  test("NK1-3 Relationship", () => {
    const parts = new NK1().relationship("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("NK1-4 Address", () => {
    const parts = new NK1().address("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[4]).toBe("C1^^C2^C3^C4^C5");
  });

  test("NK1-5 Phone Number", () => {
    const parts = new NK1().phoneNumber("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("NK1-6 Business Phone Number", () => {
    assertField(new NK1().businessPhoneNumber(SENTINEL), 6);
  });

  test("NK1-7 Contact Role", () => {
    const parts = new NK1().contactRole("C1", "C2", "C3").encode().split("|");
    expect(parts[7]).toBe("C1^C2^C3");
  });

  test("NK1-8 Start Date", () => {
    assertField(new NK1().startDate(SENTINEL), 8);
  });

  test("NK1-9 End Date", () => {
    assertField(new NK1().endDate(SENTINEL), 9);
  });

  test("NK1-10 Job Title", () => {
    assertField(new NK1().jobTitle(SENTINEL), 10);
  });

  test("NK1-11 Job Code Class", () => {
    const parts = new NK1().jobCodeClass("C1", "C2", "C3").encode().split("|");
    expect(parts[11]).toBe("C1^C2^C3");
  });

  test("NK1-12 Employee Number", () => {
    const parts = new NK1().employeeNumber("C1", "C2", "C3").encode().split("|");
    expect(parts[12]).toBe("C1^^^C2^C3");
  });

  test("NK1-13 Organization Name", () => {
    assertField(new NK1().organizationName(SENTINEL), 13);
  });

  test("NK1-14 Marital Status", () => {
    const parts = new NK1().maritalStatus("C1", "C2", "C3").encode().split("|");
    expect(parts[14]).toBe("C1^C2^C3");
  });

  test("NK1-15 Administrative Sex", () => {
    assertField(new NK1().administrativeSex(SENTINEL), 15);
  });

  test("NK1-16 Date Time Of Birth", () => {
    assertField(new NK1().dateTimeOfBirth(SENTINEL), 16);
  });

  test("NK1-17 Living Dependency", () => {
    assertField(new NK1().livingDependency(SENTINEL), 17);
  });

  test("NK1-18 Ambulatory Status", () => {
    assertField(new NK1().ambulatoryStatus(SENTINEL), 18);
  });

  test("NK1-19 Citizenship", () => {
    const parts = new NK1().citizenship("C1", "C2", "C3").encode().split("|");
    expect(parts[19]).toBe("C1^C2^C3");
  });

  test("NK1-20 Primary Language", () => {
    const parts = new NK1().primaryLanguage("C1", "C2", "C3").encode().split("|");
    expect(parts[20]).toBe("C1^C2^C3");
  });

  test("NK1-21 Living Arrangement", () => {
    assertField(new NK1().livingArrangement(SENTINEL), 21);
  });

  test("NK1-22 Publicity Code", () => {
    const parts = new NK1().publicityCode("C1", "C2", "C3").encode().split("|");
    expect(parts[22]).toBe("C1^C2^C3");
  });

  test("NK1-23 Protection Indicator", () => {
    assertField(new NK1().protectionIndicator(SENTINEL), 23);
  });

  test("NK1-24 Student Indicator", () => {
    assertField(new NK1().studentIndicator(SENTINEL), 24);
  });

  test("NK1-25 Religion", () => {
    const parts = new NK1().religion("C1", "C2", "C3").encode().split("|");
    expect(parts[25]).toBe("C1^C2^C3");
  });

  test("NK1-26 Mothers Maiden Name", () => {
    const parts = new NK1().mothersMaidenName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[26]).toBe("C1^C2^C3^C4^C5");
  });

  test("NK1-27 Nationality", () => {
    const parts = new NK1().nationality("C1", "C2", "C3").encode().split("|");
    expect(parts[27]).toBe("C1^C2^C3");
  });

  test("NK1-28 Ethnic Group", () => {
    const parts = new NK1().ethnicGroup("C1", "C2", "C3").encode().split("|");
    expect(parts[28]).toBe("C1^C2^C3");
  });

  test("NK1-29 Contact Reason", () => {
    const parts = new NK1().contactReason("C1", "C2", "C3").encode().split("|");
    expect(parts[29]).toBe("C1^C2^C3");
  });

  test("NK1-30 Contact Person Name", () => {
    const parts = new NK1().contactPersonName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[30]).toBe("C1^C2^C3^C4^C5");
  });

  test("NK1-31 Contact Person Telephone Number", () => {
    assertField(new NK1().contactPersonTelephoneNumber(SENTINEL), 31);
  });

  test("NK1-32 Contact Person Address", () => {
    const parts = new NK1().contactPersonAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[32]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("NK1-33 Associated Partys Identifiers", () => {
    const parts = new NK1().associatedPartysIdentifiers("C1", "C2", "C3").encode().split("|");
    expect(parts[33]).toBe("C1^^^C2^C3");
  });

  test("NK1-34 Job Status", () => {
    assertField(new NK1().jobStatus(SENTINEL), 34);
  });

  test("NK1-35 Race", () => {
    const parts = new NK1().race("C1", "C2", "C3").encode().split("|");
    expect(parts[35]).toBe("C1^C2^C3");
  });

  test("NK1-36 Handicap", () => {
    assertField(new NK1().handicap(SENTINEL), 36);
  });

  test("NK1-37 Contact Person Social Security Number", () => {
    assertField(new NK1().contactPersonSocialSecurityNumber(SENTINEL), 37);
  });
});
