// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the NK1 segment (HL7 v2.3). `encode()`
// emits `NK1|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { NK1 } from "./NK1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: NK1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("NK1 field positions", () => {
  test("NK1-1 Set ID", () => {
    assertField(new NK1().setId(SENTINEL), 1);
  });

  test("NK1-2 Set Name", () => {
    assertField(new NK1().setName(SENTINEL), 2);
  });

  test("NK1-3 Relationship", () => {
    assertField(new NK1().relationship(SENTINEL), 3);
  });

  test("NK1-4 Address", () => {
    assertField(new NK1().address(SENTINEL), 4);
  });

  test("NK1-5 Phone Number", () => {
    assertField(new NK1().phoneNumber(SENTINEL), 5);
  });

  test("NK1-6 Business Phone Number", () => {
    assertField(new NK1().businessPhoneNumber(SENTINEL), 6);
  });

  test("NK1-7 Contact Role", () => {
    assertField(new NK1().contactRole(SENTINEL), 7);
  });

  test("NK1-8 Start Date", () => {
    assertField(new NK1().startDate(SENTINEL), 8);
  });

  test("NK1-9 End Date", () => {
    assertField(new NK1().endDate(SENTINEL), 9);
  });

  test("NK1-10 Job Title", () => {
    assertField(new NK1().jobTitle(SENTINEL), 10);
  });

  test("NK1-13 Organization Name", () => {
    assertField(new NK1().organizationName(SENTINEL), 13);
  });

  test("NK1-15 Administrative Sex", () => {
    assertField(new NK1().administrativeSex(SENTINEL), 15);
  });

  test("NK1-16 Date Time Of Birth", () => {
    assertField(new NK1().dateTimeOfBirth(SENTINEL), 16);
  });
});
