// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the NTE segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { NTE } from "./NTE.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: NTE, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("NTE field positions", () => {
  test("NTE-1 Set ID", () => {
    assertField(new NTE().setId(SENTINEL), 1);
  });

  test("NTE-2 Source Of Comment", () => {
    assertField(new NTE().sourceOfComment(SENTINEL), 2);
  });

  test("NTE-3 Comment", () => {
    assertField(new NTE().comment(SENTINEL), 3);
  });

  test("NTE-4 Comment Type", () => {
    const parts = new NTE().commentType("C1", "C2", "C3").encode().split("|");
    expect(parts[4]).toBe("C1^C2^C3");
  });
});
