// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the NTE segment (HL7 v2.3). `encode()`
// emits `NTE|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { NTE } from "./NTE.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: NTE, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("NTE field positions", () => {
  test("NTE-1 Set ID", () => {
    assertField(new NTE().setId(SENTINEL), 1);
  });

  test("NTE-2 Source Of Comment", () => {
    assertField(new NTE().sourceOfComment(SENTINEL), 2);
  });

  test("NTE-3 Comment", () => {
    assertField(new NTE().comment(SENTINEL), 3);
  });

  test("NTE-4 Comment Type", () => {
    assertField(new NTE().commentType(SENTINEL), 4);
  });
});
