// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the OBR segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { OBR } from "./OBR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: OBR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("OBR field positions", () => {
  test("OBR-1 Set ID", () => {
    assertField(new OBR().setId(SENTINEL), 1);
  });

  test("OBR-2 Placer Order Number", () => {
    assertField(new OBR().placerOrderNumber(SENTINEL), 2);
  });

  test("OBR-3 Filler Order Number", () => {
    assertField(new OBR().fillerOrderNumber(SENTINEL), 3);
  });

  test("OBR-4 Universal Service Identifier", () => {
    const parts = new OBR().universalServiceIdentifier({ identifier: "C1", text: "C2", nameOfCodingSystem: "C3" }).encode().split("|");
    expect(parts[4]).toBe("C1^C2^C3");
  });

  test("OBR-5 Priority", () => {
    assertField(new OBR().priority(SENTINEL), 5);
  });

  test("OBR-6 Requested Date Time", () => {
    assertField(new OBR().requestedDateTime(SENTINEL), 6);
  });

  test("OBR-7 Observation Date Time", () => {
    assertField(new OBR().observationDateTime(SENTINEL), 7);
  });

  test("OBR-8 Observation End Date Time", () => {
    assertField(new OBR().observationEndDateTime(SENTINEL), 8);
  });

  test("OBR-9 Collection Volume", () => {
    assertField(new OBR().collectionVolume(SENTINEL), 9);
  });

  test("OBR-10 Collector Identifier", () => {
    const parts = new OBR().collectorIdentifier({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[10]).toBe("C1^C2^C3");
  });

  test("OBR-11 Specimen Action Code", () => {
    assertField(new OBR().specimenActionCode(SENTINEL), 11);
  });

  test("OBR-12 Danger Code", () => {
    assertField(new OBR().dangerCode(SENTINEL), 12);
  });

  test("OBR-13 Relevant Clinical Info", () => {
    assertField(new OBR().relevantClinicalInfo(SENTINEL), 13);
  });

  test("OBR-14 Specimen Received Date Time", () => {
    assertField(new OBR().specimenReceivedDateTime(SENTINEL), 14);
  });

  test("OBR-15 Specimen Source", () => {
    assertField(new OBR().specimenSource(SENTINEL), 15);
  });

  test("OBR-16 Ordering Provider", () => {
    const parts = new OBR().orderingProvider({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[16]).toBe("C1^C2^C3");
  });

  test("OBR-17 Order Callback Phone Number", () => {
    assertField(new OBR().orderCallbackPhoneNumber(SENTINEL), 17);
  });

  test("OBR-18 Placer Field1", () => {
    assertField(new OBR().placerField1(SENTINEL), 18);
  });

  test("OBR-19 Placer Field2", () => {
    assertField(new OBR().placerField2(SENTINEL), 19);
  });

  test("OBR-20 Filler Field1", () => {
    assertField(new OBR().fillerField1(SENTINEL), 20);
  });

  test("OBR-21 Filler Field2", () => {
    assertField(new OBR().fillerField2(SENTINEL), 21);
  });

  test("OBR-22 Results Rpt Status Chng Date Time", () => {
    assertField(new OBR().resultsRptStatusChngDateTime(SENTINEL), 22);
  });

  test("OBR-23 Charge To Practice", () => {
    assertField(new OBR().chargeToPractice(SENTINEL), 23);
  });

  test("OBR-24 Diagnostic Serv Sect ID", () => {
    assertField(new OBR().diagnosticServSectId(SENTINEL), 24);
  });

  test("OBR-25 Result Status", () => {
    assertField(new OBR().resultStatus(SENTINEL), 25);
  });

  test("OBR-26 Parent Result", () => {
    const parts = new OBR().parentResult({ parentObservationIdentifier: "C1", parentObservationSubIdentifier: "C2", parentObservationValueDescriptor: "C3" }).encode().split("|");
    expect(parts[26]).toBe("C1^C2^C3");
  });

  test("OBR-27 Quantity Timing", () => {
    const parts = new OBR().quantityTiming({ quantity: "C1", interval: "C2", duration: "C3", startDateTime: "C4", endDateTime: "C5", priority: "C6" }).encode().split("|");
    expect(parts[27]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("OBR-28 Result Copies To", () => {
    const parts = new OBR().resultCopiesTo({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[28]).toBe("C1^C2^C3");
  });

  test("OBR-29 Parent", () => {
    const parts = new OBR().parent({ placerAssignedIdentifier: "C1", fillerAssignedIdentifier: "C2" }).encode().split("|");
    expect(parts[29]).toBe("C1^C2");
  });

  test("OBR-30 Transportation Mode", () => {
    assertField(new OBR().transportationMode(SENTINEL), 30);
  });

  test("OBR-31 Reason For Study", () => {
    const parts = new OBR().reasonForStudy({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[31]).toBe("C1^C2^C3");
  });

  test("OBR-32 Principal Result Interpreter", () => {
    const parts = new OBR().principalResultInterpreter({ name: "C1", startDateTime: "C2", endDateTime: "C3" }).encode().split("|");
    expect(parts[32]).toBe("C1^C2^C3");
  });

  test("OBR-33 Assistant Result Interpreter", () => {
    const parts = new OBR().assistantResultInterpreter({ name: "C1", startDateTime: "C2", endDateTime: "C3" }).encode().split("|");
    expect(parts[33]).toBe("C1^C2^C3");
  });

  test("OBR-34 Technician", () => {
    const parts = new OBR().technician({ name: "C1", startDateTime: "C2", endDateTime: "C3" }).encode().split("|");
    expect(parts[34]).toBe("C1^C2^C3");
  });

  test("OBR-35 Transcriptionist", () => {
    const parts = new OBR().transcriptionist({ name: "C1", startDateTime: "C2", endDateTime: "C3" }).encode().split("|");
    expect(parts[35]).toBe("C1^C2^C3");
  });

  test("OBR-36 Scheduled Date Time", () => {
    assertField(new OBR().scheduledDateTime(SENTINEL), 36);
  });

  test("OBR-37 Number Of Sample Containers", () => {
    assertField(new OBR().numberOfSampleContainers(SENTINEL), 37);
  });

  test("OBR-38 Transport Logistics Of Collected Sample", () => {
    const parts = new OBR().transportLogisticsOfCollectedSample({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[38]).toBe("C1^C2^C3");
  });

  test("OBR-39 Collectors Comment", () => {
    const parts = new OBR().collectorsComment({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[39]).toBe("C1^C2^C3");
  });

  test("OBR-40 Transport Arrangement Responsibility", () => {
    const parts = new OBR().transportArrangementResponsibility({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[40]).toBe("C1^C2^C3");
  });

  test("OBR-41 Transport Arranged", () => {
    assertField(new OBR().transportArranged(SENTINEL), 41);
  });

  test("OBR-42 Escort Required", () => {
    assertField(new OBR().escortRequired(SENTINEL), 42);
  });

  test("OBR-43 Planned Patient Transport Comment", () => {
    const parts = new OBR().plannedPatientTransportComment({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[43]).toBe("C1^C2^C3");
  });
});
