// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the OBR segment (HL7 v2.3). `encode()`
// emits `OBR|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { OBR } from "./OBR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: OBR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("OBR field positions", () => {
  test("OBR-1 Set ID", () => {
    assertField(new OBR().setId(SENTINEL), 1);
  });

  test("OBR-2 Placer Order Number", () => {
    assertField(new OBR().placerOrderNumber(SENTINEL), 2);
  });

  test("OBR-3 Filler Order Number", () => {
    assertField(new OBR().fillerOrderNumber(SENTINEL), 3);
  });

  test("OBR-4 Universal Service Identifier", () => {
    assertField(new OBR().universalServiceIdentifier(SENTINEL), 4);
  });

  test("OBR-5 Priority", () => {
    assertField(new OBR().priority(SENTINEL), 5);
  });

  test("OBR-6 Requested Date Time", () => {
    assertField(new OBR().requestedDateTime(SENTINEL), 6);
  });

  test("OBR-7 Observation Date Time", () => {
    assertField(new OBR().observationDateTime(SENTINEL), 7);
  });

  test("OBR-8 Observation End Date Time", () => {
    assertField(new OBR().observationEndDateTime(SENTINEL), 8);
  });

  test("OBR-9 Collection Volume", () => {
    assertField(new OBR().collectionVolume(SENTINEL), 9);
  });

  test("OBR-10 Collector Identifier", () => {
    assertField(new OBR().collectorIdentifier(SENTINEL), 10);
  });

  test("OBR-11 Specimen Action Code", () => {
    assertField(new OBR().specimenActionCode(SENTINEL), 11);
  });

  test("OBR-12 Danger Code", () => {
    assertField(new OBR().dangerCode(SENTINEL), 12);
  });

  test("OBR-13 Relevant Clinical Info", () => {
    assertField(new OBR().relevantClinicalInfo(SENTINEL), 13);
  });

  test("OBR-14 Specimen Received Date Time", () => {
    assertField(new OBR().specimenReceivedDateTime(SENTINEL), 14);
  });

  test("OBR-15 Specimen Source", () => {
    assertField(new OBR().specimenSource(SENTINEL), 15);
  });

  test("OBR-16 Ordering Provider", () => {
    assertField(new OBR().orderingProvider(SENTINEL), 16);
  });

  test("OBR-17 Order Callback Phone Number", () => {
    assertField(new OBR().orderCallbackPhoneNumber(SENTINEL), 17);
  });

  test("OBR-18 Placer Field1", () => {
    assertField(new OBR().placerField1(SENTINEL), 18);
  });

  test("OBR-19 Placer Field2", () => {
    assertField(new OBR().placerField2(SENTINEL), 19);
  });

  test("OBR-20 Filler Field1", () => {
    assertField(new OBR().fillerField1(SENTINEL), 20);
  });

  test("OBR-21 Filler Field2", () => {
    assertField(new OBR().fillerField2(SENTINEL), 21);
  });

  test("OBR-22 Results Rpt Status Chng Date Time", () => {
    assertField(new OBR().resultsRptStatusChngDateTime(SENTINEL), 22);
  });

  test("OBR-23 Charge To Practice", () => {
    assertField(new OBR().chargeToPractice(SENTINEL), 23);
  });

  test("OBR-24 Diagnostic Serv Sect ID", () => {
    assertField(new OBR().diagnosticServSectId(SENTINEL), 24);
  });

  test("OBR-25 Result Status", () => {
    assertField(new OBR().resultStatus(SENTINEL), 25);
  });
});
