// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the OBX segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { OBX } from "./OBX.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: OBX, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("OBX field positions", () => {
  test("OBX-1 Set ID", () => {
    assertField(new OBX().setId(SENTINEL), 1);
  });

  test("OBX-2 Value Type", () => {
    assertField(new OBX().valueType(SENTINEL), 2);
  });

  test("OBX-3 Observation Identifier", () => {
    const parts = new OBX().observationIdentifier("C1", "C2", "C3").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("OBX-4 Observation Sub ID", () => {
    assertField(new OBX().observationSubId(SENTINEL), 4);
  });

  test("OBX-5 Observation Value", () => {
    assertField(new OBX().observationValue(SENTINEL), 5);
  });

  test("OBX-6 Units", () => {
    const parts = new OBX().units("C1", "C2", "C3").encode().split("|");
    expect(parts[6]).toBe("C1^C2^C3");
  });

  test("OBX-7 Reference Range", () => {
    assertField(new OBX().referenceRange(SENTINEL), 7);
  });

  test("OBX-8 Abnormal Flags", () => {
    assertField(new OBX().abnormalFlags(SENTINEL), 8);
  });

  test("OBX-9 Probability", () => {
    assertField(new OBX().probability(SENTINEL), 9);
  });

  test("OBX-10 Nature Of Abnormal Test", () => {
    assertField(new OBX().natureOfAbnormalTest(SENTINEL), 10);
  });

  test("OBX-11 Observation Result Status", () => {
    assertField(new OBX().observationResultStatus(SENTINEL), 11);
  });

  test("OBX-12 Effective Date Of Reference Range", () => {
    assertField(new OBX().effectiveDateOfReferenceRange(SENTINEL), 12);
  });

  test("OBX-13 User Defined Access Checks", () => {
    assertField(new OBX().userDefinedAccessChecks(SENTINEL), 13);
  });

  test("OBX-14 Date Time Of Observation", () => {
    assertField(new OBX().dateTimeOfObservation(SENTINEL), 14);
  });

  test("OBX-15 Producers ID", () => {
    assertField(new OBX().producersId(SENTINEL), 15);
  });

  test("OBX-16 Responsible Observer", () => {
    const parts = new OBX().responsibleObserver("C1", "C2", "C3").encode().split("|");
    expect(parts[16]).toBe("C1^C2^C3");
  });

  test("OBX-17 Observation Method", () => {
    const parts = new OBX().observationMethod("C1", "C2", "C3").encode().split("|");
    expect(parts[17]).toBe("C1^C2^C3");
  });
});
