// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the ORC segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { ORC } from "./ORC.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: ORC, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ORC field positions", () => {
  test("ORC-1 Order Control", () => {
    assertField(new ORC().orderControl(SENTINEL), 1);
  });

  test("ORC-2 Placer Order Number", () => {
    assertField(new ORC().placerOrderNumber(SENTINEL), 2);
  });

  test("ORC-3 Filler Order Number", () => {
    assertField(new ORC().fillerOrderNumber(SENTINEL), 3);
  });

  test("ORC-4 Placer Group Number", () => {
    assertField(new ORC().placerGroupNumber(SENTINEL), 4);
  });

  test("ORC-5 Order Status", () => {
    assertField(new ORC().orderStatus(SENTINEL), 5);
  });

  test("ORC-6 Response Flag", () => {
    assertField(new ORC().responseFlag(SENTINEL), 6);
  });

  test("ORC-7 Quantity Timing", () => {
    assertField(new ORC().quantityTiming(SENTINEL), 7);
  });

  test("ORC-8 Parent", () => {
    assertField(new ORC().parent(SENTINEL), 8);
  });

  test("ORC-9 Date Time Of Transaction", () => {
    assertField(new ORC().dateTimeOfTransaction(SENTINEL), 9);
  });

  test("ORC-10 Entered By", () => {
    const parts = new ORC().enteredBy({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[10]).toBe("C1^C2^C3");
  });

  test("ORC-11 Verified By", () => {
    const parts = new ORC().verifiedBy({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[11]).toBe("C1^C2^C3");
  });

  test("ORC-12 Ordering Provider", () => {
    const parts = new ORC().orderingProvider({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[12]).toBe("C1^C2^C3");
  });

  test("ORC-13 Enterers Location", () => {
    const parts = new ORC().enterersLocation({ pointOfCare: "C1", room: "C2", bed: "C3", facility: "C4", locationStatus: "C5", personLocationType: "C6" }).encode().split("|");
    expect(parts[13]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("ORC-14 Call Back Phone Number", () => {
    assertField(new ORC().callBackPhoneNumber(SENTINEL), 14);
  });

  test("ORC-15 Order Effective Date Time", () => {
    assertField(new ORC().orderEffectiveDateTime(SENTINEL), 15);
  });

  test("ORC-16 Order Control Code Reason", () => {
    assertField(new ORC().orderControlCodeReason(SENTINEL), 16);
  });

  test("ORC-17 Entering Organization", () => {
    assertField(new ORC().enteringOrganization(SENTINEL), 17);
  });

  test("ORC-18 Entering Device", () => {
    assertField(new ORC().enteringDevice(SENTINEL), 18);
  });

  test("ORC-19 Action By", () => {
    const parts = new ORC().actionBy({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[19]).toBe("C1^C2^C3");
  });
});
