// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the ORC segment (HL7 v2.3). `encode()`
// emits `ORC|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { ORC } from "./ORC.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: ORC, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ORC field positions", () => {
  test("ORC-1 Order Control", () => {
    assertField(new ORC().orderControl(SENTINEL), 1);
  });

  test("ORC-2 Placer Order Number", () => {
    assertField(new ORC().placerOrderNumber(SENTINEL), 2);
  });

  test("ORC-3 Filler Order Number", () => {
    assertField(new ORC().fillerOrderNumber(SENTINEL), 3);
  });

  test("ORC-4 Placer Group Number", () => {
    assertField(new ORC().placerGroupNumber(SENTINEL), 4);
  });

  test("ORC-5 Order Status", () => {
    assertField(new ORC().orderStatus(SENTINEL), 5);
  });

  test("ORC-6 Response Flag", () => {
    assertField(new ORC().responseFlag(SENTINEL), 6);
  });

  test("ORC-7 Quantity Timing", () => {
    assertField(new ORC().quantityTiming(SENTINEL), 7);
  });

  test("ORC-8 Parent", () => {
    assertField(new ORC().parent(SENTINEL), 8);
  });

  test("ORC-9 Date Time Of Transaction", () => {
    assertField(new ORC().dateTimeOfTransaction(SENTINEL), 9);
  });

  test("ORC-10 Entered By", () => {
    assertField(new ORC().enteredBy(SENTINEL), 10);
  });

  test("ORC-11 Verified By", () => {
    assertField(new ORC().verifiedBy(SENTINEL), 11);
  });

  test("ORC-12 Ordering Provider", () => {
    assertField(new ORC().orderingProvider(SENTINEL), 12);
  });

  test("ORC-13 Enterers Location", () => {
    assertField(new ORC().enterersLocation(SENTINEL), 13);
  });

  test("ORC-14 Call Back Phone Number", () => {
    assertField(new ORC().callBackPhoneNumber(SENTINEL), 14);
  });

  test("ORC-15 Order Effective Date Time", () => {
    assertField(new ORC().orderEffectiveDateTime(SENTINEL), 15);
  });

  test("ORC-16 Order Control Code Reason", () => {
    assertField(new ORC().orderControlCodeReason(SENTINEL), 16);
  });

  test("ORC-17 Entering Organization", () => {
    assertField(new ORC().enteringOrganization(SENTINEL), 17);
  });

  test("ORC-18 Entering Device", () => {
    assertField(new ORC().enteringDevice(SENTINEL), 18);
  });

  test("ORC-19 Action By", () => {
    assertField(new ORC().actionBy(SENTINEL), 19);
  });
});
