// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the PD1 segment (HL7 v2.3). `encode()`
// emits `PD1|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { PD1 } from "./PD1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: PD1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PD1 field positions", () => {
  test("PD1-1 Living Dependency", () => {
    assertField(new PD1().livingDependency(SENTINEL), 1);
  });

  test("PD1-2 Living Arrangement", () => {
    assertField(new PD1().livingArrangement(SENTINEL), 2);
  });

  test("PD1-3 Patient Primary Facility", () => {
    assertField(new PD1().patientPrimaryFacility(SENTINEL), 3);
  });

  test("PD1-4 Patient Primary Care Provider", () => {
    assertField(new PD1().patientPrimaryCareProvider(SENTINEL, SENTINEL), 4);
  });

  test("PD1-5 Student Indicator", () => {
    assertField(new PD1().studentIndicator(SENTINEL), 5);
  });

  test("PD1-6 Handicap", () => {
    assertField(new PD1().handicap(SENTINEL), 6);
  });

  test("PD1-7 Living Will Code", () => {
    assertField(new PD1().livingWillCode(SENTINEL), 7);
  });

  test("PD1-8 Organ Donor Code", () => {
    assertField(new PD1().organDonorCode(SENTINEL), 8);
  });

  test("PD1-9 Separate Bill", () => {
    assertField(new PD1().separateBill(SENTINEL), 9);
  });

  test("PD1-10 Duplicate Patient", () => {
    assertField(new PD1().duplicatePatient(SENTINEL), 10);
  });

  test("PD1-11 Publicity Code", () => {
    assertField(new PD1().publicityCode(SENTINEL), 11);
  });

  test("PD1-12 Protection Indicator", () => {
    assertField(new PD1().protectionIndicator(SENTINEL), 12);
  });

  test("PD1-13 Protection Indicator Effective Date", () => {
    assertField(new PD1().protectionIndicatorEffectiveDate(SENTINEL), 13);
  });

  test("PD1-14 Place Of Worship", () => {
    assertField(new PD1().placeOfWorship(SENTINEL), 14);
  });

  test("PD1-15 Advance Directive Code", () => {
    assertField(new PD1().advanceDirectiveCode(SENTINEL), 15);
  });

  test("PD1-16 Immunization Registry Status", () => {
    assertField(new PD1().immunizationRegistryStatus(SENTINEL), 16);
  });

  test("PD1-17 Immunization Registry Status Effective Date", () => {
    assertField(new PD1().immunizationRegistryStatusEffectiveDate(SENTINEL), 17);
  });

  test("PD1-18 Publicity Code Effective Date", () => {
    assertField(new PD1().publicityCodeEffectiveDate(SENTINEL), 18);
  });

  test("PD1-19 Military Branch", () => {
    assertField(new PD1().militaryBranch(SENTINEL), 19);
  });

  test("PD1-20 Military Rank Grade", () => {
    assertField(new PD1().militaryRankGrade(SENTINEL), 20);
  });

  test("PD1-21 Military Status", () => {
    assertField(new PD1().militaryStatus(SENTINEL), 21);
  });
});
