// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the PID segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { PID } from "./PID.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: PID, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PID field positions", () => {
  test("PID-1 Set ID", () => {
    assertField(new PID().setId(SENTINEL), 1);
  });

  test("PID-2 Patient ID", () => {
    assertField(new PID().patientId(SENTINEL), 2);
  });

  test("PID-3 Patient Identifier List", () => {
    const parts = new PID().patientIdentifierList("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3^C4^C5");
  });

  test("PID-4 Alternate Patient ID", () => {
    assertField(new PID().alternatePatientId(SENTINEL), 4);
  });

  test("PID-5 Patient Name", () => {
    const parts = new PID().patientName("C1", "C2", "C3", "C4", "C5").encode().split("|");
    expect(parts[5]).toBe("C1^C2^C3^C4^C5");
  });

  test("PID-6 Mothers Maiden Name", () => {
    const parts = new PID().mothersMaidenName("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });

  test("PID-7 Date Time Of Birth", () => {
    assertField(new PID().dateTimeOfBirth(SENTINEL), 7);
  });

  test("PID-8 Administrative Sex", () => {
    assertField(new PID().administrativeSex(SENTINEL), 8);
  });

  test("PID-9 Patient Alias", () => {
    const parts = new PID().patientAlias("C1", "C2").encode().split("|");
    expect(parts[9]).toBe("C1^C2");
  });

  test("PID-10 Race", () => {
    assertField(new PID().race(SENTINEL), 10);
  });

  test("PID-11 Patient Address", () => {
    const parts = new PID().patientAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[11]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("PID-12 County Code", () => {
    assertField(new PID().countyCode(SENTINEL), 12);
  });

  test("PID-13 Phone Number Home", () => {
    assertField(new PID().phoneNumberHome(SENTINEL), 13);
  });

  test("PID-14 Phone Number Business", () => {
    assertField(new PID().phoneNumberBusiness(SENTINEL), 14);
  });

  test("PID-15 Primary Language", () => {
    assertField(new PID().primaryLanguage(SENTINEL), 15);
  });

  test("PID-16 Marital Status", () => {
    assertField(new PID().maritalStatus(SENTINEL), 16);
  });

  test("PID-17 Religion", () => {
    assertField(new PID().religion(SENTINEL), 17);
  });

  test("PID-18 Patient Account Number", () => {
    assertField(new PID().patientAccountNumber(SENTINEL), 18);
  });

  test("PID-19 SSN", () => {
    assertField(new PID().ssn(SENTINEL), 19);
  });

  test("PID-20 Drivers License Number", () => {
    const parts = new PID().driversLicenseNumber("C1", "C2", "C3").encode().split("|");
    expect(parts[20]).toBe("C1^C2^C3");
  });

  test("PID-21 Mothers Identifier", () => {
    const parts = new PID().mothersIdentifier("C1", "C2", "C3").encode().split("|");
    expect(parts[21]).toBe("C1^^^C2^C3");
  });

  test("PID-22 Ethnic Group", () => {
    const parts = new PID().ethnicGroup("C1", "C2", "C3").encode().split("|");
    expect(parts[22]).toBe("C1^C2^C3");
  });

  test("PID-23 Birth Place", () => {
    assertField(new PID().birthPlace(SENTINEL), 23);
  });

  test("PID-24 Multiple Birth Indicator", () => {
    assertField(new PID().multipleBirthIndicator(SENTINEL), 24);
  });

  test("PID-25 Birth Order", () => {
    assertField(new PID().birthOrder(SENTINEL), 25);
  });

  test("PID-26 Citizenship", () => {
    const parts = new PID().citizenship("C1", "C2", "C3").encode().split("|");
    expect(parts[26]).toBe("C1^C2^C3");
  });

  test("PID-27 Veterans Military Status", () => {
    const parts = new PID().veteransMilitaryStatus("C1", "C2", "C3").encode().split("|");
    expect(parts[27]).toBe("C1^C2^C3");
  });

  test("PID-28 Nationality", () => {
    const parts = new PID().nationality("C1", "C2", "C3").encode().split("|");
    expect(parts[28]).toBe("C1^C2^C3");
  });

  test("PID-29 Patient Death Date And Time", () => {
    assertField(new PID().patientDeathDateAndTime(SENTINEL), 29);
  });

  test("PID-30 Patient Death Indicator", () => {
    assertField(new PID().patientDeathIndicator(SENTINEL), 30);
  });
});
