// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the PID segment (HL7 v2.3). `encode()`
// emits `PID|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { PID } from "./PID.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: PID, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PID field positions", () => {
  test("PID-1 Set ID", () => {
    assertField(new PID().setId(SENTINEL), 1);
  });

  test("PID-2 Patient ID", () => {
    assertField(new PID().patientId(SENTINEL), 2);
  });

  test("PID-4 Alternate Patient ID", () => {
    assertField(new PID().alternatePatientId(SENTINEL), 4);
  });

  test("PID-6 Mothers Maiden Name", () => {
    assertField(new PID().mothersMaidenName(SENTINEL), 6);
  });

  test("PID-7 Date Time Of Birth", () => {
    assertField(new PID().dateTimeOfBirth(SENTINEL), 7);
  });

  test("PID-8 Administrative Sex", () => {
    assertField(new PID().administrativeSex(SENTINEL), 8);
  });

  test("PID-9 Patient Alias", () => {
    assertField(new PID().patientAlias(SENTINEL), 9);
  });

  test("PID-10 Race", () => {
    assertField(new PID().race(SENTINEL), 10);
  });

  test("PID-12 County Code", () => {
    assertField(new PID().countyCode(SENTINEL), 12);
  });

  test("PID-13 Phone Number Home", () => {
    assertField(new PID().phoneNumberHome(SENTINEL), 13);
  });

  test("PID-14 Phone Number Business", () => {
    assertField(new PID().phoneNumberBusiness(SENTINEL), 14);
  });

  test("PID-15 Primary Language", () => {
    assertField(new PID().primaryLanguage(SENTINEL), 15);
  });

  test("PID-16 Marital Status", () => {
    assertField(new PID().maritalStatus(SENTINEL), 16);
  });

  test("PID-17 Religion", () => {
    assertField(new PID().religion(SENTINEL), 17);
  });

  test("PID-18 Patient Account Number", () => {
    assertField(new PID().patientAccountNumber(SENTINEL), 18);
  });

  test("PID-19 SSN", () => {
    assertField(new PID().ssn(SENTINEL), 19);
  });
});
