// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the PR1 segment (HL7 v2.3). `encode()`
// emits `PR1|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { PR1 } from "./PR1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: PR1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PR1 field positions", () => {
  test("PR1-1 Set ID", () => {
    assertField(new PR1().setId(SENTINEL), 1);
  });

  test("PR1-2 Procedure Coding Method", () => {
    assertField(new PR1().procedureCodingMethod(SENTINEL), 2);
  });

  test("PR1-3 Procedure Code", () => {
    assertField(new PR1().procedureCode(SENTINEL), 3);
  });

  test("PR1-4 Procedure Description", () => {
    assertField(new PR1().procedureDescription(SENTINEL), 4);
  });

  test("PR1-5 Procedure Date Time", () => {
    assertField(new PR1().procedureDateTime(SENTINEL), 5);
  });

  test("PR1-6 Procedure Functional Type", () => {
    assertField(new PR1().procedureFunctionalType(SENTINEL), 6);
  });

  test("PR1-7 Procedure Minutes", () => {
    assertField(new PR1().procedureMinutes(SENTINEL), 7);
  });

  test("PR1-8 Anesthesiologist", () => {
    assertField(new PR1().anesthesiologist(SENTINEL), 8);
  });

  test("PR1-9 Anesthesia Code", () => {
    assertField(new PR1().anesthesiaCode(SENTINEL), 9);
  });

  test("PR1-10 Anesthesia Minutes", () => {
    assertField(new PR1().anesthesiaMinutes(SENTINEL), 10);
  });

  test("PR1-11 Surgeon", () => {
    assertField(new PR1().surgeon(SENTINEL), 11);
  });

  test("PR1-12 Procedure Practitioner", () => {
    assertField(new PR1().procedurePractitioner(SENTINEL), 12);
  });

  test("PR1-13 Consent Code", () => {
    assertField(new PR1().consentCode(SENTINEL), 13);
  });

  test("PR1-14 Procedure Priority", () => {
    assertField(new PR1().procedurePriority(SENTINEL), 14);
  });

  test("PR1-15 Associated Diagnosis Code", () => {
    assertField(new PR1().associatedDiagnosisCode(SENTINEL), 15);
  });
});
