// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the PRA segment (HL7 v2.3). `encode()`
// emits `PRA|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { PRA } from "./PRA.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: PRA, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PRA field positions", () => {
  test("PRA-1 Primary Key Value", () => {
    assertField(new PRA().primaryKeyValue(SENTINEL), 1);
  });

  test("PRA-2 Practitioner Group", () => {
    assertField(new PRA().practitionerGroup(SENTINEL), 2);
  });

  test("PRA-3 Practitioner Category", () => {
    assertField(new PRA().practitionerCategory(SENTINEL), 3);
  });

  test("PRA-4 Provider Billing", () => {
    assertField(new PRA().providerBilling(SENTINEL), 4);
  });

  test("PRA-5 Specialty", () => {
    assertField(new PRA().specialty(SENTINEL), 5);
  });

  test("PRA-6 Practitioner ID Numbers", () => {
    assertField(new PRA().practitionerIdNumbers(SENTINEL), 6);
  });

  test("PRA-8 Date Entered Practice", () => {
    assertField(new PRA().dateEnteredPractice(SENTINEL), 8);
  });
});
