// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the PV1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { PV1 } from "./PV1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: PV1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PV1 field positions", () => {
  test("PV1-1 Set ID", () => {
    assertField(new PV1().setId(SENTINEL), 1);
  });

  test("PV1-2 Patient Class", () => {
    assertField(new PV1().patientClass(SENTINEL), 2);
  });

  test("PV1-3 Assigned Patient Location", () => {
    const parts = new PV1().assignedPatientLocation("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("PV1-4 Admission Type", () => {
    assertField(new PV1().admissionType(SENTINEL), 4);
  });

  test("PV1-5 Preadmit Number", () => {
    assertField(new PV1().preadmitNumber(SENTINEL), 5);
  });

  test("PV1-6 Prior Patient Location", () => {
    const parts = new PV1().priorPatientLocation("C1", "C2", "C3", "C4").encode().split("|");
    expect(parts[6]).toBe("C1^C2^C3^C4");
  });

  test("PV1-7 Attending Doctor", () => {
    const parts = new PV1().attendingDoctor("C1", "C2", "C3").encode().split("|");
    expect(parts[7]).toBe("C1^C2^C3");
  });

  test("PV1-8 Referring Doctor", () => {
    const parts = new PV1().referringDoctor("C1", "C2", "C3").encode().split("|");
    expect(parts[8]).toBe("C1^C2^C3");
  });

  test("PV1-9 Consulting Doctor", () => {
    const parts = new PV1().consultingDoctor("C1", "C2", "C3").encode().split("|");
    expect(parts[9]).toBe("C1^C2^C3");
  });

  test("PV1-10 Hospital Service", () => {
    assertField(new PV1().hospitalService(SENTINEL), 10);
  });

  test("PV1-11 Temporary Location", () => {
    const parts = new PV1().temporaryLocation("C1", "C2", "C3").encode().split("|");
    expect(parts[11]).toBe("C1^C2^C3");
  });

  test("PV1-12 Preadmit Test Indicator", () => {
    assertField(new PV1().preadmitTestIndicator(SENTINEL), 12);
  });

  test("PV1-13 Re Admission Indicator", () => {
    assertField(new PV1().reAdmissionIndicator(SENTINEL), 13);
  });

  test("PV1-14 Admit Source", () => {
    assertField(new PV1().admitSource(SENTINEL), 14);
  });

  test("PV1-15 Ambulatory Status", () => {
    assertField(new PV1().ambulatoryStatus(SENTINEL), 15);
  });

  test("PV1-16 VIP Indicator", () => {
    assertField(new PV1().vipIndicator(SENTINEL), 16);
  });

  test("PV1-17 Admitting Doctor", () => {
    const parts = new PV1().admittingDoctor("C1", "C2", "C3").encode().split("|");
    expect(parts[17]).toBe("C1^C2^C3");
  });

  test("PV1-18 Patient Type", () => {
    assertField(new PV1().patientType(SENTINEL), 18);
  });

  test("PV1-19 Visit Number", () => {
    const parts = new PV1().visitNumber("C1", "C2", "C3").encode().split("|");
    expect(parts[19]).toBe("C1^^^C2^C3");
  });

  test("PV1-20 Financial Class", () => {
    const parts = new PV1().financialClass("C1", "C2").encode().split("|");
    expect(parts[20]).toBe("C1^C2");
  });

  test("PV1-21 Charge Price Indicator", () => {
    assertField(new PV1().chargePriceIndicator(SENTINEL), 21);
  });

  test("PV1-22 Courtesy Code", () => {
    assertField(new PV1().courtesyCode(SENTINEL), 22);
  });

  test("PV1-23 Credit Rating", () => {
    assertField(new PV1().creditRating(SENTINEL), 23);
  });

  test("PV1-24 Contract Code", () => {
    assertField(new PV1().contractCode(SENTINEL), 24);
  });

  test("PV1-25 Contract Effective Date", () => {
    assertField(new PV1().contractEffectiveDate(SENTINEL), 25);
  });

  test("PV1-26 Contract Amount", () => {
    assertField(new PV1().contractAmount(SENTINEL), 26);
  });

  test("PV1-27 Contract Period", () => {
    assertField(new PV1().contractPeriod(SENTINEL), 27);
  });

  test("PV1-28 Interest Code", () => {
    assertField(new PV1().interestCode(SENTINEL), 28);
  });

  test("PV1-29 Transfer To Bad Debt Code", () => {
    assertField(new PV1().transferToBadDebtCode(SENTINEL), 29);
  });

  test("PV1-30 Transfer To Bad Debt Date", () => {
    assertField(new PV1().transferToBadDebtDate(SENTINEL), 30);
  });

  test("PV1-31 Bad Debt Agency Code", () => {
    assertField(new PV1().badDebtAgencyCode(SENTINEL), 31);
  });

  test("PV1-32 Bad Debt Transfer Amount", () => {
    assertField(new PV1().badDebtTransferAmount(SENTINEL), 32);
  });

  test("PV1-33 Bad Debt Recovery Amount", () => {
    assertField(new PV1().badDebtRecoveryAmount(SENTINEL), 33);
  });

  test("PV1-34 Delete Account Indicator", () => {
    assertField(new PV1().deleteAccountIndicator(SENTINEL), 34);
  });

  test("PV1-35 Delete Account Date", () => {
    assertField(new PV1().deleteAccountDate(SENTINEL), 35);
  });

  test("PV1-36 Discharge Disposition", () => {
    assertField(new PV1().dischargeDisposition(SENTINEL), 36);
  });

  test("PV1-37 Discharged To Location", () => {
    const parts = new PV1().dischargedToLocation("C1", "C2").encode().split("|");
    expect(parts[37]).toBe("C1^C2");
  });

  test("PV1-38 Diet Type", () => {
    const parts = new PV1().dietType("C1", "C2", "C3").encode().split("|");
    expect(parts[38]).toBe("C1^C2^C3");
  });

  test("PV1-39 Servicing Facility", () => {
    assertField(new PV1().servicingFacility(SENTINEL), 39);
  });

  test("PV1-40 Bed Status", () => {
    assertField(new PV1().bedStatus(SENTINEL), 40);
  });

  test("PV1-41 Account Status", () => {
    assertField(new PV1().accountStatus(SENTINEL), 41);
  });

  test("PV1-42 Pending Location", () => {
    const parts = new PV1().pendingLocation("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[42]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("PV1-43 Prior Temporary Location", () => {
    const parts = new PV1().priorTemporaryLocation("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[43]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("PV1-44 Admit Date Time", () => {
    assertField(new PV1().admitDateTime(SENTINEL), 44);
  });

  test("PV1-45 Discharge Date Time", () => {
    assertField(new PV1().dischargeDateTime(SENTINEL), 45);
  });

  test("PV1-46 Current Patient Balance", () => {
    assertField(new PV1().currentPatientBalance(SENTINEL), 46);
  });

  test("PV1-47 Total Charges", () => {
    assertField(new PV1().totalCharges(SENTINEL), 47);
  });

  test("PV1-48 Total Adjustments", () => {
    assertField(new PV1().totalAdjustments(SENTINEL), 48);
  });

  test("PV1-49 Total Payments", () => {
    assertField(new PV1().totalPayments(SENTINEL), 49);
  });

  test("PV1-50 Alternate Visit ID", () => {
    const parts = new PV1().alternateVisitId("C1", "C2", "C3").encode().split("|");
    expect(parts[50]).toBe("C1^^^C2^C3");
  });

  test("PV1-51 Visit Indicator", () => {
    assertField(new PV1().visitIndicator(SENTINEL), 51);
  });

  test("PV1-52 Other Healthcare Provider", () => {
    const parts = new PV1().otherHealthcareProvider("C1", "C2", "C3").encode().split("|");
    expect(parts[52]).toBe("C1^C2^C3");
  });
});
