// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the PV2 segment (HL7 v2.3). `encode()`
// emits `PV2|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { PV2 } from "./PV2.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: PV2, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PV2 field positions", () => {
  test("PV2-1 Prior Pending Location", () => {
    assertField(new PV2().priorPendingLocation(SENTINEL), 1);
  });

  test("PV2-2 Accommodation Code", () => {
    assertField(new PV2().accommodationCode(SENTINEL), 2);
  });

  test("PV2-3 Admit Reason", () => {
    assertField(new PV2().admitReason(SENTINEL), 3);
  });

  test("PV2-4 Transfer Reason", () => {
    assertField(new PV2().transferReason(SENTINEL), 4);
  });

  test("PV2-5 Patient Valuables", () => {
    assertField(new PV2().patientValuables(SENTINEL), 5);
  });

  test("PV2-6 Patient Valuables Location", () => {
    assertField(new PV2().patientValuablesLocation(SENTINEL), 6);
  });

  test("PV2-7 Visit User Code", () => {
    assertField(new PV2().visitUserCode(SENTINEL), 7);
  });

  test("PV2-8 Expected Admit Date Time", () => {
    assertField(new PV2().expectedAdmitDateTime(SENTINEL), 8);
  });

  test("PV2-9 Expected Discharge Date Time", () => {
    assertField(new PV2().expectedDischargeDateTime(SENTINEL), 9);
  });

  test("PV2-10 Estimated Length Of Stay", () => {
    assertField(new PV2().estimatedLengthOfStay(SENTINEL), 10);
  });

  test("PV2-11 Actual Length Of Stay", () => {
    assertField(new PV2().actualLengthOfStay(SENTINEL), 11);
  });

  test("PV2-12 Visit Description", () => {
    assertField(new PV2().visitDescription(SENTINEL), 12);
  });

  test("PV2-13 Referral Source Code", () => {
    assertField(new PV2().referralSourceCode(SENTINEL), 13);
  });

  test("PV2-14 Previous Service Date", () => {
    assertField(new PV2().previousServiceDate(SENTINEL), 14);
  });

  test("PV2-15 Employment Illness Related", () => {
    assertField(new PV2().employmentIllnessRelated(SENTINEL), 15);
  });

  test("PV2-16 Purge Status Code", () => {
    assertField(new PV2().purgeStatusCode(SENTINEL), 16);
  });

  test("PV2-17 Purge Status Date", () => {
    assertField(new PV2().purgeStatusDate(SENTINEL), 17);
  });

  test("PV2-18 Special Program Code", () => {
    assertField(new PV2().specialProgramCode(SENTINEL), 18);
  });

  test("PV2-19 Retention Indicator", () => {
    assertField(new PV2().retentionIndicator(SENTINEL), 19);
  });

  test("PV2-20 Expected Number Of Insurance Plans", () => {
    assertField(new PV2().expectedNumberOfInsurancePlans(SENTINEL), 20);
  });

  test("PV2-21 Visit Publicity Code", () => {
    assertField(new PV2().visitPublicityCode(SENTINEL), 21);
  });

  test("PV2-22 Visit Protection Indicator", () => {
    assertField(new PV2().visitProtectionIndicator(SENTINEL), 22);
  });

  test("PV2-25 Visit Priority Code", () => {
    assertField(new PV2().visitPriorityCode(SENTINEL), 25);
  });

  test("PV2-38 Mode Of Arrival Code", () => {
    assertField(new PV2().modeOfArrivalCode(SENTINEL), 38);
  });
});
