// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the PV2 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { PV2 } from "./PV2.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: PV2, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PV2 field positions", () => {
  test("PV2-1 Prior Pending Location", () => {
    const parts = new PV2().priorPendingLocation({ pointOfCare: "C1", room: "C2", bed: "C3", facility: "C4" }).encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3^C4");
  });

  test("PV2-2 Accommodation Code", () => {
    const parts = new PV2().accommodationCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3");
  });

  test("PV2-3 Admit Reason", () => {
    const parts = new PV2().admitReason({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("PV2-4 Transfer Reason", () => {
    const parts = new PV2().transferReason({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[4]).toBe("C1^C2^C3");
  });

  test("PV2-5 Patient Valuables", () => {
    assertField(new PV2().patientValuables(SENTINEL), 5);
  });

  test("PV2-6 Patient Valuables Location", () => {
    assertField(new PV2().patientValuablesLocation(SENTINEL), 6);
  });

  test("PV2-7 Visit User Code", () => {
    assertField(new PV2().visitUserCode(SENTINEL), 7);
  });

  test("PV2-8 Expected Admit Date Time", () => {
    assertField(new PV2().expectedAdmitDateTime(SENTINEL), 8);
  });

  test("PV2-9 Expected Discharge Date Time", () => {
    assertField(new PV2().expectedDischargeDateTime(SENTINEL), 9);
  });

  test("PV2-10 Estimated Length Of Stay", () => {
    assertField(new PV2().estimatedLengthOfStay(SENTINEL), 10);
  });

  test("PV2-11 Actual Length Of Stay", () => {
    assertField(new PV2().actualLengthOfStay(SENTINEL), 11);
  });

  test("PV2-12 Visit Description", () => {
    assertField(new PV2().visitDescription(SENTINEL), 12);
  });

  test("PV2-13 Referral Source Code", () => {
    const parts = new PV2().referralSourceCode({ id: "C1", familyName: "C2", givenName: "C3" }).encode().split("|");
    expect(parts[13]).toBe("C1^C2^C3");
  });

  test("PV2-14 Previous Service Date", () => {
    assertField(new PV2().previousServiceDate(SENTINEL), 14);
  });

  test("PV2-15 Employment Illness Related", () => {
    assertField(new PV2().employmentIllnessRelated(SENTINEL), 15);
  });

  test("PV2-16 Purge Status Code", () => {
    assertField(new PV2().purgeStatusCode(SENTINEL), 16);
  });

  test("PV2-17 Purge Status Date", () => {
    assertField(new PV2().purgeStatusDate(SENTINEL), 17);
  });

  test("PV2-18 Special Program Code", () => {
    assertField(new PV2().specialProgramCode(SENTINEL), 18);
  });

  test("PV2-19 Retention Indicator", () => {
    assertField(new PV2().retentionIndicator(SENTINEL), 19);
  });

  test("PV2-20 Expected Number Of Insurance Plans", () => {
    assertField(new PV2().expectedNumberOfInsurancePlans(SENTINEL), 20);
  });

  test("PV2-21 Visit Publicity Code", () => {
    assertField(new PV2().visitPublicityCode(SENTINEL), 21);
  });

  test("PV2-22 Visit Protection Indicator", () => {
    assertField(new PV2().visitProtectionIndicator(SENTINEL), 22);
  });

  test("PV2-25 Visit Priority Code", () => {
    assertField(new PV2().visitPriorityCode(SENTINEL), 25);
  });

  test("PV2-38 Mode Of Arrival Code", () => {
    const parts = new PV2().modeOfArrivalCode({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[38]).toBe("C1^C2");
  });

  test("PV2-23 Clinic Organization Name", () => {
    assertField(new PV2().clinicOrganizationName(SENTINEL), 23);
  });

  test("PV2-24 Patient Status Code", () => {
    assertField(new PV2().patientStatusCode(SENTINEL), 24);
  });

  test("PV2-26 Previous Treatment Date", () => {
    assertField(new PV2().previousTreatmentDate(SENTINEL), 26);
  });

  test("PV2-27 Expected Discharge Disposition", () => {
    assertField(new PV2().expectedDischargeDisposition(SENTINEL), 27);
  });

  test("PV2-28 Signature On File Date", () => {
    assertField(new PV2().signatureOnFileDate(SENTINEL), 28);
  });

  test("PV2-29 First Similar Illness Date", () => {
    assertField(new PV2().firstSimilarIllnessDate(SENTINEL), 29);
  });

  test("PV2-30 Patient Charge Adjustment Code", () => {
    const parts = new PV2().patientChargeAdjustmentCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[30]).toBe("C1^C2^C3");
  });

  test("PV2-31 Recurring Service Code", () => {
    assertField(new PV2().recurringServiceCode(SENTINEL), 31);
  });

  test("PV2-32 Billing Media Code", () => {
    assertField(new PV2().billingMediaCode(SENTINEL), 32);
  });

  test("PV2-33 Expected Surgery Date And Time", () => {
    assertField(new PV2().expectedSurgeryDateAndTime(SENTINEL), 33);
  });

  test("PV2-34 Military Partnership Code", () => {
    assertField(new PV2().militaryPartnershipCode(SENTINEL), 34);
  });

  test("PV2-35 Military Non Availability Code", () => {
    assertField(new PV2().militaryNonAvailabilityCode(SENTINEL), 35);
  });

  test("PV2-36 Newborn Baby Indicator", () => {
    assertField(new PV2().newbornBabyIndicator(SENTINEL), 36);
  });

  test("PV2-37 Baby Detained Indicator", () => {
    assertField(new PV2().babyDetainedIndicator(SENTINEL), 37);
  });
});
