// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RGS segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RGS } from "./RGS.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RGS, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RGS field positions", () => {
  test("RGS-1 Set ID", () => {
    assertField(new RGS().setId(SENTINEL), 1);
  });

  test("RGS-2 Segment Action Code", () => {
    assertField(new RGS().segmentActionCode(SENTINEL), 2);
  });

  test("RGS-3 Resource Group ID", () => {
    const parts = new RGS().resourceGroupId({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[3]).toBe("C1^C2");
  });
});
