// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the RGS segment (HL7 v2.3). `encode()`
// emits `RGS|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { RGS } from "./RGS.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: RGS, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RGS field positions", () => {
  test("RGS-1 Set ID", () => {
    assertField(new RGS().setId(SENTINEL), 1);
  });

  test("RGS-2 Segment Action Code", () => {
    assertField(new RGS().segmentActionCode(SENTINEL), 2);
  });

  test("RGS-3 Resource Group ID", () => {
    assertField(new RGS().resourceGroupId(SENTINEL), 3);
  });
});
