// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the ROL segment (HL7 v2.3). `encode()`
// emits `ROL|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { ROL } from "./ROL.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: ROL, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ROL field positions", () => {
  test("ROL-1 Role Instance ID", () => {
    assertField(new ROL().roleInstanceId(SENTINEL), 1);
  });

  test("ROL-2 Action Code", () => {
    assertField(new ROL().actionCode(SENTINEL), 2);
  });

  test("ROL-3 Role", () => {
    assertField(new ROL().role(SENTINEL), 3);
  });

  test("ROL-4 Role Person", () => {
    assertField(new ROL().rolePerson(SENTINEL), 4);
  });

  test("ROL-5 Role Begin Date Time", () => {
    assertField(new ROL().roleBeginDateTime(SENTINEL), 5);
  });

  test("ROL-6 Role End Date Time", () => {
    assertField(new ROL().roleEndDateTime(SENTINEL), 6);
  });

  test("ROL-7 Role Duration", () => {
    assertField(new ROL().roleDuration(SENTINEL), 7);
  });

  test("ROL-8 Role Action Reason", () => {
    assertField(new ROL().roleActionReason(SENTINEL), 8);
  });

  test("ROL-9 Provider Type", () => {
    assertField(new ROL().providerType(SENTINEL), 9);
  });

  test("ROL-10 Organization Unit Type", () => {
    assertField(new ROL().organizationUnitType(SENTINEL), 10);
  });

  test("ROL-11 Office Address", () => {
    assertField(new ROL().officeAddress(SENTINEL), 11);
  });

  test("ROL-12 Phone", () => {
    assertField(new ROL().phone(SENTINEL), 12);
  });
});
