// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the ROL segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { ROL } from "./ROL.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: ROL, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ROL field positions", () => {
  test("ROL-1 Role Instance ID", () => {
    const parts = new ROL().roleInstanceId({ entityId: "C1", namespaceId: "C2", universalId: "C3", universalIdType: "C4" }).encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3^C4");
  });

  test("ROL-2 Action Code", () => {
    assertField(new ROL().actionCode(SENTINEL), 2);
  });

  test("ROL-3 Role", () => {
    const parts = new ROL().role({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[3]).toBe("C1^C2^C3");
  });

  test("ROL-4 Role Person", () => {
    const parts = new ROL().rolePerson({ id: "C1", familyName: "C2", givenName: "C3", middleName: "C4" }).encode().split("|");
    expect(parts[4]).toBe("C1^C2^C3^C4");
  });

  test("ROL-5 Role Begin Date Time", () => {
    assertField(new ROL().roleBeginDateTime(SENTINEL), 5);
  });

  test("ROL-6 Role End Date Time", () => {
    assertField(new ROL().roleEndDateTime(SENTINEL), 6);
  });

  test("ROL-7 Role Duration", () => {
    const parts = new ROL().roleDuration({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[7]).toBe("C1^C2");
  });

  test("ROL-8 Role Action Reason", () => {
    const parts = new ROL().roleActionReason({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[8]).toBe("C1^C2");
  });

  test("ROL-9 Provider Type", () => {
    const parts = new ROL().providerType({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[9]).toBe("C1^C2");
  });

  test("ROL-10 Organization Unit Type", () => {
    const parts = new ROL().organizationUnitType({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("ROL-11 Office Address", () => {
    const parts = new ROL().officeAddress({ street: "C1", city: "C2", state: "C3", zip: "C4" }).encode().split("|");
    expect(parts[11]).toBe("C1^^C2^C3^C4");
  });

  test("ROL-12 Phone", () => {
    assertField(new ROL().phone(SENTINEL), 12);
  });
});
