// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXA segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXA } from "./RXA.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXA, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXA field positions", () => {
  test("RXA-1 Give Sub ID Counter", () => {
    assertField(new RXA().giveSubIdCounter(SENTINEL), 1);
  });

  test("RXA-2 Administration Sub ID Counter", () => {
    assertField(new RXA().administrationSubIdCounter(SENTINEL), 2);
  });

  test("RXA-3 Date Time Start Of Administration", () => {
    assertField(new RXA().dateTimeStartOfAdministration(SENTINEL), 3);
  });

  test("RXA-4 Date Time End Of Administration", () => {
    assertField(new RXA().dateTimeEndOfAdministration(SENTINEL), 4);
  });

  test("RXA-5 Administered Code", () => {
    const parts = new RXA().administeredCode("C1", "C2", "C3").encode().split("|");
    expect(parts[5]).toBe("C1^C2^C3");
  });

  test("RXA-6 Administered Amount", () => {
    assertField(new RXA().administeredAmount(SENTINEL), 6);
  });

  test("RXA-7 Administered Units", () => {
    const parts = new RXA().administeredUnits("C1", "C2", "C3").encode().split("|");
    expect(parts[7]).toBe("C1^C2^C3");
  });

  test("RXA-8 Administered Dosage Form", () => {
    const parts = new RXA().administeredDosageForm("C1", "C2").encode().split("|");
    expect(parts[8]).toBe("C1^C2");
  });

  test("RXA-9 Administration Notes", () => {
    const parts = new RXA().administrationNotes("C1", "C2").encode().split("|");
    expect(parts[9]).toBe("C1^C2");
  });

  test("RXA-10 Administering Provider", () => {
    const parts = new RXA().administeringProvider("C1", "C2", "C3").encode().split("|");
    expect(parts[10]).toBe("C1^C2^C3");
  });

  test("RXA-11 Administered At Location", () => {
    const parts = new RXA().administeredAtLocation("C1", "C2", "C3", "C4").encode().split("|");
    expect(parts[11]).toBe("C1^C2^C3^C4");
  });

  test("RXA-12 Administered Per", () => {
    assertField(new RXA().administeredPer(SENTINEL), 12);
  });

  test("RXA-13 Administered Strength", () => {
    assertField(new RXA().administeredStrength(SENTINEL), 13);
  });

  test("RXA-14 Administered Strength Units", () => {
    const parts = new RXA().administeredStrengthUnits("C1", "C2").encode().split("|");
    expect(parts[14]).toBe("C1^C2");
  });

  test("RXA-15 Substance Lot Number", () => {
    assertField(new RXA().substanceLotNumber(SENTINEL), 15);
  });

  test("RXA-16 Substance Expiration Date", () => {
    assertField(new RXA().substanceExpirationDate(SENTINEL), 16);
  });

  test("RXA-17 Substance Manufacturer Name", () => {
    const parts = new RXA().substanceManufacturerName("C1", "C2").encode().split("|");
    expect(parts[17]).toBe("C1^C2");
  });

  test("RXA-18 Substance Refusal Reason", () => {
    const parts = new RXA().substanceRefusalReason("C1", "C2").encode().split("|");
    expect(parts[18]).toBe("C1^C2");
  });

  test("RXA-19 Indication", () => {
    const parts = new RXA().indication("C1", "C2").encode().split("|");
    expect(parts[19]).toBe("C1^C2");
  });

  test("RXA-20 Completion Status", () => {
    assertField(new RXA().completionStatus(SENTINEL), 20);
  });

  test("RXA-21 Action Code", () => {
    assertField(new RXA().actionCode(SENTINEL), 21);
  });

  test("RXA-22 System Entry Date Time", () => {
    assertField(new RXA().systemEntryDateTime(SENTINEL), 22);
  });
});
