// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the RXA segment (HL7 v2.3). `encode()`
// emits `RXA|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { RXA } from "./RXA.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: RXA, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXA field positions", () => {
  test("RXA-1 Give Sub ID Counter", () => {
    assertField(new RXA().giveSubIdCounter(SENTINEL), 1);
  });

  test("RXA-2 Administration Sub ID Counter", () => {
    assertField(new RXA().administrationSubIdCounter(SENTINEL), 2);
  });

  test("RXA-3 Date Time Start Of Administration", () => {
    assertField(new RXA().dateTimeStartOfAdministration(SENTINEL), 3);
  });

  test("RXA-4 Date Time End Of Administration", () => {
    assertField(new RXA().dateTimeEndOfAdministration(SENTINEL), 4);
  });

  test("RXA-5 Administered Code", () => {
    assertField(new RXA().administeredCode(SENTINEL), 5);
  });

  test("RXA-6 Administered Amount", () => {
    assertField(new RXA().administeredAmount(SENTINEL), 6);
  });

  test("RXA-7 Administered Units", () => {
    assertField(new RXA().administeredUnits(SENTINEL), 7);
  });

  test("RXA-8 Administered Dosage Form", () => {
    assertField(new RXA().administeredDosageForm(SENTINEL), 8);
  });

  test("RXA-9 Administration Notes", () => {
    assertField(new RXA().administrationNotes(SENTINEL), 9);
  });

  test("RXA-10 Administering Provider", () => {
    assertField(new RXA().administeringProvider(SENTINEL), 10);
  });

  test("RXA-11 Administered At Location", () => {
    assertField(new RXA().administeredAtLocation(SENTINEL), 11);
  });

  test("RXA-12 Administered Per", () => {
    assertField(new RXA().administeredPer(SENTINEL), 12);
  });

  test("RXA-13 Administered Strength", () => {
    assertField(new RXA().administeredStrength(SENTINEL), 13);
  });

  test("RXA-14 Administered Strength Units", () => {
    assertField(new RXA().administeredStrengthUnits(SENTINEL), 14);
  });

  test("RXA-15 Substance Lot Number", () => {
    assertField(new RXA().substanceLotNumber(SENTINEL), 15);
  });

  test("RXA-16 Substance Expiration Date", () => {
    assertField(new RXA().substanceExpirationDate(SENTINEL), 16);
  });

  test("RXA-17 Substance Manufacturer Name", () => {
    assertField(new RXA().substanceManufacturerName(SENTINEL), 17);
  });

  test("RXA-18 Substance Refusal Reason", () => {
    assertField(new RXA().substanceRefusalReason(SENTINEL), 18);
  });

  test("RXA-19 Indication", () => {
    assertField(new RXA().indication(SENTINEL), 19);
  });

  test("RXA-20 Completion Status", () => {
    assertField(new RXA().completionStatus(SENTINEL), 20);
  });

  test("RXA-21 Action Code", () => {
    assertField(new RXA().actionCode(SENTINEL), 21);
  });

  test("RXA-22 System Entry Date Time", () => {
    assertField(new RXA().systemEntryDateTime(SENTINEL), 22);
  });
});
