// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXD segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXD } from "./RXD.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXD, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXD field positions", () => {
  test("RXD-1 Dispense Sub ID Counter", () => {
    assertField(new RXD().dispenseSubIdCounter(SENTINEL), 1);
  });

  test("RXD-2 Dispense Give Code", () => {
    const parts = new RXD().dispenseGiveCode("C1", "C2", "C3").encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3");
  });

  test("RXD-3 Date Time Dispensed", () => {
    assertField(new RXD().dateTimeDispensed(SENTINEL), 3);
  });

  test("RXD-4 Actual Dispense Amount", () => {
    assertField(new RXD().actualDispenseAmount(SENTINEL), 4);
  });

  test("RXD-5 Actual Dispense Units", () => {
    const parts = new RXD().actualDispenseUnits("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("RXD-6 Actual Dosage Form", () => {
    const parts = new RXD().actualDosageForm("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });

  test("RXD-7 Prescription Number", () => {
    assertField(new RXD().prescriptionNumber(SENTINEL), 7);
  });

  test("RXD-8 Number Of Refills Remaining", () => {
    assertField(new RXD().numberOfRefillsRemaining(SENTINEL), 8);
  });

  test("RXD-9 Dispense Notes", () => {
    assertField(new RXD().dispenseNotes(SENTINEL), 9);
  });

  test("RXD-10 Dispensing Provider", () => {
    const parts = new RXD().dispensingProvider("C1", "C2", "C3").encode().split("|");
    expect(parts[10]).toBe("C1^C2^C3");
  });

  test("RXD-11 Substitution Status", () => {
    assertField(new RXD().substitutionStatus(SENTINEL), 11);
  });

  test("RXD-12 Total Daily Dose", () => {
    const parts = new RXD().totalDailyDose("C1", "C2").encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });

  test("RXD-13 Dispense To Location", () => {
    const parts = new RXD().dispenseToLocation("C1", "C2", "C3", "C4").encode().split("|");
    expect(parts[13]).toBe("C1^C2^C3^C4");
  });

  test("RXD-14 Needs Human Review", () => {
    assertField(new RXD().needsHumanReview(SENTINEL), 14);
  });

  test("RXD-15 Special Dispensing Instructions", () => {
    const parts = new RXD().specialDispensingInstructions("C1", "C2", "C3").encode().split("|");
    expect(parts[15]).toBe("C1^C2^C3");
  });

  test("RXD-16 Actual Strength", () => {
    assertField(new RXD().actualStrength(SENTINEL), 16);
  });

  test("RXD-17 Actual Strength Unit", () => {
    const parts = new RXD().actualStrengthUnit("C1", "C2", "C3").encode().split("|");
    expect(parts[17]).toBe("C1^C2^C3");
  });

  test("RXD-18 Substance Lot Number", () => {
    assertField(new RXD().substanceLotNumber(SENTINEL), 18);
  });

  test("RXD-19 Substance Expiration Date", () => {
    assertField(new RXD().substanceExpirationDate(SENTINEL), 19);
  });

  test("RXD-20 Substance Manufacturer Name", () => {
    const parts = new RXD().substanceManufacturerName("C1", "C2").encode().split("|");
    expect(parts[20]).toBe("C1^C2");
  });

  test("RXD-21 Indication", () => {
    const parts = new RXD().indication("C1", "C2", "C3").encode().split("|");
    expect(parts[21]).toBe("C1^C2^C3");
  });

  test("RXD-22 Dispense Package Size", () => {
    assertField(new RXD().dispensePackageSize(SENTINEL), 22);
  });

  test("RXD-23 Dispense Package Size Unit", () => {
    const parts = new RXD().dispensePackageSizeUnit("C1", "C2", "C3").encode().split("|");
    expect(parts[23]).toBe("C1^C2^C3");
  });

  test("RXD-24 Dispense Package Method", () => {
    assertField(new RXD().dispensePackageMethod(SENTINEL), 24);
  });
});
