// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the RXD segment (HL7 v2.3). `encode()`
// emits `RXD|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { RXD } from "./RXD.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: RXD, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXD field positions", () => {
  test("RXD-1 Dispense Sub ID Counter", () => {
    assertField(new RXD().dispenseSubIdCounter(SENTINEL), 1);
  });

  test("RXD-2 Dispense Give Code", () => {
    assertField(new RXD().dispenseGiveCode(SENTINEL), 2);
  });

  test("RXD-3 Date Time Dispensed", () => {
    assertField(new RXD().dateTimeDispensed(SENTINEL), 3);
  });

  test("RXD-4 Actual Dispense Amount", () => {
    assertField(new RXD().actualDispenseAmount(SENTINEL), 4);
  });

  test("RXD-5 Actual Dispense Units", () => {
    assertField(new RXD().actualDispenseUnits(SENTINEL), 5);
  });

  test("RXD-6 Actual Dosage Form", () => {
    assertField(new RXD().actualDosageForm(SENTINEL), 6);
  });

  test("RXD-7 Prescription Number", () => {
    assertField(new RXD().prescriptionNumber(SENTINEL), 7);
  });

  test("RXD-8 Number Of Refills Remaining", () => {
    assertField(new RXD().numberOfRefillsRemaining(SENTINEL), 8);
  });

  test("RXD-9 Dispense Notes", () => {
    assertField(new RXD().dispenseNotes(SENTINEL), 9);
  });

  test("RXD-10 Dispensing Provider", () => {
    assertField(new RXD().dispensingProvider(SENTINEL), 10);
  });

  test("RXD-11 Substitution Status", () => {
    assertField(new RXD().substitutionStatus(SENTINEL), 11);
  });

  test("RXD-18 Substance Lot Number", () => {
    assertField(new RXD().substanceLotNumber(SENTINEL), 18);
  });

  test("RXD-19 Substance Expiration Date", () => {
    assertField(new RXD().substanceExpirationDate(SENTINEL), 19);
  });

  test("RXD-20 Substance Manufacturer Name", () => {
    assertField(new RXD().substanceManufacturerName(SENTINEL), 20);
  });
});
