// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the RXE segment (HL7 v2.3). `encode()`
// emits `RXE|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { RXE } from "./RXE.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: RXE, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXE field positions", () => {
  test("RXE-1 Quantity Timing", () => {
    assertField(new RXE().quantityTiming(SENTINEL), 1);
  });

  test("RXE-2 Give Code", () => {
    assertField(new RXE().giveCode(SENTINEL), 2);
  });

  test("RXE-3 Give Amount Min", () => {
    assertField(new RXE().giveAmountMin(SENTINEL), 3);
  });

  test("RXE-4 Give Amount Max", () => {
    assertField(new RXE().giveAmountMax(SENTINEL), 4);
  });

  test("RXE-5 Give Units", () => {
    assertField(new RXE().giveUnits(SENTINEL), 5);
  });

  test("RXE-6 Give Dosage Form", () => {
    assertField(new RXE().giveDosageForm(SENTINEL), 6);
  });

  test("RXE-7 Provider Admin Instructions", () => {
    assertField(new RXE().providerAdminInstructions(SENTINEL), 7);
  });

  test("RXE-10 Dispense Amount", () => {
    assertField(new RXE().dispenseAmount(SENTINEL), 10);
  });

  test("RXE-11 Dispense Units", () => {
    assertField(new RXE().dispenseUnits(SENTINEL), 11);
  });

  test("RXE-12 Number Of Refills", () => {
    assertField(new RXE().numberOfRefills(SENTINEL), 12);
  });

  test("RXE-13 Ordering Provider DEA Number", () => {
    assertField(new RXE().orderingProviderDeaNumber(SENTINEL), 13);
  });

  test("RXE-14 Pharmacist Verifier ID", () => {
    assertField(new RXE().pharmacistVerifierId(SENTINEL), 14);
  });

  test("RXE-15 Prescription Number", () => {
    assertField(new RXE().prescriptionNumber(SENTINEL), 15);
  });

  test("RXE-16 Number Of Refills Remaining", () => {
    assertField(new RXE().numberOfRefillsRemaining(SENTINEL), 16);
  });

  test("RXE-22 Give Per", () => {
    assertField(new RXE().givePer(SENTINEL), 22);
  });

  test("RXE-23 Give Rate Amount", () => {
    assertField(new RXE().giveRateAmount(SENTINEL), 23);
  });

  test("RXE-24 Give Rate Units", () => {
    assertField(new RXE().giveRateUnits(SENTINEL), 24);
  });

  test("RXE-25 Give Strength", () => {
    assertField(new RXE().giveStrength(SENTINEL), 25);
  });

  test("RXE-26 Give Strength Units", () => {
    assertField(new RXE().giveStrengthUnits(SENTINEL), 26);
  });
});
