// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXE segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXE } from "./RXE.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXE, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXE field positions", () => {
  test("RXE-1 Quantity Timing", () => {
    assertField(new RXE().quantityTiming(SENTINEL), 1);
  });

  test("RXE-2 Give Code", () => {
    const parts = new RXE().giveCode("C1", "C2", "C3").encode().split("|");
    expect(parts[2]).toBe("C1^C2^C3");
  });

  test("RXE-3 Give Amount Min", () => {
    assertField(new RXE().giveAmountMin(SENTINEL), 3);
  });

  test("RXE-4 Give Amount Max", () => {
    assertField(new RXE().giveAmountMax(SENTINEL), 4);
  });

  test("RXE-5 Give Units", () => {
    const parts = new RXE().giveUnits("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("RXE-6 Give Dosage Form", () => {
    const parts = new RXE().giveDosageForm("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });

  test("RXE-7 Provider Admin Instructions", () => {
    const parts = new RXE().providerAdminInstructions("C1", "C2").encode().split("|");
    expect(parts[7]).toBe("C1^C2");
  });

  test("RXE-8 Deliver To Location", () => {
    assertField(new RXE().deliverToLocation(SENTINEL), 8);
  });

  test("RXE-9 Substitution Status", () => {
    assertField(new RXE().substitutionStatus(SENTINEL), 9);
  });

  test("RXE-10 Dispense Amount", () => {
    assertField(new RXE().dispenseAmount(SENTINEL), 10);
  });

  test("RXE-11 Dispense Units", () => {
    const parts = new RXE().dispenseUnits("C1", "C2").encode().split("|");
    expect(parts[11]).toBe("C1^C2");
  });

  test("RXE-12 Number Of Refills", () => {
    assertField(new RXE().numberOfRefills(SENTINEL), 12);
  });

  test("RXE-13 Ordering Provider DEA Number", () => {
    const parts = new RXE().orderingProviderDeaNumber("C1", "C2", "C3").encode().split("|");
    expect(parts[13]).toBe("C1^C2^C3");
  });

  test("RXE-14 Pharmacist Verifier ID", () => {
    const parts = new RXE().pharmacistVerifierId("C1", "C2", "C3").encode().split("|");
    expect(parts[14]).toBe("C1^C2^C3");
  });

  test("RXE-15 Prescription Number", () => {
    assertField(new RXE().prescriptionNumber(SENTINEL), 15);
  });

  test("RXE-16 Number Of Refills Remaining", () => {
    assertField(new RXE().numberOfRefillsRemaining(SENTINEL), 16);
  });

  test("RXE-17 Number Of Refills Doses Dispensed", () => {
    assertField(new RXE().numberOfRefillsDosesDispensed(SENTINEL), 17);
  });

  test("RXE-18 Date Time Most Recent Refill Or Dose Dispensed", () => {
    assertField(new RXE().dateTimeMostRecentRefillOrDoseDispensed(SENTINEL), 18);
  });

  test("RXE-19 Total Daily Dose", () => {
    const parts = new RXE().totalDailyDose("C1", "C2").encode().split("|");
    expect(parts[19]).toBe("C1^C2");
  });

  test("RXE-20 Needs Human Review", () => {
    assertField(new RXE().needsHumanReview(SENTINEL), 20);
  });

  test("RXE-21 Special Dispensing Instructions", () => {
    const parts = new RXE().specialDispensingInstructions("C1", "C2", "C3").encode().split("|");
    expect(parts[21]).toBe("C1^C2^C3");
  });

  test("RXE-22 Give Per", () => {
    assertField(new RXE().givePer(SENTINEL), 22);
  });

  test("RXE-23 Give Rate Amount", () => {
    assertField(new RXE().giveRateAmount(SENTINEL), 23);
  });

  test("RXE-24 Give Rate Units", () => {
    const parts = new RXE().giveRateUnits("C1", "C2").encode().split("|");
    expect(parts[24]).toBe("C1^C2");
  });

  test("RXE-25 Give Strength", () => {
    assertField(new RXE().giveStrength(SENTINEL), 25);
  });

  test("RXE-26 Give Strength Units", () => {
    const parts = new RXE().giveStrengthUnits("C1", "C2").encode().split("|");
    expect(parts[26]).toBe("C1^C2");
  });

  test("RXE-27 Give Indication", () => {
    const parts = new RXE().giveIndication("C1", "C2", "C3").encode().split("|");
    expect(parts[27]).toBe("C1^C2^C3");
  });

  test("RXE-28 Dispense Package Size", () => {
    assertField(new RXE().dispensePackageSize(SENTINEL), 28);
  });

  test("RXE-29 Dispense Package Size Unit", () => {
    const parts = new RXE().dispensePackageSizeUnit("C1", "C2", "C3").encode().split("|");
    expect(parts[29]).toBe("C1^C2^C3");
  });

  test("RXE-30 Dispense Package Method", () => {
    assertField(new RXE().dispensePackageMethod(SENTINEL), 30);
  });
});
