// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the RXO segment (HL7 v2.3). `encode()`
// emits `RXO|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { RXO } from "./RXO.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: RXO, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXO field positions", () => {
  test("RXO-1 Requested Give Code", () => {
    assertField(new RXO().requestedGiveCode(SENTINEL), 1);
  });

  test("RXO-2 Requested Give Amount Min", () => {
    assertField(new RXO().requestedGiveAmountMin(SENTINEL), 2);
  });

  test("RXO-3 Requested Give Amount Max", () => {
    assertField(new RXO().requestedGiveAmountMax(SENTINEL), 3);
  });

  test("RXO-4 Requested Give Units", () => {
    assertField(new RXO().requestedGiveUnits(SENTINEL), 4);
  });

  test("RXO-5 Requested Dosage Form", () => {
    assertField(new RXO().requestedDosageForm(SENTINEL), 5);
  });

  test("RXO-6 Provider Pharmacy Instructions", () => {
    assertField(new RXO().providerPharmacyInstructions(SENTINEL), 6);
  });

  test("RXO-7 Provider Admin Instructions", () => {
    assertField(new RXO().providerAdminInstructions(SENTINEL), 7);
  });

  test("RXO-10 Requested Dispense Code", () => {
    assertField(new RXO().requestedDispenseCode(SENTINEL), 10);
  });

  test("RXO-11 Requested Dispense Amount", () => {
    assertField(new RXO().requestedDispenseAmount(SENTINEL), 11);
  });

  test("RXO-12 Requested Dispense Units", () => {
    assertField(new RXO().requestedDispenseUnits(SENTINEL), 12);
  });

  test("RXO-13 Number Of Refills", () => {
    assertField(new RXO().numberOfRefills(SENTINEL), 13);
  });

  test("RXO-14 Ordering Provider DEA Number", () => {
    assertField(new RXO().orderingProviderDeaNumber(SENTINEL), 14);
  });

  test("RXO-15 Pharmacist Verifier ID", () => {
    assertField(new RXO().pharmacistVerifierId(SENTINEL), 15);
  });

  test("RXO-16 Needs Human Review", () => {
    assertField(new RXO().needsHumanReview(SENTINEL), 16);
  });

  test("RXO-21 Requested Give Rate Amount", () => {
    assertField(new RXO().requestedGiveRateAmount(SENTINEL), 21);
  });

  test("RXO-22 Requested Give Rate Units", () => {
    assertField(new RXO().requestedGiveRateUnits(SENTINEL), 22);
  });
});
