// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXO segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXO } from "./RXO.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXO, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXO field positions", () => {
  test("RXO-1 Requested Give Code", () => {
    const parts = new RXO().requestedGiveCode("C1", "C2", "C3").encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3");
  });

  test("RXO-2 Requested Give Amount Min", () => {
    assertField(new RXO().requestedGiveAmountMin(SENTINEL), 2);
  });

  test("RXO-3 Requested Give Amount Max", () => {
    assertField(new RXO().requestedGiveAmountMax(SENTINEL), 3);
  });

  test("RXO-4 Requested Give Units", () => {
    const parts = new RXO().requestedGiveUnits("C1", "C2").encode().split("|");
    expect(parts[4]).toBe("C1^C2");
  });

  test("RXO-5 Requested Dosage Form", () => {
    const parts = new RXO().requestedDosageForm("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("RXO-6 Provider Pharmacy Instructions", () => {
    const parts = new RXO().providerPharmacyInstructions("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });

  test("RXO-7 Provider Admin Instructions", () => {
    const parts = new RXO().providerAdminInstructions("C1", "C2").encode().split("|");
    expect(parts[7]).toBe("C1^C2");
  });

  test("RXO-8 Deliver To Location", () => {
    assertField(new RXO().deliverToLocation(SENTINEL), 8);
  });

  test("RXO-9 Allow Substitutions", () => {
    assertField(new RXO().allowSubstitutions(SENTINEL), 9);
  });

  test("RXO-10 Requested Dispense Code", () => {
    const parts = new RXO().requestedDispenseCode("C1", "C2").encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("RXO-11 Requested Dispense Amount", () => {
    assertField(new RXO().requestedDispenseAmount(SENTINEL), 11);
  });

  test("RXO-12 Requested Dispense Units", () => {
    const parts = new RXO().requestedDispenseUnits("C1", "C2").encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });

  test("RXO-13 Number Of Refills", () => {
    assertField(new RXO().numberOfRefills(SENTINEL), 13);
  });

  test("RXO-14 Ordering Provider DEA Number", () => {
    const parts = new RXO().orderingProviderDeaNumber("C1", "C2", "C3").encode().split("|");
    expect(parts[14]).toBe("C1^C2^C3");
  });

  test("RXO-15 Pharmacist Verifier ID", () => {
    const parts = new RXO().pharmacistVerifierId("C1", "C2", "C3").encode().split("|");
    expect(parts[15]).toBe("C1^C2^C3");
  });

  test("RXO-16 Needs Human Review", () => {
    assertField(new RXO().needsHumanReview(SENTINEL), 16);
  });

  test("RXO-17 Requested Give Per Time Unit", () => {
    assertField(new RXO().requestedGivePerTimeUnit(SENTINEL), 17);
  });

  test("RXO-18 Requested Give Strength", () => {
    assertField(new RXO().requestedGiveStrength(SENTINEL), 18);
  });

  test("RXO-19 Requested Give Strength Units", () => {
    const parts = new RXO().requestedGiveStrengthUnits("C1", "C2", "C3").encode().split("|");
    expect(parts[19]).toBe("C1^C2^C3");
  });

  test("RXO-20 Indication", () => {
    const parts = new RXO().indication("C1", "C2", "C3").encode().split("|");
    expect(parts[20]).toBe("C1^C2^C3");
  });

  test("RXO-21 Requested Give Rate Amount", () => {
    assertField(new RXO().requestedGiveRateAmount(SENTINEL), 21);
  });

  test("RXO-22 Requested Give Rate Units", () => {
    const parts = new RXO().requestedGiveRateUnits("C1", "C2").encode().split("|");
    expect(parts[22]).toBe("C1^C2");
  });
});
