// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the RXR segment (HL7 v2.3). `encode()`
// emits `RXR|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { RXR } from "./RXR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: RXR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXR field positions", () => {
  test("RXR-1 Route", () => {
    assertField(new RXR().route(SENTINEL), 1);
  });

  test("RXR-2 Administration Site", () => {
    assertField(new RXR().administrationSite(SENTINEL), 2);
  });

  test("RXR-3 Administration Device", () => {
    assertField(new RXR().administrationDevice(SENTINEL), 3);
  });

  test("RXR-4 Administration Method", () => {
    assertField(new RXR().administrationMethod(SENTINEL), 4);
  });

  test("RXR-5 Routing Instruction", () => {
    assertField(new RXR().routingInstruction(SENTINEL), 5);
  });

  test("RXR-6 Administration Site Modifier", () => {
    assertField(new RXR().administrationSiteModifier(SENTINEL), 6);
  });
});
