// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXR segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXR } from "./RXR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXR field positions", () => {
  test("RXR-1 Route", () => {
    const parts = new RXR().route("C1", "C2", "C3").encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3");
  });

  test("RXR-2 Administration Site", () => {
    const parts = new RXR().administrationSite("C1", "C2").encode().split("|");
    expect(parts[2]).toBe("C1^C2");
  });

  test("RXR-3 Administration Device", () => {
    const parts = new RXR().administrationDevice("C1", "C2").encode().split("|");
    expect(parts[3]).toBe("C1^C2");
  });

  test("RXR-4 Administration Method", () => {
    const parts = new RXR().administrationMethod("C1", "C2").encode().split("|");
    expect(parts[4]).toBe("C1^C2");
  });

  test("RXR-5 Routing Instruction", () => {
    const parts = new RXR().routingInstruction("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("RXR-6 Administration Site Modifier", () => {
    const parts = new RXR().administrationSiteModifier("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });
});
