// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the SCH segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { SCH } from "./SCH.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: SCH, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("SCH field positions", () => {
  test("SCH-1 Placer Appointment ID", () => {
    const parts = new SCH().placerAppointmentId("C1", "C2").encode().split("|");
    expect(parts[1]).toBe("C1^C2");
  });

  test("SCH-2 Filler Appointment ID", () => {
    const parts = new SCH().fillerAppointmentId("C1", "C2").encode().split("|");
    expect(parts[2]).toBe("C1^C2");
  });

  test("SCH-3 Occurrence Number", () => {
    assertField(new SCH().occurrenceNumber(SENTINEL), 3);
  });

  test("SCH-4 Placer Group Number", () => {
    const parts = new SCH().placerGroupNumber("C1", "C2").encode().split("|");
    expect(parts[4]).toBe("C1^C2");
  });

  test("SCH-5 Schedule ID", () => {
    const parts = new SCH().scheduleId("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("SCH-6 Event Reason", () => {
    const parts = new SCH().eventReason("C1", "C2", "C3").encode().split("|");
    expect(parts[6]).toBe("C1^C2^C3");
  });

  test("SCH-7 Appointment Reason", () => {
    const parts = new SCH().appointmentReason("C1", "C2", "C3").encode().split("|");
    expect(parts[7]).toBe("C1^C2^C3");
  });

  test("SCH-8 Appointment Type", () => {
    const parts = new SCH().appointmentType("C1", "C2").encode().split("|");
    expect(parts[8]).toBe("C1^C2");
  });

  test("SCH-9 Appointment Duration", () => {
    assertField(new SCH().appointmentDuration(SENTINEL), 9);
  });

  test("SCH-10 Appointment Duration Units", () => {
    const parts = new SCH().appointmentDurationUnits("C1", "C2").encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("SCH-11 Appointment Timing Quantity", () => {
    assertField(new SCH().appointmentTimingQuantity(SENTINEL), 11);
  });

  test("SCH-12 Placer Contact Person", () => {
    const parts = new SCH().placerContactPerson("C1", "C2", "C3").encode().split("|");
    expect(parts[12]).toBe("C1^C2^C3");
  });

  test("SCH-13 Placer Contact Phone Number", () => {
    assertField(new SCH().placerContactPhoneNumber(SENTINEL), 13);
  });

  test("SCH-14 Placer Contact Address", () => {
    const parts = new SCH().placerContactAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[14]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("SCH-15 Placer Contact Location", () => {
    const parts = new SCH().placerContactLocation("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[15]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("SCH-16 Filler Contact Person", () => {
    const parts = new SCH().fillerContactPerson("C1", "C2", "C3").encode().split("|");
    expect(parts[16]).toBe("C1^C2^C3");
  });

  test("SCH-17 Filler Contact Phone Number", () => {
    assertField(new SCH().fillerContactPhoneNumber(SENTINEL), 17);
  });

  test("SCH-18 Filler Contact Address", () => {
    const parts = new SCH().fillerContactAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[18]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("SCH-19 Filler Contact Location", () => {
    const parts = new SCH().fillerContactLocation("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[19]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("SCH-20 Entered By Person", () => {
    const parts = new SCH().enteredByPerson("C1", "C2", "C3").encode().split("|");
    expect(parts[20]).toBe("C1^C2^C3");
  });

  test("SCH-21 Entered By Phone Number", () => {
    assertField(new SCH().enteredByPhoneNumber(SENTINEL), 21);
  });

  test("SCH-22 Entered By Location", () => {
    const parts = new SCH().enteredByLocation("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[22]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("SCH-23 Parent Placer Appointment ID", () => {
    const parts = new SCH().parentPlacerAppointmentId("C1", "C2").encode().split("|");
    expect(parts[23]).toBe("C1^C2");
  });

  test("SCH-24 Parent Filler Appointment ID", () => {
    const parts = new SCH().parentFillerAppointmentId("C1", "C2").encode().split("|");
    expect(parts[24]).toBe("C1^C2");
  });

  test("SCH-25 Filler Status Code", () => {
    const parts = new SCH().fillerStatusCode("C1", "C2").encode().split("|");
    expect(parts[25]).toBe("C1^C2");
  });
});
