// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the SCH segment (HL7 v2.3). `encode()`
// emits `SCH|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { SCH } from "./SCH.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: SCH, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("SCH field positions", () => {
  test("SCH-1 Placer Appointment ID", () => {
    assertField(new SCH().placerAppointmentId(SENTINEL), 1);
  });

  test("SCH-2 Filler Appointment ID", () => {
    assertField(new SCH().fillerAppointmentId(SENTINEL), 2);
  });

  test("SCH-3 Occurrence Number", () => {
    assertField(new SCH().occurrenceNumber(SENTINEL), 3);
  });

  test("SCH-5 Schedule ID", () => {
    assertField(new SCH().scheduleId(SENTINEL), 5);
  });

  test("SCH-6 Event Reason", () => {
    assertField(new SCH().eventReason(SENTINEL), 6);
  });

  test("SCH-7 Appointment Reason", () => {
    assertField(new SCH().appointmentReason(SENTINEL), 7);
  });

  test("SCH-8 Appointment Type", () => {
    assertField(new SCH().appointmentType(SENTINEL), 8);
  });

  test("SCH-9 Appointment Duration", () => {
    assertField(new SCH().appointmentDuration(SENTINEL), 9);
  });

  test("SCH-10 Appointment Duration Units", () => {
    assertField(new SCH().appointmentDurationUnits(SENTINEL), 10);
  });

  test("SCH-11 Appointment Timing Quantity", () => {
    assertField(new SCH().appointmentTimingQuantity(SENTINEL), 11);
  });

  test("SCH-12 Placer Contact Person", () => {
    assertField(new SCH().placerContactPerson(SENTINEL), 12);
  });

  test("SCH-16 Filler Contact Person", () => {
    assertField(new SCH().fillerContactPerson(SENTINEL), 16);
  });

  test("SCH-20 Entered By Person", () => {
    assertField(new SCH().enteredByPerson(SENTINEL), 20);
  });

  test("SCH-25 Filler Status Code", () => {
    assertField(new SCH().fillerStatusCode(SENTINEL), 25);
  });
});
