// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the SFT segment (HL7 v2.3). `encode()`
// emits `SFT|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { SFT } from "./SFT.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: SFT, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("SFT field positions", () => {
  test("SFT-1 Software Vendor Organization", () => {
    assertField(new SFT().softwareVendorOrganization(SENTINEL), 1);
  });

  test("SFT-2 Software Version", () => {
    assertField(new SFT().softwareVersion(SENTINEL), 2);
  });

  test("SFT-3 Software Product Name", () => {
    assertField(new SFT().softwareProductName(SENTINEL), 3);
  });

  test("SFT-4 Software Binary ID", () => {
    assertField(new SFT().softwareBinaryId(SENTINEL), 4);
  });

  test("SFT-5 Software Product Info", () => {
    assertField(new SFT().softwareProductInfo(SENTINEL), 5);
  });

  test("SFT-6 Software Install Date", () => {
    assertField(new SFT().softwareInstallDate(SENTINEL), 6);
  });
});
