// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the SPM segment (HL7 v2.3). `encode()`
// emits `SPM|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { SPM } from "./SPM.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: SPM, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("SPM field positions", () => {
  test("SPM-1 Set ID", () => {
    assertField(new SPM().setId(SENTINEL), 1);
  });

  test("SPM-2 Specimen ID", () => {
    assertField(new SPM().specimenId(SENTINEL), 2);
  });

  test("SPM-3 Specimen Parent Ids", () => {
    assertField(new SPM().specimenParentIds(SENTINEL), 3);
  });

  test("SPM-4 Specimen Type", () => {
    assertField(new SPM().specimenType(SENTINEL), 4);
  });

  test("SPM-5 Specimen Type Modifier", () => {
    assertField(new SPM().specimenTypeModifier(SENTINEL), 5);
  });

  test("SPM-6 Specimen Additives", () => {
    assertField(new SPM().specimenAdditives(SENTINEL), 6);
  });

  test("SPM-7 Specimen Collection Method", () => {
    assertField(new SPM().specimenCollectionMethod(SENTINEL), 7);
  });

  test("SPM-8 Specimen Source Site", () => {
    assertField(new SPM().specimenSourceSite(SENTINEL), 8);
  });

  test("SPM-9 Specimen Source Site Modifier", () => {
    assertField(new SPM().specimenSourceSiteModifier(SENTINEL), 9);
  });

  test("SPM-10 Specimen Collection Site", () => {
    assertField(new SPM().specimenCollectionSite(SENTINEL), 10);
  });

  test("SPM-11 Specimen Role", () => {
    assertField(new SPM().specimenRole(SENTINEL), 11);
  });

  test("SPM-12 Specimen Collection Amount", () => {
    assertField(new SPM().specimenCollectionAmount(SENTINEL), 12);
  });

  test("SPM-13 Grouped Specimen Count", () => {
    assertField(new SPM().groupedSpecimenCount(SENTINEL), 13);
  });

  test("SPM-14 Specimen Description", () => {
    assertField(new SPM().specimenDescription(SENTINEL), 14);
  });

  test("SPM-17 Specimen Collection Date Time", () => {
    assertField(new SPM().specimenCollectionDateTime(SENTINEL), 17);
  });

  test("SPM-18 Specimen Received Date Time", () => {
    assertField(new SPM().specimenReceivedDateTime(SENTINEL), 18);
  });

  test("SPM-20 Specimen Availability", () => {
    assertField(new SPM().specimenAvailability(SENTINEL), 20);
  });

  test("SPM-25 Specimen Current Quantity", () => {
    assertField(new SPM().specimenCurrentQuantity(SENTINEL), 25);
  });

  test("SPM-24 Specimen Condition", () => {
    assertField(new SPM().specimenCondition(SENTINEL), 24);
  });

  test("SPM-21 Specimen Reject Reason", () => {
    assertField(new SPM().specimenRejectReason(SENTINEL), 21);
  });
});
