// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the SPM segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { SPM } from "./SPM.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: SPM, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("SPM field positions", () => {
  test("SPM-1 Set ID", () => {
    assertField(new SPM().setId(SENTINEL), 1);
  });

  test("SPM-2 Specimen ID", () => {
    const parts = new SPM().specimenId("C1", "C2").encode().split("|");
    expect(parts[2]).toBe("C1^C2");
  });

  test("SPM-3 Specimen Parent Ids", () => {
    assertField(new SPM().specimenParentIds(SENTINEL), 3);
  });

  test("SPM-4 Specimen Type", () => {
    const parts = new SPM().specimenType("C1", "C2", "C3").encode().split("|");
    expect(parts[4]).toBe("C1^C2^C3");
  });

  test("SPM-5 Specimen Type Modifier", () => {
    const parts = new SPM().specimenTypeModifier("C1", "C2").encode().split("|");
    expect(parts[5]).toBe("C1^C2");
  });

  test("SPM-6 Specimen Additives", () => {
    const parts = new SPM().specimenAdditives("C1", "C2").encode().split("|");
    expect(parts[6]).toBe("C1^C2");
  });

  test("SPM-7 Specimen Collection Method", () => {
    const parts = new SPM().specimenCollectionMethod("C1", "C2").encode().split("|");
    expect(parts[7]).toBe("C1^C2");
  });

  test("SPM-8 Specimen Source Site", () => {
    const parts = new SPM().specimenSourceSite("C1", "C2", "C3").encode().split("|");
    expect(parts[8]).toBe("C1^C2^C3");
  });

  test("SPM-9 Specimen Source Site Modifier", () => {
    const parts = new SPM().specimenSourceSiteModifier("C1", "C2").encode().split("|");
    expect(parts[9]).toBe("C1^C2");
  });

  test("SPM-10 Specimen Collection Site", () => {
    const parts = new SPM().specimenCollectionSite("C1", "C2").encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("SPM-11 Specimen Role", () => {
    const parts = new SPM().specimenRole("C1", "C2").encode().split("|");
    expect(parts[11]).toBe("C1^C2");
  });

  test("SPM-12 Specimen Collection Amount", () => {
    const parts = new SPM().specimenCollectionAmount("C1", "C2").encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });

  test("SPM-13 Grouped Specimen Count", () => {
    assertField(new SPM().groupedSpecimenCount(SENTINEL), 13);
  });

  test("SPM-14 Specimen Description", () => {
    assertField(new SPM().specimenDescription(SENTINEL), 14);
  });

  test("SPM-17 Specimen Collection Date Time", () => {
    const parts = new SPM().specimenCollectionDateTime("C1", "C2").encode().split("|");
    expect(parts[17]).toBe("C1^C2");
  });

  test("SPM-18 Specimen Received Date Time", () => {
    assertField(new SPM().specimenReceivedDateTime(SENTINEL), 18);
  });

  test("SPM-20 Specimen Availability", () => {
    assertField(new SPM().specimenAvailability(SENTINEL), 20);
  });

  test("SPM-25 Specimen Current Quantity", () => {
    const parts = new SPM().specimenCurrentQuantity("C1", "C2").encode().split("|");
    expect(parts[25]).toBe("C1^C2");
  });

  test("SPM-24 Specimen Condition", () => {
    const parts = new SPM().specimenCondition("C1", "C2").encode().split("|");
    expect(parts[24]).toBe("C1^C2");
  });

  test("SPM-21 Specimen Reject Reason", () => {
    const parts = new SPM().specimenRejectReason("C1", "C2").encode().split("|");
    expect(parts[21]).toBe("C1^C2");
  });

  test("SPM-15 Specimen Handling Code", () => {
    const parts = new SPM().specimenHandlingCode("C1", "C2", "C3").encode().split("|");
    expect(parts[15]).toBe("C1^C2^C3");
  });

  test("SPM-16 Specimen Risk Code", () => {
    const parts = new SPM().specimenRiskCode("C1", "C2", "C3").encode().split("|");
    expect(parts[16]).toBe("C1^C2^C3");
  });

  test("SPM-19 Specimen Expiration Date Time", () => {
    assertField(new SPM().specimenExpirationDateTime(SENTINEL), 19);
  });

  test("SPM-22 Specimen Quality", () => {
    const parts = new SPM().specimenQuality("C1", "C2", "C3").encode().split("|");
    expect(parts[22]).toBe("C1^C2^C3");
  });

  test("SPM-23 Specimen Appropriateness", () => {
    const parts = new SPM().specimenAppropriateness("C1", "C2", "C3").encode().split("|");
    expect(parts[23]).toBe("C1^C2^C3");
  });

  test("SPM-26 Number Of Specimen Containers", () => {
    assertField(new SPM().numberOfSpecimenContainers(SENTINEL), 26);
  });

  test("SPM-27 Container Type", () => {
    const parts = new SPM().containerType("C1", "C2", "C3").encode().split("|");
    expect(parts[27]).toBe("C1^C2^C3");
  });

  test("SPM-28 Container Condition", () => {
    const parts = new SPM().containerCondition("C1", "C2", "C3").encode().split("|");
    expect(parts[28]).toBe("C1^C2^C3");
  });

  test("SPM-29 Specimen Child Role", () => {
    const parts = new SPM().specimenChildRole("C1", "C2", "C3").encode().split("|");
    expect(parts[29]).toBe("C1^C2^C3");
  });
});
