// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the STF segment (HL7 v2.3). `encode()`
// emits `STF|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { STF } from "./STF.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: STF, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("STF field positions", () => {
  test("STF-1 Primary Key Value", () => {
    assertField(new STF().primaryKeyValue(SENTINEL), 1);
  });

  test("STF-2 Staff Identifier List", () => {
    assertField(new STF().staffIdentifierList(SENTINEL), 2);
  });

  test("STF-4 Staff Type", () => {
    assertField(new STF().staffType(SENTINEL), 4);
  });

  test("STF-5 Administrative Sex", () => {
    assertField(new STF().administrativeSex(SENTINEL), 5);
  });

  test("STF-6 Date Time Of Birth", () => {
    assertField(new STF().dateTimeOfBirth(SENTINEL), 6);
  });

  test("STF-7 Active Inactive Flag", () => {
    assertField(new STF().activeInactiveFlag(SENTINEL), 7);
  });

  test("STF-8 Department", () => {
    assertField(new STF().department(SENTINEL), 8);
  });

  test("STF-9 Hospital Service", () => {
    assertField(new STF().hospitalService(SENTINEL), 9);
  });

  test("STF-10 Phone", () => {
    assertField(new STF().phone(SENTINEL), 10);
  });

  test("STF-11 Address", () => {
    assertField(new STF().address(SENTINEL), 11);
  });

  test("STF-15 Email Address", () => {
    assertField(new STF().emailAddress(SENTINEL), 15);
  });

  test("STF-18 Job Title", () => {
    assertField(new STF().jobTitle(SENTINEL), 18);
  });
});
