// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the STF segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { STF } from "./STF.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: STF, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("STF field positions", () => {
  test("STF-1 Primary Key Value", () => {
    const parts = new STF().primaryKeyValue({ identifier: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[1]).toBe("C1^C2^C3");
  });

  test("STF-2 Staff Identifier List", () => {
    assertField(new STF().staffIdentifierList(SENTINEL), 2);
  });

  test("STF-3 Staff Name", () => {
    assertField(new STF().staffName({ familyName: SENTINEL, givenName: "", middleName: "", suffix: "", prefix: "" }), 3);
  });

  test("STF-4 Staff Type", () => {
    assertField(new STF().staffType(SENTINEL), 4);
  });

  test("STF-5 Administrative Sex", () => {
    assertField(new STF().administrativeSex(SENTINEL), 5);
  });

  test("STF-6 Date Time Of Birth", () => {
    assertField(new STF().dateTimeOfBirth(SENTINEL), 6);
  });

  test("STF-7 Active Inactive Flag", () => {
    assertField(new STF().activeInactiveFlag(SENTINEL), 7);
  });

  test("STF-8 Department", () => {
    const parts = new STF().department({ identifier: "C1", text: "C2" }).encode().split("|");
    expect(parts[8]).toBe("C1^C2");
  });

  test("STF-9 Hospital Service", () => {
    const parts = new STF().hospitalService({ identifier: "C1", text: "C2" }).encode().split("|");
    expect(parts[9]).toBe("C1^C2");
  });

  test("STF-10 Phone", () => {
    assertField(new STF().phone(SENTINEL), 10);
  });

  test("STF-11 Address", () => {
    assertField(new STF().address(SENTINEL), 11);
  });

  test("STF-12 Institution Activation Date", () => {
    const parts = new STF().institutionActivationDate({ date: "C1", institutionName: "C2" }).encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });

  test("STF-13 Institution Inactivation Date", () => {
    const parts = new STF().institutionInactivationDate({ date: "C1", institutionName: "C2" }).encode().split("|");
    expect(parts[13]).toBe("C1^C2");
  });

  test("STF-14 Backup Person ID", () => {
    const parts = new STF().backupPersonId({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[14]).toBe("C1^C2^C3");
  });

  test("STF-15 Email Address", () => {
    assertField(new STF().emailAddress(SENTINEL), 15);
  });

  test("STF-16 Preferred Method Of Contact", () => {
    const parts = new STF().preferredMethodOfContact({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[16]).toBe("C1^C2^C3");
  });

  test("STF-17 Marital Status", () => {
    const parts = new STF().maritalStatus({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[17]).toBe("C1^C2^C3");
  });

  test("STF-18 Job Title", () => {
    assertField(new STF().jobTitle(SENTINEL), 18);
  });

  test("STF-19 Job Code Class", () => {
    const parts = new STF().jobCodeClass({ jobCode: "C1", jobClass: "C2" }).encode().split("|");
    expect(parts[19]).toBe("C1^C2");
  });

  test("STF-20 Employment Status Code", () => {
    const parts = new STF().employmentStatusCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[20]).toBe("C1^C2^C3");
  });

  test("STF-21 Additional Insured On Auto", () => {
    assertField(new STF().additionalInsuredOnAuto(SENTINEL), 21);
  });

  test("STF-22 Drivers License Number", () => {
    const parts = new STF().driversLicenseNumber({ licenseNumber: "C1", issuingAuthority: "C2", expirationDate: "C3" }).encode().split("|");
    expect(parts[22]).toBe("C1^C2^C3");
  });

  test("STF-23 Copy Auto Ins", () => {
    assertField(new STF().copyAutoIns(SENTINEL), 23);
  });

  test("STF-24 Auto Ins Expires", () => {
    assertField(new STF().autoInsExpires(SENTINEL), 24);
  });

  test("STF-25 Date Last DMV Review", () => {
    assertField(new STF().dateLastDmvReview(SENTINEL), 25);
  });

  test("STF-26 Date Next DMV Review", () => {
    assertField(new STF().dateNextDmvReview(SENTINEL), 26);
  });
});
