// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the TQ1 segment (HL7 v2.3). `encode()`
// emits `TQ1|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { TQ1 } from "./TQ1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: TQ1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("TQ1 field positions", () => {
  test("TQ1-1 Set ID", () => {
    assertField(new TQ1().setId(SENTINEL), 1);
  });

  test("TQ1-2 Quantity", () => {
    assertField(new TQ1().quantity(SENTINEL), 2);
  });

  test("TQ1-3 Repeat Pattern", () => {
    assertField(new TQ1().repeatPattern(SENTINEL), 3);
  });

  test("TQ1-4 Explicit Time", () => {
    assertField(new TQ1().explicitTime(SENTINEL), 4);
  });

  test("TQ1-5 Relative Time", () => {
    assertField(new TQ1().relativeTime(SENTINEL), 5);
  });

  test("TQ1-6 Service Duration", () => {
    assertField(new TQ1().serviceDuration(SENTINEL), 6);
  });

  test("TQ1-7 Start Date Time", () => {
    assertField(new TQ1().startDateTime(SENTINEL), 7);
  });

  test("TQ1-8 End Date Time", () => {
    assertField(new TQ1().endDateTime(SENTINEL), 8);
  });

  test("TQ1-9 Priority", () => {
    assertField(new TQ1().priority(SENTINEL), 9);
  });

  test("TQ1-10 Condition Text", () => {
    assertField(new TQ1().conditionText(SENTINEL), 10);
  });

  test("TQ1-11 Text Instruction", () => {
    assertField(new TQ1().textInstruction(SENTINEL), 11);
  });

  test("TQ1-12 Conjunction", () => {
    assertField(new TQ1().conjunction(SENTINEL), 12);
  });

  test("TQ1-13 Occurrence Duration", () => {
    assertField(new TQ1().occurrenceDuration(SENTINEL), 13);
  });

  test("TQ1-14 Total Occurrences", () => {
    assertField(new TQ1().totalOccurrences(SENTINEL), 14);
  });
});
