// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the UB1 segment (HL7 v2.3). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { UB1 } from "./UB1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: UB1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("UB1 field positions", () => {
  test("UB1-1 Set ID", () => {
    assertField(new UB1().setId(SENTINEL), 1);
  });

  test("UB1-2 Blood Deductible", () => {
    assertField(new UB1().bloodDeductible(SENTINEL), 2);
  });

  test("UB1-3 Blood Furnished Pints", () => {
    assertField(new UB1().bloodFurnishedPints(SENTINEL), 3);
  });

  test("UB1-4 Blood Replaced Pints", () => {
    assertField(new UB1().bloodReplacedPints(SENTINEL), 4);
  });

  test("UB1-5 Blood Not Replaced Pints", () => {
    assertField(new UB1().bloodNotReplacedPints(SENTINEL), 5);
  });

  test("UB1-6 Co Insurance Days", () => {
    assertField(new UB1().coInsuranceDays(SENTINEL), 6);
  });

  test("UB1-7 Condition Code", () => {
    assertField(new UB1().conditionCode(SENTINEL), 7);
  });

  test("UB1-8 Covered Days", () => {
    assertField(new UB1().coveredDays(SENTINEL), 8);
  });

  test("UB1-9 Non Covered Days", () => {
    assertField(new UB1().nonCoveredDays(SENTINEL), 9);
  });

  test("UB1-10 Value Amount Code", () => {
    const parts = new UB1().valueAmountCode({ code: "C1", amount: "C2" }).encode().split("|");
    expect(parts[10]).toBe("C1^C2");
  });

  test("UB1-11 Number Of Grace Days", () => {
    assertField(new UB1().numberOfGraceDays(SENTINEL), 11);
  });

  test("UB1-12 Special Program Indicator", () => {
    const parts = new UB1().specialProgramIndicator({ code: "C1", text: "C2" }).encode().split("|");
    expect(parts[12]).toBe("C1^C2");
  });

  test("UB1-13 Psro Ur Approval Indicator", () => {
    assertField(new UB1().psroUrApprovalIndicator(SENTINEL), 13);
  });

  test("UB1-14 Psro Ur Approved Stay From", () => {
    assertField(new UB1().psroUrApprovedStayFrom(SENTINEL), 14);
  });

  test("UB1-15 Psro Ur Approved Stay To", () => {
    assertField(new UB1().psroUrApprovedStayTo(SENTINEL), 15);
  });

  test("UB1-16 Occurrence", () => {
    assertField(new UB1().occurrence(SENTINEL), 16);
  });

  test("UB1-17 Occurrence Span", () => {
    assertField(new UB1().occurrenceSpan(SENTINEL), 17);
  });

  test("UB1-18 Occur Span Start Date", () => {
    assertField(new UB1().occurSpanStartDate(SENTINEL), 18);
  });

  test("UB1-19 Occur Span End Date", () => {
    assertField(new UB1().occurSpanEndDate(SENTINEL), 19);
  });

  test("UB1-20 UB82 Locator2", () => {
    assertField(new UB1().ub82Locator2(SENTINEL), 20);
  });

  test("UB1-21 UB82 Locator9", () => {
    assertField(new UB1().ub82Locator9(SENTINEL), 21);
  });

  test("UB1-22 UB82 Locator27", () => {
    assertField(new UB1().ub82Locator27(SENTINEL), 22);
  });

  test("UB1-23 UB82 Locator45", () => {
    assertField(new UB1().ub82Locator45(SENTINEL), 23);
  });
});
