// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: pnpm test:positions
//
// Field-position tests for the UB2 segment (HL7 v2.3). `encode()`
// emits `UB2|<field1>|<field2>|...`, so after splitting on the field
// separator the value written by a setter lands at a fixed index. Asserting
// the exact index — not just substring presence — is what catches off-by-one
// field-placement bugs.
import { test, expect, describe } from "vitest";
import { UB2 } from "./UB2.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component,
// first subcomponent) and nowhere else.
function assertField(seg: UB2, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("UB2 field positions", () => {
  test("UB2-1 Set ID", () => {
    assertField(new UB2().setId(SENTINEL), 1);
  });

  test("UB2-2 Co Insurance Days", () => {
    assertField(new UB2().coInsuranceDays(SENTINEL), 2);
  });

  test("UB2-3 Condition Code", () => {
    assertField(new UB2().conditionCode(SENTINEL), 3);
  });

  test("UB2-4 Covered Days", () => {
    assertField(new UB2().coveredDays(SENTINEL), 4);
  });

  test("UB2-5 Non Covered Days", () => {
    assertField(new UB2().nonCoveredDays(SENTINEL), 5);
  });

  test("UB2-6 Value Amount Code", () => {
    assertField(new UB2().valueAmountCode(SENTINEL), 6);
  });

  test("UB2-7 Occurrence Code Date", () => {
    assertField(new UB2().occurrenceCodeDate(SENTINEL), 7);
  });

  test("UB2-8 Occurrence Span Code Dates", () => {
    assertField(new UB2().occurrenceSpanCodeDates(SENTINEL), 8);
  });

  test("UB2-9 UB92 Locator2", () => {
    assertField(new UB2().ub92Locator2(SENTINEL), 9);
  });

  test("UB2-10 UB92 Locator11", () => {
    assertField(new UB2().ub92Locator11(SENTINEL), 10);
  });

  test("UB2-11 UB92 Locator31", () => {
    assertField(new UB2().ub92Locator31(SENTINEL), 11);
  });

  test("UB2-12 Document Control Number", () => {
    assertField(new UB2().documentControlNumber(SENTINEL), 12);
  });

  test("UB2-13 UB92 Locator49", () => {
    assertField(new UB2().ub92Locator49(SENTINEL), 13);
  });

  test("UB2-14 UB92 Locator56", () => {
    assertField(new UB2().ub92Locator56(SENTINEL), 14);
  });

  test("UB2-15 UB92 Locator57", () => {
    assertField(new UB2().ub92Locator57(SENTINEL), 15);
  });

  test("UB2-16 UB92 Locator78", () => {
    assertField(new UB2().ub92Locator78(SENTINEL), 16);
  });

  test("UB2-17 Special Visit Count", () => {
    assertField(new UB2().specialVisitCount(SENTINEL), 17);
  });
});
