// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the DG1 segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { DG1 } from "./DG1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: DG1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("DG1 field positions", () => {
  test("DG1-20 Diagnosis Identifier", () => {
    const parts = new DG1().diagnosisIdentifier({ entityIdentifier: "C1", namespaceId: "C2" }).encode().split("|");
    expect(parts[20]).toBe("C1^C2");
  });

  test("DG1-21 Diagnosis Action Code", () => {
    assertField(new DG1().diagnosisActionCode(SENTINEL), 21);
  });
});
