// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the ERR segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { ERR } from "./ERR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: ERR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("ERR field positions", () => {
  test("ERR-10 Override Type", () => {
    const parts = new ERR().overrideType("C1", "C2", "C3").encode().split("|");
    expect(parts[10]).toBe("C1^C2^C3");
  });

  test("ERR-11 Override Reason Code", () => {
    const parts = new ERR().overrideReasonCode("C1", "C2", "C3").encode().split("|");
    expect(parts[11]).toBe("C1^C2^C3");
  });

  test("ERR-12 Help Desk Contact Point", () => {
    assertField(new ERR().helpDeskContactPoint(SENTINEL), 12);
  });
});
