// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the IN1 segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { IN1 } from "./IN1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: IN1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("IN1 field positions", () => {
  test("IN1-50 Signature Code", () => {
    assertField(new IN1().signatureCode(SENTINEL), 50);
  });

  test("IN1-51 Signature Code Date", () => {
    assertField(new IN1().signatureCodeDate(SENTINEL), 51);
  });

  test("IN1-52 Insured Birth Place", () => {
    assertField(new IN1().insuredBirthPlace(SENTINEL), 52);
  });

  test("IN1-53 VIP Indicator", () => {
    assertField(new IN1().vipIndicator(SENTINEL), 53);
  });
});
