// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the MSH segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.//
// NOTE: MSH-1 (field separator) and MSH-2 (encoding characters) occupy the
// start of the encoded segment, so an MSH-N value sits at split index N-1.
// The index used below is the split index, not the HL7 field number.
import { test, expect, describe } from "vitest";
import { MSH } from "./MSH.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: MSH, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("MSH field positions", () => {
  test("MSH-20 Alternate Character Set Handling Scheme", () => {
    assertField(new MSH().alternateCharacterSetHandlingScheme(SENTINEL), 19);
  });

  test("MSH-21 Message Profile Identifier", () => {
    const parts = new MSH().messageProfileIdentifier({ entityIdentifier: "C1", namespaceId: "C2" }).encode().split("|");
    expect(parts[20]).toBe("C1^C2");
  });
});
