// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the OBR segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { OBR } from "./OBR.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: OBR, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("OBR field positions", () => {
  test("OBR-44 Procedure Code", () => {
    const parts = new OBR().procedureCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[44]).toBe("C1^C2^C3");
  });

  test("OBR-45 Procedure Code Modifier", () => {
    const parts = new OBR().procedureCodeModifier({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[45]).toBe("C1^C2^C3");
  });

  test("OBR-46 Placer Supplemental Service Information", () => {
    const parts = new OBR().placerSupplementalServiceInformation({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[46]).toBe("C1^C2^C3");
  });

  test("OBR-47 Filler Supplemental Service Information", () => {
    const parts = new OBR().fillerSupplementalServiceInformation({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[47]).toBe("C1^C2^C3");
  });

  test("OBR-48 Medically Necessary Duplicate Procedure Reason", () => {
    const parts = new OBR().medicallyNecessaryDuplicateProcedureReason({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[48]).toBe("C1^C2^C3");
  });

  test("OBR-49 Result Handling", () => {
    assertField(new OBR().resultHandling(SENTINEL), 49);
  });

  test("OBR-50 Parent Universal Service Identifier", () => {
    const parts = new OBR().parentUniversalServiceIdentifier({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[50]).toBe("C1^C2^C3");
  });
});
