// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the OBX segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { OBX } from "./OBX.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: OBX, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("OBX field positions", () => {
  test("OBX-18 Equipment Instance Identifier", () => {
    const parts = new OBX().equipmentInstanceIdentifier("C1", "C2").encode().split("|");
    expect(parts[18]).toBe("C1^C2");
  });

  test("OBX-19 Date Time Of The Analysis", () => {
    assertField(new OBX().dateTimeOfTheAnalysis(SENTINEL), 19);
  });

  test("OBX-23 Performing Organization Name", () => {
    assertField(new OBX().performingOrganizationName(SENTINEL), 23);
  });

  test("OBX-24 Performing Organization Address", () => {
    const parts = new OBX().performingOrganizationAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[24]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("OBX-25 Performing Organization Medical Director", () => {
    const parts = new OBX().performingOrganizationMedicalDirector("C1", "C2", "C3").encode().split("|");
    expect(parts[25]).toBe("C1^C2^C3");
  });
});
