// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the PID segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { PID } from "./PID.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: PID, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PID field positions", () => {
  test("PID-31 Identity Unknown Indicator", () => {
    assertField(new PID().identityUnknownIndicator(SENTINEL), 31);
  });

  test("PID-32 Identity Reliability Code", () => {
    assertField(new PID().identityReliabilityCode(SENTINEL), 32);
  });

  test("PID-33 Last Update Date Time", () => {
    assertField(new PID().lastUpdateDateTime(SENTINEL), 33);
  });

  test("PID-34 Last Update Facility", () => {
    assertField(new PID().lastUpdateFacility(SENTINEL), 34);
  });

  test("PID-35 Species Code", () => {
    const parts = new PID().speciesCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[35]).toBe("C1^C2^C3");
  });

  test("PID-36 Breed Code", () => {
    const parts = new PID().breedCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[36]).toBe("C1^C2^C3");
  });

  test("PID-37 Strain", () => {
    assertField(new PID().strain(SENTINEL), 37);
  });

  test("PID-38 Production Class Code", () => {
    const parts = new PID().productionClassCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[38]).toBe("C1^C2^C3");
  });

  test("PID-39 Tribal Citizenship", () => {
    const parts = new PID().tribalCitizenship({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[39]).toBe("C1^C2^C3");
  });
});
