// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the PR1 segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { PR1 } from "./PR1.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: PR1, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PR1 field positions", () => {
  test("PR1-16 Procedure Code Modifier", () => {
    const parts = new PR1().procedureCodeModifier("C1", "C2", "C3").encode().split("|");
    expect(parts[16]).toBe("C1^C2^C3");
  });

  test("PR1-17 Procedure Drg Type", () => {
    assertField(new PR1().procedureDrgType(SENTINEL), 17);
  });

  test("PR1-18 Tissue Type Code", () => {
    const parts = new PR1().tissueTypeCode("C1", "C2", "C3").encode().split("|");
    expect(parts[18]).toBe("C1^C2^C3");
  });

  test("PR1-19 Procedure Identifier", () => {
    const parts = new PR1().procedureIdentifier("C1", "C2").encode().split("|");
    expect(parts[19]).toBe("C1^C2");
  });

  test("PR1-20 Procedure Action Code", () => {
    assertField(new PR1().procedureActionCode(SENTINEL), 20);
  });
});
