// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the PV2 segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { PV2 } from "./PV2.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: PV2, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("PV2 field positions", () => {
  test("PV2-39 Recreational Drug Use Code", () => {
    const parts = new PV2().recreationalDrugUseCode("C1", "C2", "C3").encode().split("|");
    expect(parts[39]).toBe("C1^C2^C3");
  });

  test("PV2-40 Admission Level Of Care Code", () => {
    const parts = new PV2().admissionLevelOfCareCode("C1", "C2", "C3").encode().split("|");
    expect(parts[40]).toBe("C1^C2^C3");
  });

  test("PV2-41 Precaution Code", () => {
    const parts = new PV2().precautionCode("C1", "C2", "C3").encode().split("|");
    expect(parts[41]).toBe("C1^C2^C3");
  });

  test("PV2-42 Patient Condition Code", () => {
    const parts = new PV2().patientConditionCode("C1", "C2", "C3").encode().split("|");
    expect(parts[42]).toBe("C1^C2^C3");
  });

  test("PV2-43 Living Will Code", () => {
    assertField(new PV2().livingWillCode(SENTINEL), 43);
  });

  test("PV2-44 Organ Donor Code", () => {
    assertField(new PV2().organDonorCode(SENTINEL), 44);
  });

  test("PV2-45 Advance Directive Code", () => {
    const parts = new PV2().advanceDirectiveCode("C1", "C2", "C3").encode().split("|");
    expect(parts[45]).toBe("C1^C2^C3");
  });

  test("PV2-46 Patient Status Effective Date", () => {
    assertField(new PV2().patientStatusEffectiveDate(SENTINEL), 46);
  });

  test("PV2-47 Expected LOA Return Date Time", () => {
    assertField(new PV2().expectedLoaReturnDateTime(SENTINEL), 47);
  });

  test("PV2-48 Expected Pre Admission Testing Date Time", () => {
    assertField(new PV2().expectedPreAdmissionTestingDateTime(SENTINEL), 48);
  });

  test("PV2-49 Notify Clergy Code", () => {
    assertField(new PV2().notifyClergyCode(SENTINEL), 49);
  });
});
