// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXA segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXA } from "./RXA.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXA, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXA field positions", () => {
  test("RXA-23 Administered Drug Strength Volume", () => {
    assertField(new RXA().administeredDrugStrengthVolume(SENTINEL), 23);
  });

  test("RXA-24 Administered Drug Strength Volume Units", () => {
    const parts = new RXA().administeredDrugStrengthVolumeUnits({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[24]).toBe("C1^C2^C3");
  });

  test("RXA-25 Administered Barcode Identifier", () => {
    const parts = new RXA().administeredBarcodeIdentifier({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[25]).toBe("C1^C2^C3");
  });

  test("RXA-26 Pharmacy Order Type", () => {
    assertField(new RXA().pharmacyOrderType(SENTINEL), 26);
  });
});
