// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXD segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXD } from "./RXD.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXD, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXD field positions", () => {
  test("RXD-25 Supplementary Code", () => {
    const parts = new RXD().supplementaryCode("C1", "C2", "C3").encode().split("|");
    expect(parts[25]).toBe("C1^C2^C3");
  });

  test("RXD-26 Initiating Location", () => {
    const parts = new RXD().initiatingLocation("C1", "C2", "C3").encode().split("|");
    expect(parts[26]).toBe("C1^C2^C3");
  });

  test("RXD-27 Packaging Assembly Location", () => {
    const parts = new RXD().packagingAssemblyLocation("C1", "C2", "C3").encode().split("|");
    expect(parts[27]).toBe("C1^C2^C3");
  });

  test("RXD-28 Actual Drug Strength Volume", () => {
    assertField(new RXD().actualDrugStrengthVolume(SENTINEL), 28);
  });

  test("RXD-29 Actual Drug Strength Volume Units", () => {
    const parts = new RXD().actualDrugStrengthVolumeUnits("C1", "C2", "C3").encode().split("|");
    expect(parts[29]).toBe("C1^C2^C3");
  });

  test("RXD-30 Dispense To Pharmacy", () => {
    const parts = new RXD().dispenseToPharmacy("C1", "C2", "C3").encode().split("|");
    expect(parts[30]).toBe("C1^C2^C3");
  });

  test("RXD-31 Dispense To Pharmacy Address", () => {
    const parts = new RXD().dispenseToPharmacyAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[31]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("RXD-32 Pharmacy Order Type", () => {
    assertField(new RXD().pharmacyOrderType(SENTINEL), 32);
  });

  test("RXD-33 Dispense Type", () => {
    const parts = new RXD().dispenseType("C1", "C2", "C3").encode().split("|");
    expect(parts[33]).toBe("C1^C2^C3");
  });
});
