// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXE segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXE } from "./RXE.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXE, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXE field positions", () => {
  test("RXE-31 Supplementary Code", () => {
    const parts = new RXE().supplementaryCode("C1", "C2", "C3").encode().split("|");
    expect(parts[31]).toBe("C1^C2^C3");
  });

  test("RXE-32 Original Order Date Time", () => {
    assertField(new RXE().originalOrderDateTime(SENTINEL), 32);
  });

  test("RXE-33 Give Drug Strength Volume", () => {
    assertField(new RXE().giveDrugStrengthVolume(SENTINEL), 33);
  });

  test("RXE-34 Give Drug Strength Volume Units", () => {
    const parts = new RXE().giveDrugStrengthVolumeUnits("C1", "C2", "C3").encode().split("|");
    expect(parts[34]).toBe("C1^C2^C3");
  });

  test("RXE-35 Controlled Substance Schedule", () => {
    const parts = new RXE().controlledSubstanceSchedule("C1", "C2", "C3").encode().split("|");
    expect(parts[35]).toBe("C1^C2^C3");
  });

  test("RXE-36 Formulary Status", () => {
    assertField(new RXE().formularyStatus(SENTINEL), 36);
  });

  test("RXE-37 Pharmaceutical Substance Alternative", () => {
    const parts = new RXE().pharmaceuticalSubstanceAlternative("C1", "C2", "C3").encode().split("|");
    expect(parts[37]).toBe("C1^C2^C3");
  });

  test("RXE-38 Pharmacy Of Most Recent Fill", () => {
    const parts = new RXE().pharmacyOfMostRecentFill("C1", "C2", "C3").encode().split("|");
    expect(parts[38]).toBe("C1^C2^C3");
  });

  test("RXE-39 Initial Dispense Amount", () => {
    assertField(new RXE().initialDispenseAmount(SENTINEL), 39);
  });

  test("RXE-40 Dispensing Pharmacy", () => {
    const parts = new RXE().dispensingPharmacy("C1", "C2", "C3").encode().split("|");
    expect(parts[40]).toBe("C1^C2^C3");
  });

  test("RXE-41 Dispensing Pharmacy Address", () => {
    const parts = new RXE().dispensingPharmacyAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[41]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("RXE-42 Deliver To Patient Location", () => {
    assertField(new RXE().deliverToPatientLocation(SENTINEL), 42);
  });

  test("RXE-43 Deliver To Address", () => {
    const parts = new RXE().deliverToAddress("C1", "C2", "C3", "C4", "C5", "C6").encode().split("|");
    expect(parts[43]).toBe("C1^C2^C3^C4^C5^C6");
  });

  test("RXE-44 Pharmacy Order Type", () => {
    assertField(new RXE().pharmacyOrderType(SENTINEL), 44);
  });
});
