// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the RXO segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { RXO } from "./RXO.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: RXO, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("RXO field positions", () => {
  test("RXO-23 Total Daily Dose", () => {
    const parts = new RXO().totalDailyDose({ quantity: "C1", units: "C2" }).encode().split("|");
    expect(parts[23]).toBe("C1^C2");
  });

  test("RXO-24 Supplementary Code", () => {
    const parts = new RXO().supplementaryCode({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[24]).toBe("C1^C2^C3");
  });

  test("RXO-25 Requested Drug Strength Volume", () => {
    assertField(new RXO().requestedDrugStrengthVolume(SENTINEL), 25);
  });

  test("RXO-26 Requested Drug Strength Volume Units", () => {
    const parts = new RXO().requestedDrugStrengthVolumeUnits({ code: "C1", text: "C2", codingSystem: "C3" }).encode().split("|");
    expect(parts[26]).toBe("C1^C2^C3");
  });

  test("RXO-27 Pharmacy Order Type", () => {
    assertField(new RXO().pharmacyOrderType(SENTINEL), 27);
  });

  test("RXO-28 Dispensing Interval", () => {
    assertField(new RXO().dispensingInterval(SENTINEL), 28);
  });
});
