// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the SCH segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { SCH } from "./SCH.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: SCH, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("SCH field positions", () => {
  test("SCH-26 Placer Order Number", () => {
    const parts = new SCH().placerOrderNumber("C1", "C2").encode().split("|");
    expect(parts[26]).toBe("C1^C2");
  });

  test("SCH-27 Filler Order Number", () => {
    const parts = new SCH().fillerOrderNumber("C1", "C2").encode().split("|");
    expect(parts[27]).toBe("C1^C2");
  });
});
