// AUTO-GENERATED by codegen/generate-field-position-tests.ts — do not edit by hand.
// Regenerate with: npx tsx codegen/generate-field-position-tests.ts
//
// Field-position tests for the STF segment (HL7 v2.5.1). Asserting
// the exact field/component index — not just substring presence — is what
// catches off-by-one field placement and composite component-position bugs.
import { test, expect, describe } from "vitest";
import { STF } from "./STF.ts";

const SENTINEL = "ZQXP0S";

// Assert the sentinel encodes into field `splitIndex` (first component, first
// subcomponent) and nowhere else.
function assertField(seg: STF, splitIndex: number): void {
  const parts = seg.encode().split("|");
  const value = parts[splitIndex]?.split("^")[0]?.split("&")[0];
  expect(value).toBe(SENTINEL);
  expect(parts.filter((p) => p.includes(SENTINEL)).length).toBe(1);
}

describe("STF field positions", () => {
  test("STF-27 Race", () => {
    const parts = new STF().race("C1", "C2", "C3").encode().split("|");
    expect(parts[27]).toBe("C1^C2^C3");
  });

  test("STF-28 Ethnic Group", () => {
    const parts = new STF().ethnicGroup("C1", "C2", "C3").encode().split("|");
    expect(parts[28]).toBe("C1^C2^C3");
  });

  test("STF-29 Reactivation Approval Indicator", () => {
    assertField(new STF().reactivationApprovalIndicator(SENTINEL), 29);
  });

  test("STF-30 Citizenship", () => {
    const parts = new STF().citizenship("C1", "C2", "C3").encode().split("|");
    expect(parts[30]).toBe("C1^C2^C3");
  });

  test("STF-31 Death Date And Time", () => {
    assertField(new STF().deathDateAndTime(SENTINEL), 31);
  });

  test("STF-32 Death Indicator", () => {
    assertField(new STF().deathIndicator(SENTINEL), 32);
  });

  test("STF-33 Institution Relationship Type Code", () => {
    const parts = new STF().institutionRelationshipTypeCode("C1", "C2", "C3").encode().split("|");
    expect(parts[33]).toBe("C1^C2^C3");
  });

  test("STF-34 Institution Relationship Period", () => {
    const parts = new STF().institutionRelationshipPeriod("C1", "C2").encode().split("|");
    expect(parts[34]).toBe("C1^C2");
  });

  test("STF-35 Expected Return Date", () => {
    assertField(new STF().expectedReturnDate(SENTINEL), 35);
  });

  test("STF-36 Cost Center Code", () => {
    const parts = new STF().costCenterCode("C1", "C2", "C3").encode().split("|");
    expect(parts[36]).toBe("C1^C2^C3");
  });

  test("STF-37 Generic Classification Indicator", () => {
    assertField(new STF().genericClassificationIndicator(SENTINEL), 37);
  });

  test("STF-38 Inactive Reason Code", () => {
    const parts = new STF().inactiveReasonCode("C1", "C2", "C3").encode().split("|");
    expect(parts[38]).toBe("C1^C2^C3");
  });
});
